"""Inventory for the Multiple View Geometry notebook course."""

from __future__ import annotations

PARTS = [{'description': 'Projective 2D/3D geometry, homographies, numerical estimation, and error '
                 'analysis.',
  'folder': 'part-00-background-projective-geometry-transformations-and-estimation',
  'label': 'Part 0',
  'title': 'The Background: Projective Geometry, Transformations and Estimation'},
 {'description': 'Camera matrices, calibration, distortion, vanishing geometry, and single-view '
                 'measurement.',
  'folder': 'part-01-camera-geometry-and-single-view-geometry',
  'label': 'Part I',
  'title': 'Camera Geometry and Single View Geometry'},
 {'description': 'Epipolar geometry, the fundamental matrix, triangulation, homographies, '
                 'rectification, and affine stereo.',
  'folder': 'part-02-two-view-geometry',
  'label': 'Part II',
  'title': 'Two-View Geometry'},
 {'description': 'The trifocal tensor, point and line transfer, three-view constraints, and tensor '
                 'estimation.',
  'folder': 'part-03-three-view-geometry',
  'label': 'Part III',
  'title': 'Three-View Geometry'},
 {'description': 'Multiple-view tensors, factorization, bundle adjustment, auto-calibration, '
                 'duality, cheirality, and degeneracies.',
  'folder': 'part-04-n-view-geometry',
  'label': 'Part IV',
  'title': 'N-View Geometry'},
 {'description': 'Tensor notation, statistics, parameter estimation, matrix decompositions, least '
                 'squares, iterative methods, and special homographies.',
  'folder': 'part-05-appendices',
  'label': 'Part V',
  'title': 'Appendices'}]

ENTRIES = [{'checks': ['projected points satisfy homogeneous scale equivalence',
             'two-view residuals are near zero for synthetic correspondences',
             'triangulated points reproject to both cameras',
             'metric upgrade changes distances but preserves incidence'],
  'concepts': ['projective geometry gives one language for images and 3D scenes',
               'camera projection loses depth but preserves incidence',
               'two and three views convert correspondence into structure constraints',
               'metric information returns only after extra calibration or scene assumptions'],
  'focus': 'Projection, ambiguity, transfer, Euclidean upgrade, and the full multiple-view '
           'reconstruction arc.',
  'folder': 'chapter-01-introduction-a-tour-of-multiple-view-geometry',
  'kind': 'chapter',
  'label': 'Chapter 01',
  'mode': 'tour',
  'notebook': '01-introduction-a-tour-of-multiple-view-geometry.ipynb',
  'number': 1,
  'part': None,
  'pdf': '19-40',
  'printed': '1-22',
  'title': 'Introduction: A Tour of Multiple View Geometry',
  'topic': 'chapter-01',
  'visuals': ['pinhole projection tour',
              'one-view two-view three-view comparison',
              'projective ambiguity ladder',
              'transfer and reconstruction pipeline']},
 {'checks': ['line-point incidence is scale invariant',
             'lines transform by inverse transpose',
             'cross-ratios remain stable under homographies',
             'rectified parallel lines meet on the recovered line at infinity'],
  'concepts': ['homogeneous 2D points represent Euclidean points plus ideal directions',
               'lines and points are dual incidence objects',
               'homographies preserve collinearity but not Euclidean measurements',
               'affine and metric rectification restore chosen invariants'],
  'focus': 'Points, lines, conics, homographies, transformation hierarchy, rectification, and '
           'metric recovery in the projective plane.',
  'folder': 'chapter-02-projective-geometry-and-transformations-of-2d',
  'kind': 'chapter',
  'label': 'Chapter 02',
  'mode': 'p2',
  'notebook': '02-projective-geometry-and-transformations-of-2d.ipynb',
  'number': 2,
  'part': 'part-00-background-projective-geometry-transformations-and-estimation',
  'pdf': '43-82',
  'printed': '25-64',
  'title': 'Projective Geometry and Transformations of 2D',
  'topic': 'chapter-02',
  'visuals': ['homography grid deformation',
              'vanishing line and affine rectification',
              'conic pole-polar diagram',
              'transformation hierarchy panel']},
 {'checks': ['plane-point incidence vanishes for sampled points',
             'line coordinates satisfy the Plucker quadratic relation',
             'quadric samples satisfy the implicit equation',
             'metric directions obey the absolute conic orthogonality test'],
  'concepts': ['3D projective coordinates keep finite points and directions in one algebra',
               'planes and points meet through a single bilinear incidence test',
               'lines require Plucker-style constraints rather than only two endpoints',
               'the plane at infinity and absolute conic encode affine and metric upgrades'],
  'focus': 'Projective 3D points, planes, lines, quadrics, twisted cubics, the plane at infinity, '
           'and the absolute conic.',
  'folder': 'chapter-03-projective-geometry-and-transformations-of-3d',
  'kind': 'chapter',
  'label': 'Chapter 03',
  'mode': 'p3',
  'notebook': '03-projective-geometry-and-transformations-of-3d.ipynb',
  'number': 3,
  'part': 'part-00-background-projective-geometry-transformations-and-estimation',
  'pdf': '83-104',
  'printed': '65-86',
  'title': 'Projective Geometry and Transformations of 3D',
  'topic': 'chapter-03',
  'visuals': ['3D incidence viewer',
              'skew-line and Plucker relation demo',
              'quadric slicing scene',
              'absolute conic upgrade sketch']},
 {'checks': ['DLT residual decreases after normalization',
             'estimated H is scale normalized',
             'RANSAC inlier count exceeds the outlier count',
             'geometric reprojection error is lower than the raw algebraic baseline'],
  'concepts': ['a homography estimate is a nullspace problem before it is an image warp',
               'normalization changes numerical conditioning without changing geometry',
               'geometric error is measured in image coordinates rather than coefficient space',
               'robust estimation separates inliers from misleading correspondences'],
  'focus': 'DLT homography estimation, geometric and statistical costs, normalization, iterative '
           'refinement, robust estimation, and automatic matching.',
  'folder': 'chapter-04-estimation-2d-projective-transformations',
  'kind': 'chapter',
  'label': 'Chapter 04',
  'mode': 'homography-estimation',
  'notebook': '04-estimation-2d-projective-transformations.ipynb',
  'number': 4,
  'part': 'part-00-background-projective-geometry-transformations-and-estimation',
  'pdf': '105-149',
  'printed': '87-131',
  'title': 'Estimation: 2D Projective Transformations',
  'topic': 'chapter-04',
  'visuals': ['noisy correspondence homography',
              'normalization condition-number heatmap',
              'RANSAC inlier map',
              'cost-function comparison panel']},
 {'checks': ['sample covariance is positive semidefinite',
             'empirical coverage roughly matches the requested confidence gate',
             'RMSE grows with injected noise',
             'Monte Carlo means stay close to the noiseless estimate'],
  'concepts': ['an estimator is judged by residuals, variance, and sensitivity, not only by one '
               'answer',
               'covariance describes local uncertainty in estimated geometry',
               'Monte Carlo trials make algorithm stability visible',
               'performance bounds are useful only when tied to observable diagnostics'],
  'focus': 'Performance bounds, covariance propagation, Monte Carlo covariance, and empirical '
           'evaluation of geometric estimators.',
  'folder': 'chapter-05-algorithm-evaluation-and-error-analysis',
  'kind': 'chapter',
  'label': 'Chapter 05',
  'mode': 'error',
  'notebook': '05-algorithm-evaluation-and-error-analysis.ipynb',
  'number': 5,
  'part': 'part-00-background-projective-geometry-transformations-and-estimation',
  'pdf': '150-168',
  'printed': '132-150',
  'title': 'Algorithm Evaluation and Error Analysis',
  'topic': 'chapter-05',
  'visuals': ['error ellipse field',
              'noise sweep dashboard',
              'Monte Carlo covariance cloud',
              'bias-variance comparison']},
 {'checks': ['P times the camera center is zero',
             'RQ-style factorization reconstructs the camera matrix',
             'projected homogeneous coordinates are scale equivalent',
             'affine projection keeps parallel world directions parallel in the image'],
  'concepts': ['a camera matrix maps world rays to image points through homogeneous projection',
               'the camera center is the nullspace of P',
               'intrinsics and extrinsics separate internal pixel geometry from camera pose',
               'affine and weak-perspective cameras are controlled approximations'],
  'focus': 'Finite cameras, projective cameras, affine cameras, intrinsic/extrinsic factorization, '
           'and alternative camera models.',
  'folder': 'chapter-06-camera-models',
  'kind': 'chapter',
  'label': 'Chapter 06',
  'mode': 'camera',
  'notebook': '06-camera-models.ipynb',
  'number': 6,
  'part': 'part-01-camera-geometry-and-single-view-geometry',
  'pdf': '171-195',
  'printed': '153-177',
  'title': 'Camera Models',
  'topic': 'chapter-06',
  'visuals': ['camera frustum and image plane',
              'intrinsic parameter slider map',
              'projection-class comparison',
              'camera-center nullspace diagram']},
 {'checks': ['estimated P reprojects calibration points with low RMSE',
             'radial correction reduces curved residual structure',
             'camera center remains finite for a finite camera',
             'constrained estimates preserve their intended parameter restrictions'],
  'concepts': ['camera calibration is a linear solve followed by geometric validation',
               'restricted camera models reduce degrees of freedom by using prior structure',
               'radial distortion is visible as a systematic residual pattern',
               'calibration quality is best read from reprojection errors'],
  'focus': 'Camera resectioning from 3D-2D correspondences, geometric error, constrained '
           'calibration, and radial distortion.',
  'folder': 'chapter-07-computation-of-the-camera-matrix-p',
  'kind': 'chapter',
  'label': 'Chapter 07',
  'mode': 'camera-estimation',
  'notebook': '07-computation-of-the-camera-matrix-p.ipynb',
  'number': 7,
  'part': 'part-01-camera-geometry-and-single-view-geometry',
  'pdf': '196-212',
  'printed': '178-194',
  'title': 'Computation of the Camera Matrix P',
  'topic': 'chapter-07',
  'visuals': ['calibration target projection',
              'camera resection residual vectors',
              'distortion and undistortion grid',
              'restricted-camera parameter panel']},
 {'checks': ['orthogonal vanishing points satisfy the IAC relation',
             'parallel 3D lines meet at a common image vanishing point',
             'height ratios are invariant under the constructed homology',
             'projected conic points satisfy the conic equation'],
  'concepts': ['single-view measurement is possible when projective ambiguity is pinned by scene '
               'structure',
               'vanishing points encode 3D directions',
               'the image of the absolute conic converts orthogonality into calibration equations',
               'planes and conics transfer useful metric information through projection'],
  'focus': 'Projection of planes, lines, conics, quadrics, silhouettes, vanishing points, the '
           'image of the absolute conic, and single-view reconstruction.',
  'folder': 'chapter-08-more-single-view-geometry',
  'kind': 'chapter',
  'label': 'Chapter 08',
  'mode': 'single-view',
  'notebook': '08-more-single-view-geometry.ipynb',
  'number': 8,
  'part': 'part-01-camera-geometry-and-single-view-geometry',
  'pdf': '213-254',
  'printed': '195-236',
  'title': 'More Single View Geometry',
  'topic': 'chapter-08',
  'visuals': ['room vanishing-point triangle',
              'image of absolute conic constraints',
              'single-view height measurement',
              'projected conic and quadric silhouettes']},
 {'checks': ['x2 transpose F x1 is near zero',
             'F has rank two',
             'epipoles lie in the left and right nullspaces',
             'essential matrix singular values occur as a repeated pair and zero'],
  'concepts': ['corresponding points lie on paired epipolar lines',
               'the fundamental matrix is rank two and maps points to lines',
               'epipoles are images of the opposite camera centers',
               'calibration upgrades F to the essential matrix with extra singular-value '
               'structure'],
  'focus': 'Epipolar geometry, the fundamental matrix, special motions, epipoles, camera '
           'retrieval, and the essential matrix.',
  'folder': 'chapter-09-epipolar-geometry-and-the-fundamental-matrix',
  'kind': 'chapter',
  'label': 'Chapter 09',
  'mode': 'epipolar',
  'notebook': '09-epipolar-geometry-and-the-fundamental-matrix.ipynb',
  'number': 9,
  'part': 'part-02-two-view-geometry',
  'pdf': '257-279',
  'printed': '239-261',
  'title': 'Epipolar Geometry and the Fundamental Matrix',
  'topic': 'chapter-09',
  'visuals': ['two-camera epipolar fan',
              'moving-point epiline widget sketch',
              'F and E singular value panel',
              'camera retrieval diagram']},
 {'checks': ['transformed cameras and points keep identical image projections',
             'reprojection error remains low after projective warps',
             'affine upgrade fixes a plane at infinity',
             'metric upgrade restores Euclidean angle checks'],
  'concepts': ['image correspondences determine structure only up to a 3D projective ambiguity',
               'the same images can be produced by transformed cameras and transformed points',
               'stratification adds affine and metric constraints in stages',
               'ground truth is useful for measuring ambiguity but not required for reprojection'],
  'focus': 'Projective reconstruction, reconstruction ambiguity, the projective reconstruction '
           'theorem, and stratified upgrade.',
  'folder': 'chapter-10-3d-reconstruction-of-cameras-and-structure',
  'kind': 'chapter',
  'label': 'Chapter 10',
  'mode': 'reconstruction',
  'notebook': '10-3d-reconstruction-of-cameras-and-structure.ipynb',
  'number': 10,
  'part': 'part-02-two-view-geometry',
  'pdf': '280-296',
  'printed': '262-278',
  'title': '3D Reconstruction of Cameras and Structure',
  'topic': 'chapter-10',
  'visuals': ['projective ambiguity warp',
              'stratified reconstruction ladder',
              'camera and point reconstruction scene',
              'reprojection-invariance dashboard']},
 {'checks': ['rank enforcement sets the smallest singular value to zero',
             'Sampson errors are smaller for inliers than outliers',
             'RANSAC recovers a high-consensus F',
             'rectified corresponding points have nearly equal vertical coordinates'],
  'concepts': ['the eight-point algorithm is a linear fit constrained back to rank two',
               'normalization is essential for stable fundamental matrix estimation',
               'Sampson error turns the epipolar constraint into a first-order distance',
               'rectification makes matching a one-dimensional search along rows'],
  'focus': 'Normalized eight-point estimation, algebraic minimization, geometric distance, robust '
           'computation, degeneracies, envelopes, and rectification.',
  'folder': 'chapter-11-computation-of-the-fundamental-matrix-f',
  'kind': 'chapter',
  'label': 'Chapter 11',
  'mode': 'fundamental-estimation',
  'notebook': '11-computation-of-the-fundamental-matrix-f.ipynb',
  'number': 11,
  'part': 'part-02-two-view-geometry',
  'pdf': '297-327',
  'printed': '279-309',
  'title': 'Computation of the Fundamental Matrix F',
  'topic': 'chapter-11',
  'visuals': ['match pipeline and inlier map',
              'Sampson contour field',
              'rank enforcement singular values',
              'rectified epipolar-line panel']},
 {'checks': ['triangulated points reproject to both images',
             'ray angle predicts depth uncertainty',
             'refinement lowers geometric reprojection error',
             'estimated covariance is positive semidefinite'],
  'concepts': ['triangulation intersects back-projected rays that usually miss because of noise',
               'linear methods produce an initial point for geometric refinement',
               'uncertainty grows when rays meet at a small angle',
               'line reconstruction follows the same back-projection logic with line constraints'],
  'focus': 'Linear triangulation, geometric error, Sampson correction, optimal correction, '
           'uncertainty, and line reconstruction.',
  'folder': 'chapter-12-structure-computation',
  'kind': 'chapter',
  'label': 'Chapter 12',
  'mode': 'triangulation',
  'notebook': '12-structure-computation.ipynb',
  'number': 12,
  'part': 'part-02-two-view-geometry',
  'pdf': '328-342',
  'printed': '310-324',
  'title': 'Structure Computation',
  'topic': 'chapter-12',
  'visuals': ['skew-ray closest approach',
              'linear versus optimal triangulation',
              'uncertainty ellipsoid',
              'line reconstruction from image lines']},
 {'checks': ['planar points transfer with low homography residual',
             'off-plane parallax is nonzero and epipolar',
             'F reconstructed from H satisfies point constraints',
             'H infinity agrees with the rotation-induced transfer'],
  'concepts': ['a plane turns two-view transfer into a homography',
               'points off the plane reveal parallax relative to the plane-induced transfer',
               'F and a plane homography constrain one another',
               'the infinite homography captures pure rotation and calibration-dependent transfer'],
  'focus': 'Plane-induced homographies, recovering planes, F from a plane homography, parallax, '
           'and the infinite homography.',
  'folder': 'chapter-13-scene-planes-and-homographies',
  'kind': 'chapter',
  'label': 'Chapter 13',
  'mode': 'plane-homography',
  'notebook': '13-scene-planes-and-homographies.ipynb',
  'number': 13,
  'part': 'part-02-two-view-geometry',
  'pdf': '343-361',
  'printed': '325-343',
  'title': 'Scene Planes and Homographies',
  'topic': 'chapter-13',
  'visuals': ['plane transfer field',
              'parallax vector plot',
              'F-from-H consistency diagram',
              'infinite homography comparison']},
 {'checks': ['affine epipolar residuals are linear in image coordinates',
             'parallel epipolar lines share a direction',
             'bas-relief transformed points preserve affine reprojections',
             'recovered motion satisfies the affine camera equations'],
  'concepts': ['affine cameras simplify epipolar geometry by pushing epipoles to infinity',
               'affine F has fewer parameters than a projective fundamental matrix',
               'bas-relief ambiguity preserves many image measurements while changing depth',
               'motion recovery is constrained by affine viewing assumptions'],
  'focus': 'Affine cameras, affine fundamental matrix estimation, triangulation, affine '
           'reconstruction, bas-relief ambiguity, and motion recovery.',
  'folder': 'chapter-14-affine-epipolar-geometry',
  'kind': 'chapter',
  'label': 'Chapter 14',
  'mode': 'affine-epipolar',
  'notebook': '14-affine-epipolar-geometry.ipynb',
  'number': 14,
  'part': 'part-02-two-view-geometry',
  'pdf': '362-380',
  'printed': '344-362',
  'title': 'Affine Epipolar Geometry',
  'topic': 'chapter-14',
  'visuals': ['orthographic two-camera scene',
              'affine epipolar line family',
              'bas-relief ambiguity slider sketch',
              'affine triangulation panel']},
 {'checks': ['trilinear residuals vanish for synthetic correspondences',
             'transferred points reproject near the third observation',
             'tensor slices have the expected rank behavior',
             'pairwise F matrices satisfy their epipolar constraints'],
  'concepts': ['three views encode point and line transfer in a single tensor object',
               'the tensor packages how planes through one camera induce correspondences in the '
               'others',
               'point transfer becomes reliable when two views constrain the third',
               'pairwise fundamental matrices are shadows of the three-view relation'],
  'focus': 'The geometric basis of the trifocal tensor, tensor notation, transfer, and three-view '
           'fundamental matrices.',
  'folder': 'chapter-15-the-trifocal-tensor',
  'kind': 'chapter',
  'label': 'Chapter 15',
  'mode': 'trifocal',
  'notebook': '15-the-trifocal-tensor.ipynb',
  'number': 15,
  'part': 'part-03-three-view-geometry',
  'pdf': '383-408',
  'printed': '365-390',
  'title': 'The Trifocal Tensor',
  'topic': 'chapter-15',
  'visuals': ['three-camera transfer studio',
              'tensor slice explorer',
              'point-line transfer diagram',
              'pairwise F recovery panel']},
 {'checks': ['linear tensor residuals decrease with normalization',
             'robust fitting rejects high-transfer-error triplets',
             'estimated transfer points land near observations',
             'geometric refinement improves the median transfer error'],
  'concepts': ['trifocal estimation is linear in measurements before enforcing geometric validity',
               'normalization stabilizes multi-image tensor fitting',
               'transfer error is the natural observable quality measure',
               'robust triplet selection protects the tensor from bad tracks'],
  'focus': 'Linear, algebraic, geometric, and robust estimation of the trifocal tensor from point '
           'and line correspondences.',
  'folder': 'chapter-16-computation-of-the-trifocal-tensor-t',
  'kind': 'chapter',
  'label': 'Chapter 16',
  'mode': 'trifocal-estimation',
  'notebook': '16-computation-of-the-trifocal-tensor-t.ipynb',
  'number': 16,
  'part': 'part-03-three-view-geometry',
  'pdf': '409-426',
  'printed': '391-408',
  'title': 'Computation of the Trifocal Tensor T',
  'topic': 'chapter-16',
  'visuals': ['triplet correspondence lab',
              'transfer-error landscape',
              'robust tensor inlier plot',
              'normalization effect panel']},
 {'checks': ['counted degrees of freedom match the synthetic parameterization',
             'selected determinants vanish on consistent tracks',
             'rank drops identify redundant equations',
             'equation subsets preserve the same reconstruction residual'],
  'concepts': ['multi-view tensors form a ladder of constraints as more cameras observe the same '
               'structure',
               'not every algebraic equation contributes independent information',
               'counting arguments reveal the degrees of freedom behind reconstruction',
               'useful equations are chosen for stability as well as formal validity'],
  'focus': 'Bilinear, trilinear, and quadrilinear relations; plane intersections; counting '
           'arguments; independent equations; and equation choice.',
  'folder': 'chapter-17-n-linearities-and-multiple-view-tensors',
  'kind': 'chapter',
  'label': 'Chapter 17',
  'mode': 'nlinear',
  'notebook': '17-n-linearities-and-multiple-view-tensors.ipynb',
  'number': 17,
  'part': 'part-04-n-view-geometry',
  'pdf': '429-451',
  'printed': '411-433',
  'title': 'N-Linearities and Multiple View Tensors',
  'topic': 'chapter-17',
  'visuals': ['tensor ladder diagram',
              'determinant block relations',
              'degree-of-freedom calculator',
              'independent-equation graph']},
 {'checks': ['affine track matrix has low numerical rank',
             'bundle-adjustment residual decreases',
             'sparse normal matrix has the expected block structure',
             'factorization reconstructs held-out observations with small error'],
  'concepts': ['tracks across many frames create a sparse camera-point estimation problem',
               'factorization exposes low-rank structure in affine image measurements',
               'non-rigid shape adds modes rather than a single rigid point set',
               'bundle adjustment improves all cameras and points together'],
  'focus': 'Bundle adjustment, affine factorization, non-rigid factorization, projective '
           'factorization, plane-based reconstruction, and sequences.',
  'folder': 'chapter-18-n-view-computational-methods',
  'kind': 'chapter',
  'label': 'Chapter 18',
  'mode': 'nview-methods',
  'notebook': '18-n-view-computational-methods.ipynb',
  'number': 18,
  'part': 'part-04-n-view-geometry',
  'pdf': '452-475',
  'printed': '434-457',
  'title': 'N-View Computational Methods',
  'topic': 'chapter-18',
  'visuals': ['track matrix SVD',
              'sparse bundle-adjustment graph',
              'cost descent plot',
              'non-rigid mode panel']},
 {'checks': ['recovered K has positive diagonal entries',
             'calibration constraints reduce algebraic residuals',
             'DAQ candidates have the expected signature pattern',
             'rotation-only constraints agree across images'],
  'concepts': ['auto-calibration recovers metric camera information from constraints across views',
               'the absolute dual quadric is a carrier for calibration constraints',
               'special motions add constraints but may also create degeneracies',
               'stratified solutions turn projective reconstructions into metric ones step by '
               'step'],
  'focus': 'Algebraic auto-calibration, the absolute dual quadric, Kruppa equations, stratified '
           'solutions, rotating cameras, planar motion, turntables, and stereo rigs.',
  'folder': 'chapter-19-auto-calibration',
  'kind': 'chapter',
  'label': 'Chapter 19',
  'mode': 'autocalibration',
  'notebook': '19-auto-calibration.ipynb',
  'number': 19,
  'part': 'part-04-n-view-geometry',
  'pdf': '476-519',
  'printed': '458-501',
  'title': 'Auto-Calibration',
  'topic': 'chapter-19',
  'visuals': ['calibration constraint accumulator',
              'absolute dual quadric viewer',
              'Kruppa constraint sketch',
              'rotating-camera calibration panel']},
 {'checks': ['dual incidence matrices have matching zero patterns',
             'primal and dual residuals agree on synthetic data',
             'reduced variables reproduce the target measurements',
             'graph connectivity predicts recoverable components'],
  'concepts': ['duality turns camera-point incidence into a complementary reconstruction problem',
               'reduced reconstruction keeps only the variables needed for a chosen query',
               'incidence graphs clarify which observations constrain which entities',
               'dual formulations preserve reprojection logic while changing algebraic roles'],
  'focus': 'Carlsson-Weinshall duality and reduced reconstruction through the exchange of point '
           'and camera roles.',
  'folder': 'chapter-20-duality',
  'kind': 'chapter',
  'label': 'Chapter 20',
  'mode': 'duality',
  'notebook': '20-duality.ipynb',
  'number': 20,
  'part': 'part-04-n-view-geometry',
  'pdf': '520-532',
  'printed': '502-514',
  'title': 'Duality',
  'topic': 'chapter-20',
  'visuals': ['point-camera dual swap',
              'incidence bipartite graph',
              'reduced reconstruction panel',
              'dual residual comparison']},
 {'checks': ['visible points have positive projective depth',
             'cheiral inequalities are feasible for the selected reconstruction',
             'quasi-affine transforms preserve depth signs',
             'third-view predictions match the synthetic visibility mask'],
  'concepts': ['projective reconstruction must still respect which points are in front of cameras',
               'cheirality is expressed as a sign constraint on depths',
               'quasi-affine transformations preserve the visible side of cameras',
               'visibility in a third view can be reasoned about through inequalities'],
  'focus': 'Quasi-affine transformations, front/back camera tests, visible point sets, cheiral '
           'inequalities, third-view visibility, and depth ordering.',
  'folder': 'chapter-21-cheirality',
  'kind': 'chapter',
  'label': 'Chapter 21',
  'mode': 'cheirality',
  'notebook': '21-cheirality.ipynb',
  'number': 21,
  'part': 'part-04-n-view-geometry',
  'pdf': '533-550',
  'printed': '515-532',
  'title': 'Cheirality',
  'topic': 'chapter-21',
  'visuals': ['depth-sign viewer',
              'cheiral half-space plot',
              'third-view visibility map',
              'quasi-affine transformation panel']},
 {'checks': ['design matrices lose rank in degenerate layouts',
             'nullspace dimension increases for critical configurations',
             'alternative reconstructions share similar reprojection error',
             'diagnostics flag the degenerate sample before final estimation'],
  'concepts': ['degeneracy means the data no longer constrains a unique geometric answer',
               'rank and nullity diagnostics reveal many critical configurations',
               'some scene/camera arrangements create plausible but wrong reconstructions',
               'good algorithms report degeneracy instead of forcing a confident estimate'],
  'focus': 'Degeneracies in camera resectioning, two-view and three-view reconstruction, critical '
           'surfaces, and ambiguous configurations.',
  'folder': 'chapter-22-degenerate-configurations',
  'kind': 'chapter',
  'label': 'Chapter 22',
  'mode': 'degenerate',
  'notebook': '22-degenerate-configurations.ipynb',
  'number': 22,
  'part': 'part-04-n-view-geometry',
  'pdf': '551-578',
  'printed': '533-560',
  'title': 'Degenerate Configurations',
  'topic': 'chapter-22',
  'visuals': ['critical-surface gallery',
              'rank-nullity dashboard',
              'two-view degeneracy scene',
              'three-view ambiguity panel']},
 {'checks': ['basis-transformed coordinates represent the same point',
             'contracted scalar values remain invariant',
             'epsilon contractions match cross products',
             'tensor slices transform according to the chosen bases'],
  'concepts': ['indices describe how coordinates transform under basis changes',
               'contractions pair upper and lower indices into invariant quantities',
               'the epsilon tensor encodes cross products and determinants',
               'tensor notation is practical when arrays have more than two meaningful axes'],
  'focus': 'Covariant and contravariant indices, basis changes, contractions, the epsilon tensor, '
           'and trifocal tensor notation.',
  'folder': 'appendix-01-tensor-notation',
  'kind': 'appendix',
  'label': 'Appendix 01',
  'mode': 'tensor',
  'notebook': 'a01-tensor-notation.ipynb',
  'number': 101,
  'part': 'part-05-appendices',
  'pdf': '580-582',
  'printed': '562-564',
  'title': 'Tensor Notation',
  'topic': 'appendix-01',
  'visuals': ['basis-change index diagram',
              'contraction flow chart',
              'epsilon tensor determinant panel',
              'trifocal tensor slice notation']},
 {'checks': ['sample covariance is positive semidefinite',
             'Mahalanobis distances follow the expected distribution roughly',
             'confidence gates contain the planned fraction of samples',
             'whitening produces nearly identity covariance'],
  'concepts': ['Gaussian noise models turn residual vectors into probabilities',
               'covariance ellipses reveal anisotropic uncertainty',
               'Mahalanobis distance is the residual measured in covariance units',
               'chi-square gates convert residual magnitude into an acceptance test'],
  'focus': 'Gaussian measurement models, covariance, Mahalanobis distance, confidence gates, and '
           'chi-square diagnostics.',
  'folder': 'appendix-02-gaussian-normal-and-chi2-distributions',
  'kind': 'appendix',
  'label': 'Appendix 02',
  'mode': 'statistics',
  'notebook': 'a02-gaussian-normal-and-chi2-distributions.ipynb',
  'number': 102,
  'part': 'part-05-appendices',
  'pdf': '583-585',
  'printed': '565-567',
  'title': 'Gaussian and Chi-square Distributions',
  'topic': 'appendix-02',
  'visuals': ['covariance ellipse field',
              'Mahalanobis distance contours',
              'chi-square confidence gates',
              'sample coverage dashboard']},
 {'checks': ['maximum likelihood coincides with least squares for isotropic Gaussian noise',
             'empirical variance exceeds the lower-bound estimate',
             'bias shrinks with more measurements in the synthetic example',
             'posterior normalization sums to one in the discrete lab'],
  'concepts': ['estimation turns noisy measurements into parameter distributions',
               'maximum likelihood is a geometry-aware choice only after defining the noise model',
               'bias and variance describe different failure modes',
               'bounds are useful when compared with Monte Carlo behavior'],
  'focus': 'Bias, variance, maximum likelihood, posterior estimation, Fisher information, and '
           'Cramer-Rao style bounds.',
  'folder': 'appendix-03-parameter-estimation',
  'kind': 'appendix',
  'label': 'Appendix 03',
  'mode': 'parameter-estimation',
  'notebook': 'a03-parameter-estimation.ipynb',
  'number': 103,
  'part': 'part-05-appendices',
  'pdf': '586-595',
  'printed': '568-577',
  'title': 'Parameter Estimation',
  'topic': 'appendix-03',
  'visuals': ['likelihood curve',
              'estimator bias sweep',
              'variance versus bound panel',
              'posterior update diagram']},
 {'checks': ['SVD reconstruction matches the original matrix',
             'nullspace vectors satisfy A v near zero',
             'positive-definite matrices have positive eigenvalues',
             'factorized camera matrices reconstruct P up to scale'],
  'concepts': ['matrix decompositions expose geometric structure hidden in coefficients',
               'SVD identifies rank, nullspaces, conditioning, and best low-rank approximations',
               'RQ-style decompositions support camera calibration factorization',
               'positive definite matrices encode valid covariance and conic constraints'],
  'focus': 'Rank, nullspaces, eigenstructure, SVD, Cholesky, QR/RQ, Schur, and matrix identities '
           'used by MVG algorithms.',
  'folder': 'appendix-04-matrix-properties-and-decompositions',
  'kind': 'appendix',
  'label': 'Appendix 04',
  'mode': 'matrix',
  'notebook': 'a04-matrix-properties-and-decompositions.ipynb',
  'number': 104,
  'part': 'part-05-appendices',
  'pdf': '596-605',
  'printed': '578-587',
  'title': 'Matrix Properties and Decompositions',
  'topic': 'appendix-04',
  'visuals': ['SVD geometry panel',
              'nullspace and rank dashboard',
              'RQ camera factorization sketch',
              'positive-definite ellipse view']},
 {'checks': ['least-squares residual is orthogonal to the column space',
             'SVD and normal-equation solutions agree on well-conditioned examples',
             'weighted residuals shrink in high-confidence directions',
             'TLS line fitting reduces orthogonal rather than vertical distance'],
  'concepts': ['least squares projects impossible constraints onto the closest attainable model',
               'normal equations are useful but can square conditioning problems',
               'total least squares treats errors in the design matrix as well as observations',
               'weights encode unequal measurement uncertainty'],
  'focus': 'Linear least squares, normal equations, total least squares, weighted least squares, '
           'constrained systems, and sparse symmetric equations.',
  'folder': 'appendix-05-least-squares-minimization',
  'kind': 'appendix',
  'label': 'Appendix 05',
  'mode': 'least-squares',
  'notebook': 'a05-least-squares-minimization.ipynb',
  'number': 105,
  'part': 'part-05-appendices',
  'pdf': '606-614',
  'printed': '588-596',
  'title': 'Least-squares Minimization',
  'topic': 'appendix-05',
  'visuals': ['residual projection diagram',
              'normal-equation conditioning panel',
              'total versus ordinary least-squares comparison',
              'weighted residual dashboard']},
 {'checks': ['finite-difference Jacobians match analytic approximations',
             'accepted steps decrease the objective',
             'robust weights shrink for large residuals',
             'sparse block elimination matches the dense solution on a small case'],
  'concepts': ['iterative methods replace nonlinear geometry by local linear problems',
               'damping interpolates between cautious descent and fast Gauss-Newton updates',
               'sparse structure makes bundle adjustment tractable',
               'robust costs reduce the influence of outliers'],
  'focus': 'Newton, Gauss-Newton, Levenberg-Marquardt, sparse systems, robust costs, rotations, '
           'homogeneous vectors, and constrained parameterizations.',
  'folder': 'appendix-06-iterative-estimation-methods',
  'kind': 'appendix',
  'label': 'Appendix 06',
  'mode': 'iterative',
  'notebook': 'a06-iterative-estimation-methods.ipynb',
  'number': 106,
  'part': 'part-05-appendices',
  'pdf': '615-645',
  'printed': '597-627',
  'title': 'Iterative Estimation Methods',
  'topic': 'appendix-06',
  'visuals': ['optimizer path comparison',
              'damping schedule panel',
              'Schur complement sparsity graph',
              'robust loss curve']},
 {'checks': ['fixed points satisfy H x proportional to x',
             'axis points remain on the fixed line',
             'eigenvalue multiplicities match the class label',
             'cross-ratio invariants remain stable under the homology'],
  'concepts': ['special homographies are recognized by fixed points, fixed lines, and eigenvalue '
               'multiplicities',
               'homologies move points along lines through a vertex while fixing an axis',
               'conjugate rotations preserve a hidden metric angle',
               'classification helps decide how many correspondences are needed'],
  'focus': 'Conjugate rotations, homologies, elations, affinities, and special eigenstructure of '
           'plane projective transformations.',
  'folder': 'appendix-07-some-special-plane-projective-transformations',
  'kind': 'appendix',
  'label': 'Appendix 07',
  'mode': 'special-homographies',
  'notebook': 'a07-some-special-plane-projective-transformations.ipynb',
  'number': 107,
  'part': 'part-05-appendices',
  'pdf': '646-651',
  'printed': '628-633',
  'title': 'Some Special Plane Projective Transformations',
  'topic': 'appendix-07',
  'visuals': ['fixed point and line flow',
              'homology axis-vertex diagram',
              'conjugate rotation eigenvalue panel',
              'homography classification table']}]

SMOKE_NOTEBOOKS = {'01-introduction-a-tour-of-multiple-view-geometry.ipynb',
 '02-projective-geometry-and-transformations-of-2d.ipynb',
 '06-camera-models.ipynb',
 '09-epipolar-geometry-and-the-fundamental-matrix.ipynb',
 '11-computation-of-the-fundamental-matrix-f.ipynb',
 '12-structure-computation.ipynb',
 '15-the-trifocal-tensor.ipynb',
 '18-n-view-computational-methods.ipynb',
 'a06-iterative-estimation-methods.ipynb'}


def canonical_entries() -> list[dict]:
    return list(ENTRIES)


def parts() -> list[dict]:
    return list(PARTS)


def entry_folder(entry: dict) -> str:
    if entry["part"] is None:
        return entry["folder"]
    return f'{entry["part"]}/{entry["folder"]}'
