from __future__ import annotations

from pathlib import Path

BOOK_ROOT = Path(__file__).resolve().parents[1]

PARTS = [
    {
        "id": "part-01-projective-geometry",
        "number": 1,
        "title": "Projective Geometry",
        "focus": "Projective planes, homogeneous coordinates, cross-ratios, determinants, and bracket algebra.",
    },
    {
        "id": "part-02-working-and-playing-with-geometry",
        "number": 2,
        "title": "Working and Playing with Geometry",
        "focus": "Quadrilateral sets, conics, projective d-space, tensor diagrams, configurations, and theorem proving.",
    },
    {
        "id": "part-03-measurements",
        "number": 3,
        "title": "Measurements",
        "focus": "Complex projective line, Euclidean structures, Cayley-Klein geometry, hyperbolic models, and extensions.",
    },
]

CHAPTERS = [
    {
        "number": 1,
        "part": None,
        "folder": "chapter-01-pappos-theorem-nine-proofs-and-three-variations",
        "artifact": "chapter-01-pappos-theorem-nine-proofs-and-three-variations",
        "title": "Pappos's Theorem: Nine Proofs and Three Variations",
        "notebook": "01-pappos-theorem-nine-proofs-and-three-variations.ipynb",
        "sections": "1.1-1.7",
        "printed_span": "3-32",
        "pdf_span": "25-54",
        "focus": "Pappos configurations, projective completion, area and determinant proofs, conic variants, Miquel/cross-ratio lab.",
        "question": "How can one incidence theorem reveal projective completion, algebraic proof, and circle geometry at once?",
        "visual_mode": "incidence",
        "visuals": [
            "Pappos incidence configuration with movable roles",
            "parallel limit and line at infinity",
            "area-cancellation proof state",
            "Miquel and cross-ratio circle lab",
            "determinant proof sanity check",
        ],
    },
    {
        "number": 2,
        "part": "part-01-projective-geometry",
        "folder": "part-01-projective-geometry/chapter-02-projective-planes",
        "artifact": "chapter-02-projective-planes",
        "title": "Projective Planes",
        "notebook": "02-projective-planes.ipynb",
        "sections": "2.1-2.3",
        "printed_span": "35-46",
        "pdf_span": "57-68",
        "focus": "Perspective drawings, incidence axioms, duality, and the smallest finite projective plane.",
        "question": "What changes when points and lines are treated as dual citizens of the same incidence world?",
        "visual_mode": "incidence",
        "visuals": [
            "perspective drawing as incidence data",
            "projective plane axiom dependency map",
            "point-line duality diagram",
            "Fano plane incidence table",
            "finite-plane sanity checks",
        ],
    },
    {
        "number": 3,
        "part": "part-01-projective-geometry",
        "folder": "part-01-projective-geometry/chapter-03-homogeneous-coordinates",
        "artifact": "chapter-03-homogeneous-coordinates",
        "title": "Homogeneous Coordinates",
        "notebook": "03-homogeneous-coordinates.ipynb",
        "sections": "3.1-3.7",
        "printed_span": "47-66",
        "pdf_span": "69-88",
        "focus": "RP2 from R3, elements at infinity, joins/meets, duality, transformations, and finite projective planes.",
        "question": "How do three coordinates remove the exceptional cases from two-dimensional geometry?",
        "visual_mode": "space",
        "visuals": [
            "affine plane embedded in R3",
            "points at infinity as limiting rays",
            "join and meet via cross product",
            "projective transform grid",
            "finite-plane coordinate experiment",
        ],
    },
    {
        "number": 4,
        "part": "part-01-projective-geometry",
        "folder": "part-01-projective-geometry/chapter-04-lines-and-cross-ratios",
        "artifact": "chapter-04-lines-and-cross-ratios",
        "title": "Lines and Cross-Ratios",
        "notebook": "04-lines-and-cross-ratios.ipynb",
        "sections": "4.1-4.4",
        "printed_span": "67-78",
        "pdf_span": "89-100",
        "focus": "Coordinates on a projective line, real projective line charts, cross-ratios, and harmonic quadruples.",
        "question": "Which numerical quantity survives when a line is reparametrized projectively?",
        "visual_mode": "line",
        "visuals": [
            "projective line chart transitions",
            "cross-ratio under Mobius maps",
            "harmonic point construction",
            "infinity crossing on RP1",
            "numeric invariance table",
        ],
    },
    {
        "number": 5,
        "part": "part-01-projective-geometry",
        "folder": "part-01-projective-geometry/chapter-05-calculating-with-points-on-lines",
        "artifact": "chapter-05-calculating-with-points-on-lines",
        "title": "Calculating with Points on Lines",
        "notebook": "05-calculating-with-points-on-lines.ipynb",
        "sections": "5.1-5.7",
        "printed_span": "79-92",
        "pdf_span": "101-114",
        "focus": "Harmonic points, projective scales, reconstructing real numbers, von Staudt constructions, and Pappos arithmetic.",
        "question": "How can incidence constructions on a line begin to act like arithmetic?",
        "visual_mode": "line",
        "visuals": [
            "harmonic point as cross-ratio minus one",
            "projective scale with three anchors",
            "addition and multiplication construction graph",
            "field-law dependency diagram",
            "Pappos arithmetic check",
        ],
    },
    {
        "number": 6,
        "part": "part-01-projective-geometry",
        "folder": "part-01-projective-geometry/chapter-06-determinants",
        "artifact": "chapter-06-determinants",
        "title": "Determinants",
        "notebook": "06-determinants.ipynb",
        "sections": "6.1-6.5",
        "printed_span": "93-108",
        "pdf_span": "115-130",
        "focus": "Determinantal viewpoint, bracket formulas, Plucker's mu, invariant properties, and Grassmann-Plucker relations.",
        "question": "Why do determinants know collinearity, orientation, and projective invariance at the same time?",
        "visual_mode": "bracket",
        "visuals": [
            "oriented bracket as signed area",
            "Plucker mu transformation panel",
            "collinearity determinant test",
            "Grassmann-Plucker relation check",
            "invariant scaling experiment",
        ],
    },
    {
        "number": 7,
        "part": "part-01-projective-geometry",
        "folder": "part-01-projective-geometry/chapter-07-more-on-bracket-algebra",
        "artifact": "chapter-07-more-on-bracket-algebra",
        "title": "More on Bracket Algebra",
        "notebook": "07-more-on-bracket-algebra.ipynb",
        "sections": "7.1-7.5",
        "printed_span": "109-126",
        "pdf_span": "131-148",
        "focus": "Moving between points and determinants, a glimpse of invariant theory, invariant functions, and the bracket algebra.",
        "question": "How can algebraic expressions become a language for projective configurations?",
        "visual_mode": "bracket",
        "visuals": [
            "points-to-determinants pipeline",
            "basis reconstruction diagram",
            "invariant monomial weight chart",
            "bracket polynomial cancellation graph",
            "symbolic sanity checks",
        ],
    },
    {
        "number": 8,
        "part": "part-02-working-and-playing-with-geometry",
        "folder": "part-02-working-and-playing-with-geometry/chapter-08-quadrilateral-sets-and-liftings",
        "artifact": "chapter-08-quadrilateral-sets-and-liftings",
        "title": "Quadrilateral Sets and Liftings",
        "notebook": "08-quadrilateral-sets-and-liftings.ipynb",
        "sections": "8.1-8.6",
        "printed_span": "129-144",
        "pdf_span": "151-166",
        "focus": "Points on a line, quadrilateral sets, symmetry, von Staudt links, slope conditions, and involutions.",
        "question": "What hidden symmetries appear when four-point line data is lifted into the plane?",
        "visual_mode": "incidence",
        "visuals": [
            "quadrilateral set on a projective line",
            "lifting diagram",
            "symmetry orbit panel",
            "slope condition experiment",
            "involution fixed-pair lab",
        ],
    },
    {
        "number": 9,
        "part": "part-02-working-and-playing-with-geometry",
        "folder": "part-02-working-and-playing-with-geometry/chapter-09-conics-and-their-duals",
        "artifact": "chapter-09-conics-and-their-duals",
        "title": "Conics and Their Duals",
        "notebook": "09-conics-and-their-duals.ipynb",
        "sections": "9.1-9.6",
        "printed_span": "145-166",
        "pdf_span": "167-188",
        "focus": "Conic equations, polars, tangents, dual quadratic forms, transformations, degenerate conics, and primal-dual pairs.",
        "question": "How does a symmetric matrix turn points, lines, tangents, and duality into one computational system?",
        "visual_mode": "conic",
        "visuals": [
            "matrix conic contour",
            "polar and tangent construction",
            "dual conic envelope",
            "projective transform of a conic",
            "degenerate conic classification",
        ],
    },
    {
        "number": 10,
        "part": "part-02-working-and-playing-with-geometry",
        "folder": "part-02-working-and-playing-with-geometry/chapter-10-conics-and-perspectivity",
        "artifact": "chapter-10-conics-and-perspectivity",
        "title": "Conics and Perspectivity",
        "notebook": "10-conics-and-perspectivity.ipynb",
        "sections": "10.1-10.7",
        "printed_span": "167-188",
        "pdf_span": "189-210",
        "focus": "Conics through five points, conic cross-ratios, perspective generation, transformations, transfer principles, Pascal and Brianchon.",
        "question": "Why does a conic behave like a projective line seen through a moving perspective?",
        "visual_mode": "conic",
        "visuals": [
            "five-point conic fitting",
            "cross-ratio transported along a conic",
            "perspective generation sweep",
            "Pascal and Brianchon dual diagram",
            "Hesse transfer experiment",
        ],
    },
    {
        "number": 11,
        "part": "part-02-working-and-playing-with-geometry",
        "folder": "part-02-working-and-playing-with-geometry/chapter-11-calculating-with-conics",
        "artifact": "chapter-11-calculating-with-conics",
        "title": "Calculating with Conics",
        "notebook": "11-calculating-with-conics.ipynb",
        "sections": "11.1-11.6",
        "printed_span": "189-208",
        "pdf_span": "211-230",
        "focus": "Splitting degenerate conics, branching operations, conic-line intersections, conic-conic intersections, complex numbers, and tangent constraints.",
        "question": "Where do case distinctions and complex numbers enter when conics become computational objects?",
        "visual_mode": "conic",
        "visuals": [
            "degenerate conic splitting",
            "if-operation decision tree",
            "line-conic intersection roots",
            "two-conic intersection panel",
            "complex root interpretation",
        ],
    },
    {
        "number": 12,
        "part": "part-02-working-and-playing-with-geometry",
        "folder": "part-02-working-and-playing-with-geometry/chapter-12-projective-d-space",
        "artifact": "chapter-12-projective-d-space",
        "title": "Projective d-space",
        "notebook": "12-projective-d-space.ipynb",
        "sections": "12.1-12.6",
        "printed_span": "209-226",
        "pdf_span": "231-248",
        "focus": "Elements at infinity, homogeneous transformations, points and planes in 3-space, lines in 3-space, and universal join/meet systems.",
        "question": "How do joins and meets generalize once the objects are points, planes, and lines in higher dimension?",
        "visual_mode": "space",
        "visuals": [
            "elements at infinity in 3-space",
            "point-plane incidence",
            "line in RP3 as two-plane data",
            "universal join-meet lattice",
            "projection sanity check",
        ],
    },
    {
        "number": 13,
        "part": "part-02-working-and-playing-with-geometry",
        "folder": "part-02-working-and-playing-with-geometry/chapter-13-diagram-techniques",
        "artifact": "chapter-13-diagram-techniques",
        "title": "Diagram Techniques",
        "notebook": "13-diagram-techniques.ipynb",
        "sections": "13.1-13.9",
        "printed_span": "227-246",
        "pdf_span": "249-268",
        "focus": "From points, lines, and matrices to tensors, tensor diagrams, transformations, delta tensors, epsilon tensors, and diagrammatic invariants.",
        "question": "How can tensor notation become a manipulable picture of projective algebra?",
        "visual_mode": "tensor",
        "visuals": [
            "matrix-to-tensor diagram legend",
            "delta tensor wire identity",
            "epsilon tensor orientation node",
            "epsilon-delta rewrite move",
            "configuration invariant diagram",
        ],
    },
    {
        "number": 14,
        "part": "part-02-working-and-playing-with-geometry",
        "folder": "part-02-working-and-playing-with-geometry/chapter-14-working-with-diagrams",
        "artifact": "chapter-14-working-with-diagrams",
        "title": "Working with Diagrams",
        "notebook": "14-working-with-diagrams.ipynb",
        "sections": "14.1-14.8",
        "printed_span": "247-268",
        "pdf_span": "269-290",
        "focus": "Trace conditions, Pascal's theorem, closed epsilon cycles, conics, RP3 diagrams, rank-4 epsilon-delta rules, and Plucker coordinates.",
        "question": "What proof moves become visible when a formula is treated as a diagram to simplify?",
        "visual_mode": "tensor",
        "visuals": [
            "trace condition loop",
            "Pascal diagram rewrite",
            "closed epsilon cycle",
            "rank-four epsilon-delta move",
            "tensor versus Plucker comparison",
        ],
    },
    {
        "number": 15,
        "part": "part-02-working-and-playing-with-geometry",
        "folder": "part-02-working-and-playing-with-geometry/chapter-15-configurations-theorems-and-bracket-expressions",
        "artifact": "chapter-15-configurations-theorems-and-bracket-expressions",
        "title": "Configurations, Theorems, and Bracket Expressions",
        "notebook": "15-configurations-theorems-and-bracket-expressions.ipynb",
        "sections": "15.1-15.6",
        "printed_span": "269-294",
        "pdf_span": "291-316",
        "focus": "Desargues theorem, binomial proofs, chains and cycles of cross-ratios, Ceva and Menelaus, and glued configurations.",
        "question": "How do incidence theorems become bracket expressions that can be checked and transformed?",
        "visual_mode": "bracket",
        "visuals": [
            "Desargues configuration",
            "binomial proof cancellation",
            "cross-ratio cycle chain",
            "Ceva and Menelaus paired diagram",
            "glued configuration dependency graph",
        ],
    },
    {
        "number": 16,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-16-complex-numbers-a-primer",
        "artifact": "chapter-16-complex-numbers-a-primer",
        "title": "Complex Numbers: A Primer",
        "notebook": "16-complex-numbers-a-primer.ipynb",
        "sections": "16.1-16.5",
        "printed_span": "297-310",
        "pdf_span": "319-332",
        "focus": "Historical motivation, the fundamental theorem, geometry of complex numbers, Euler formula, and complex conjugation.",
        "question": "Why are rotations, roots, and conjugation geometric operations rather than only algebraic syntax?",
        "visual_mode": "complex",
        "visuals": [
            "complex plane as geometry",
            "roots as regular polygon",
            "Euler rotation sweep",
            "conjugation as reflection",
            "polynomial root check",
        ],
    },
    {
        "number": 17,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-17-the-complex-projective-line",
        "artifact": "chapter-17-the-complex-projective-line",
        "title": "The Complex Projective Line",
        "notebook": "17-the-complex-projective-line.ipynb",
        "sections": "17.1-17.7",
        "printed_span": "311-328",
        "pdf_span": "333-350",
        "focus": "CP1, geometric property tests, projective transformations, inversions, Mobius reflections, Grassmann-Plucker relations, angles, and stereographic projection.",
        "question": "How does adding the point at infinity turn circles, lines, inversions, and sphere geometry into one picture?",
        "visual_mode": "complex",
        "visuals": [
            "CP1 chart with infinity",
            "Mobius image of a grid",
            "circle inversion and reflection",
            "intersection-angle preservation",
            "stereographic projection sphere",
        ],
    },
    {
        "number": 18,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-18-euclidean-geometry",
        "artifact": "chapter-18-euclidean-geometry",
        "title": "Euclidean Geometry",
        "notebook": "18-euclidean-geometry.ipynb",
        "sections": "18.1-18.8",
        "printed_span": "329-348",
        "pdf_span": "351-370",
        "focus": "Circular points, cocircularity, robust cross-ratios, Euclidean transformations, theorem translation, angles, Laguerre formula, and distances.",
        "question": "How do the two circular points let projective geometry recover Euclidean angle and distance?",
        "visual_mode": "measurement",
        "visuals": [
            "circular points as conic anchors",
            "cocircularity cross-ratio test",
            "Euclidean transformation family",
            "Laguerre angle formula experiment",
            "distance from projective data",
        ],
    },
    {
        "number": 19,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-19-euclidean-structures-from-a-projective-perspective",
        "artifact": "chapter-19-euclidean-structures-from-a-projective-perspective",
        "title": "Euclidean Structures from a Projective Perspective",
        "notebook": "19-euclidean-structures-from-a-projective-perspective.ipynb",
        "sections": "19.1-19.7",
        "printed_span": "349-374",
        "pdf_span": "371-396",
        "focus": "Mirror images, angle bisectors, circle centers, conic foci, conic construction from foci, triangle theorems, and hybrid thinking.",
        "question": "What Euclidean constructions become clearer when the invisible circular points are included?",
        "visual_mode": "measurement",
        "visuals": [
            "mirror image as projective reflection",
            "angle bisector via circular points",
            "circle center construction",
            "conic foci from complex tangents",
            "triangle theorem translation",
        ],
    },
    {
        "number": 20,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-20-cayley-klein-geometries",
        "artifact": "chapter-20-cayley-klein-geometries",
        "title": "Cayley-Klein Geometries",
        "notebook": "20-cayley-klein-geometries.ipynb",
        "sections": "20.1-20.7",
        "printed_span": "375-398",
        "pdf_span": "397-420",
        "focus": "I and J revisited, measurements from a conic, nondegenerate and degenerate line measurements, planar Cayley-Klein geometry, and geometry classification.",
        "question": "How can one conic decide whether a geometry measures like Euclidean, hyperbolic, elliptic, or degenerate space?",
        "visual_mode": "measurement",
        "visuals": [
            "absolute conic choices",
            "cross-ratio line measurement",
            "degenerate measurement limit",
            "planar Cayley-Klein model",
            "geometry census chart",
        ],
    },
    {
        "number": 21,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-21-measurements-and-transformations",
        "artifact": "chapter-21-measurements-and-transformations",
        "title": "Measurements and Transformations",
        "notebook": "21-measurements-and-transformations.ipynb",
        "sections": "21.1-21.6",
        "printed_span": "399-422",
        "pdf_span": "421-444",
        "focus": "Measurements versus oriented measurements, transformations, eliminating reference points, comparing measurements, reflections, pole/polar pairs, and rotations.",
        "question": "Which transformations preserve a measurement, and how do reflections generate them?",
        "visual_mode": "measurement",
        "visuals": [
            "oriented measurement comparison",
            "absolute-preserving transform",
            "reference-point elimination",
            "pole-polar reflection",
            "two reflections to a rotation",
        ],
    },
    {
        "number": 22,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-22-cayley-klein-geometries-at-work",
        "artifact": "chapter-22-cayley-klein-geometries-at-work",
        "title": "Cayley-Klein Geometries at Work",
        "notebook": "22-cayley-klein-geometries-at-work.ipynb",
        "sections": "22.1-22.5",
        "printed_span": "423-442",
        "pdf_span": "445-464",
        "focus": "Orthogonality, constructive versus implicit representations, shared and differing properties, midpoints, angle bisectors, and trigonometry.",
        "question": "Which familiar constructions survive when the metric is defined by an arbitrary absolute conic?",
        "visual_mode": "measurement",
        "visuals": [
            "orthogonality from pole-polar relation",
            "constructive versus implicit model",
            "midpoint comparison",
            "angle bisector families",
            "Cayley-Klein trigonometry lab",
        ],
    },
    {
        "number": 23,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-23-circles-and-cycles",
        "artifact": "chapter-23-circles-and-cycles",
        "title": "Circles and Cycles",
        "notebook": "23-circles-and-cycles.ipynb",
        "sections": "23.1-23.5",
        "printed_span": "443-464",
        "pdf_span": "465-486",
        "focus": "Circles via distances, relation to the fundamental conic, centers at infinity, organizing principles, and cycles in Galilean geometry.",
        "question": "When distance comes from an absolute conic, what should count as a circle?",
        "visual_mode": "measurement",
        "visuals": [
            "distance circle family",
            "fundamental conic contact",
            "center at infinity limit",
            "cycle classification panel",
            "Galilean cycle experiment",
        ],
    },
    {
        "number": 24,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-24-non-euclidean-geometry-a-historical-interlude",
        "artifact": "chapter-24-non-euclidean-geometry-a-historical-interlude",
        "title": "Non-Euclidean Geometry: A Historical Interlude",
        "notebook": "24-non-euclidean-geometry-a-historical-interlude.ipynb",
        "sections": "24.1-24.6",
        "printed_span": "465-482",
        "pdf_span": "487-504",
        "focus": "Inner geometry, Euclid's postulates, Gauss, Bolyai, Lobachevsky, Beltrami, Klein, the Beltrami-Klein model, and Poincare.",
        "question": "How did the search around the parallel postulate become a model-building problem?",
        "visual_mode": "hyperbolic",
        "visuals": [
            "postulate dependency map",
            "parallel behavior comparison",
            "Beltrami-Klein disk sketch",
            "Poincare conformal contrast",
            "historical model timeline",
        ],
    },
    {
        "number": 25,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-25-hyperbolic-geometry",
        "artifact": "chapter-25-hyperbolic-geometry",
        "title": "Hyperbolic Geometry",
        "notebook": "25-hyperbolic-geometry.ipynb",
        "sections": "25.1-25.6",
        "printed_span": "483-504",
        "pdf_span": "505-526",
        "focus": "Hyperbolic staging ground, transformations, angles and boundaries, Poincare disk, CP1 transformations, and distance/angle formulas.",
        "question": "How do projective and complex tools give two coordinated models of the same hyperbolic plane?",
        "visual_mode": "hyperbolic",
        "visuals": [
            "Klein and Poincare model comparison",
            "hyperbolic transformation of boundary points",
            "geodesic arcs in the disk",
            "angle preservation panel",
            "distance cross-ratio heatmap",
        ],
    },
    {
        "number": 26,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-26-selected-topics-in-hyperbolic-geometry",
        "artifact": "chapter-26-selected-topics-in-hyperbolic-geometry",
        "title": "Selected Topics in Hyperbolic Geometry",
        "notebook": "26-selected-topics-in-hyperbolic-geometry.ipynb",
        "sections": "26.1-26.5",
        "printed_span": "505-524",
        "pdf_span": "527-546",
        "focus": "Circles and cycles in the Poincare disk, area and angle defect, Thales and Pythagoras, regular n-gons, and symmetry groups.",
        "question": "Which Euclidean-looking pictures change their meaning inside the hyperbolic disk?",
        "visual_mode": "hyperbolic",
        "visuals": [
            "hyperbolic circles, horocycles, and hypercycles",
            "area versus angle defect",
            "hyperbolic Thales and Pythagoras lab",
            "regular polygon construction",
            "symmetry group orbit",
        ],
    },
    {
        "number": 27,
        "part": "part-03-measurements",
        "folder": "part-03-measurements/chapter-27-what-we-did-not-touch",
        "artifact": "chapter-27-what-we-did-not-touch",
        "title": "What We Did Not Touch",
        "notebook": "27-what-we-did-not-touch.ipynb",
        "sections": "27.1-27.4",
        "printed_span": "525-556",
        "pdf_span": "547-578",
        "focus": "Algebraic projective geometry, discrete mathematics, quantum theory, and dynamic projective geometry.",
        "question": "Where does projective geometry continue after the main tour ends?",
        "visual_mode": "complex",
        "visuals": [
            "algebraic geometry branch map",
            "discrete projective arrangement",
            "quantum-state projective view",
            "dynamic geometry branch detour",
            "course knowledge graph",
        ],
    },
]

SMOKE_CHAPTERS = [1, 2, 9, 13, 17, 20, 25, 27]


def chapters_for_part(part_id: str | None) -> list[dict[str, object]]:
    return [chapter for chapter in CHAPTERS if chapter["part"] == part_id]


def chapter_by_number(number: int) -> dict[str, object]:
    for chapter in CHAPTERS:
        if chapter["number"] == number:
            return chapter
    raise KeyError(number)


def canonical_notebook_path(chapter: dict[str, object]) -> Path:
    return BOOK_ROOT / str(chapter["folder"]) / str(chapter["notebook"])


def artifact_root(chapter: dict[str, object]) -> Path:
    return BOOK_ROOT / "artifacts" / str(chapter["artifact"])

