"""Build course and chapter index notebooks for FCG."""

from __future__ import annotations

import json
from pathlib import Path

import fcg_inventory as inventory

BOOK_ROOT = inventory.BOOK_ROOT


def markdown_notebook(markdown: str) -> dict[str, object]:
    return {
        "cells": [{"cell_type": "markdown", "id": "course-index", "metadata": {}, "source": markdown.splitlines(keepends=True)}],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def write_notebook(path: Path, markdown: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(markdown_notebook(markdown), indent=2), encoding="utf-8")


def build_book_index() -> None:
    lines = [
        "# Fundamentals of Computer Graphics - Visualization-First Notebook Course",
        "",
        "This is a standalone notebook course built from the chapter structure of *Fundamentals of Computer Graphics*, Fifth Edition. The notebooks use original prose, generated diagrams, executable checks, and book-local artifacts.",
        "",
        "## How To Use This Course",
        "",
        "Start with any chapter. Each folder contains a local `00-index.ipynb` and one canonical teaching notebook. Generated artifacts live under `artifacts/chapter-XX/`.",
        "",
        "## Course Map",
        "",
    ]
    for entry in inventory.ENTRIES:
        folder = entry["folder"]
        notebook = entry["notebook"]
        lines.append(
            f"- [Chapter {entry['chapter']:02d}: {entry['title']}]({folder}/00-index.ipynb) - "
            f"[canonical]({folder}/{notebook}); printed pp. {entry['printed']}; PDF pp. {entry['pdf']}; {entry['focus']}"
        )
    write_notebook(BOOK_ROOT / "00-book-index.ipynb", "\n".join(lines) + "\n")


def build_chapter_indexes() -> None:
    for entry in inventory.ENTRIES:
        chapter = int(entry["chapter"])
        lines = [
            f"# Chapter {chapter:02d}: {entry['title']}",
            "",
            f"- Canonical notebook: [{entry['notebook']}]({entry['notebook']})",
            f"- Printed pages: {entry['printed']}",
            f"- Physical PDF pages: {entry['pdf']}",
            f"- Visual spine: {entry['visual_spine']}",
            "",
            "Artifacts for this chapter are stored under "
            f"`../artifacts/chapter-{chapter:02d}/` and are generated by the canonical notebook.",
        ]
        write_notebook(BOOK_ROOT / str(entry["folder"]) / "00-index.ipynb", "\n".join(lines) + "\n")


def main() -> None:
    build_book_index()
    build_chapter_indexes()
    print(f"Built index notebooks for {len(inventory.ENTRIES)} chapters")


if __name__ == "__main__":
    main()
