"""Course inventory for the Fundamentals of Computer Graphics notebooks."""

from __future__ import annotations

from pathlib import Path

BOOK_ROOT = Path(__file__).resolve().parents[1]

ENTRIES = [
    {"chapter": 1, "title": "Introduction", "folder": "chapter-01-introduction", "notebook": "01-introduction.ipynb", "printed": "1-12", "pdf": "18-29", "focus": "Graphics areas, applications, APIs, pipeline thinking, numerical issues, efficiency, and visual debugging.", "visual_spine": "graphics map, pipeline, numeric robustness, debug images"},
    {"chapter": 2, "title": "Miscellaneous Math", "folder": "chapter-02-miscellaneous-math", "notebook": "02-miscellaneous-math.ipynb", "printed": "13-62", "pdf": "30-79", "focus": "Sets, mappings, quadratics, vectors, curves, surfaces, interpolation, triangles, probability, and Monte Carlo integration.", "visual_spine": "vectors, barycentric coordinates, quadratics, probability, Monte Carlo"},
    {"chapter": 3, "title": "Raster Images", "folder": "chapter-03-raster-images", "notebook": "03-raster-images.ipynb", "printed": "63-78", "pdf": "80-95", "focus": "Raster devices, pixels, RGB color, gamma, quantization, and alpha compositing.", "visual_spine": "pixels, RGB, gamma, quantization, alpha compositing"},
    {"chapter": 4, "title": "Ray Tracing", "folder": "chapter-04-ray-tracing", "notebook": "04-ray-tracing.ipynb", "printed": "79-96", "pdf": "96-113", "focus": "Ray generation, perspective, ray-object intersections, closest hits, shading inputs, shadows, and reflections.", "visual_spine": "camera rays, intersections, closest hit, shadows, reflection"},
    {"chapter": 5, "title": "Surface Shading", "folder": "chapter-05-surface-shading", "notebook": "05-surface-shading.ipynb", "printed": "97-106", "pdf": "114-123", "focus": "Point lights, Lambertian diffuse reflection, Blinn-Phong highlights, attenuation, and ambient terms.", "visual_spine": "Lambert, point lights, Blinn-Phong, ambient fill"},
    {"chapter": 6, "title": "Linear Algebra", "folder": "chapter-06-linear-algebra", "notebook": "06-linear-algebra.ipynb", "printed": "107-126", "pdf": "124-143", "focus": "Determinants, matrices, inverses, linear systems, eigenvectors, and matrix diagonalization.", "visual_spine": "determinants, matrix maps, inverse, eigen/SVD geometry"},
    {"chapter": 7, "title": "Transformation Matrices", "folder": "chapter-07-transformation-matrices", "notebook": "07-transformation-matrices.ipynb", "printed": "127-156", "pdf": "144-173", "focus": "2D and 3D transformations, homogeneous coordinates, inverse transforms, and coordinate frames.", "visual_spine": "2D/3D transforms, homogeneous coordinates, normal transforms"},
    {"chapter": 8, "title": "Viewing", "folder": "chapter-08-viewing", "notebook": "08-viewing.ipynb", "printed": "157-176", "pdf": "174-193", "focus": "Viewing transforms, projective transforms, perspective projection, frusta, and field of view.", "visual_spine": "camera basis, projection, frustum, viewport, field of view"},
    {"chapter": 9, "title": "The Graphics Pipeline", "folder": "chapter-09-graphics-pipeline", "notebook": "09-graphics-pipeline.ipynb", "printed": "177-204", "pdf": "194-221", "focus": "Rasterization, interpolation, depth buffering, antialiasing, clipping, and culling.", "visual_spine": "rasterization, interpolation, z-buffer, antialiasing, culling"},
    {"chapter": 10, "title": "Signal Processing", "folder": "chapter-10-signal-processing", "notebook": "10-signal-processing.ipynb", "printed": "205-254", "pdf": "222-271", "focus": "Sampling, convolution, reconstruction filters, image processing, frequency response, and aliasing.", "visual_spine": "sampling, convolution, filters, Fourier spectra, aliasing"},
    {"chapter": 11, "title": "Texture Mapping", "folder": "chapter-11-texture-mapping", "notebook": "11-texture-mapping.ipynb", "printed": "255-290", "pdf": "272-307", "focus": "Texture coordinates, filtering, mipmaps, bump and displacement mapping, shadows, environment maps, and procedural textures.", "visual_spine": "UVs, perspective-correct lookup, mipmaps, bump/displacement, noise"},
    {"chapter": 12, "title": "Data Structures for Graphics", "folder": "chapter-12-data-structures-for-graphics", "notebook": "12-data-structures-for-graphics.ipynb", "printed": "291-334", "pdf": "308-351", "focus": "Meshes, scene graphs, spatial structures, BSP trees, and tiled array layouts.", "visual_spine": "mesh topology, scene graphs, BVH/kd/BSP, tiled memory"},
    {"chapter": 13, "title": "Sampling", "folder": "chapter-13-sampling", "notebook": "13-sampling.ipynb", "printed": "335-356", "pdf": "352-373", "focus": "Probability measures, inverse CDFs, rejection, stratification, lines, disks, spheres, and hemisphere sampling.", "visual_spine": "measures, inverse CDF, rejection, stratification, hemisphere sampling"},
    {"chapter": 14, "title": "Physics-Based Rendering", "folder": "chapter-14-physics-based-rendering", "notebook": "14-physics-based-rendering.ipynb", "printed": "357-382", "pdf": "374-399", "focus": "Photons, radiometry, Fresnel, refraction, attenuation, BRDFs, the rendering equation, and Monte Carlo path tracing.", "visual_spine": "radiometry, Fresnel, refraction, BRDFs, rendering equation"},
    {"chapter": 15, "title": "Curves", "folder": "chapter-15-curves", "notebook": "15-curves.ipynb", "printed": "383-428", "pdf": "400-445", "focus": "Parametric curves, continuity, polynomial pieces, cubics, Bezier curves, B-splines, and NURBS.", "visual_spine": "parametrization, continuity, Bezier, B-splines, NURBS"},
    {"chapter": 16, "title": "Computer Animation", "folder": "chapter-16-computer-animation", "notebook": "16-computer-animation.ipynb", "printed": "429-460", "pdf": "446-477", "focus": "Principles of animation, keyframing, deformation, character animation, physics, procedural techniques, and groups.", "visual_spine": "keyframes, splines, quaternions, rigs, skinning, particles"},
    {"chapter": 17, "title": "Using Graphics Hardware", "folder": "chapter-17-using-graphics-hardware", "notebook": "17-using-graphics-hardware.ipynb", "printed": "461-502", "pdf": "478-519", "focus": "GPU pipeline, buffers, state, shaders, vertex arrays, transformations, attributes, textures, meshes, and instancing.", "visual_spine": "mini GPU pipeline, buffers, shaders, depth, textures"},
    {"chapter": 18, "title": "Color", "folder": "chapter-18-color", "notebook": "18-color.ipynb", "printed": "503-524", "pdf": "520-541", "focus": "Colorimetry, color spaces, chromatic adaptation, color appearance, and perceptual distances.", "visual_spine": "spectra, XYZ/RGB/LAB, gamut, gamma, chromatic adaptation"},
    {"chapter": 19, "title": "Visual Perception", "folder": "chapter-19-visual-perception", "notebook": "19-visual-perception.ipynb", "printed": "525-568", "pdf": "542-585", "focus": "Sensitivity, spatial vision, depth cues, motion, object perception, and picture perception.", "visual_spine": "contrast, illusions, depth cues, motion, picture perception"},
    {"chapter": 20, "title": "Tone Reproduction", "folder": "chapter-20-tone-reproduction", "notebook": "20-tone-reproduction.ipynb", "printed": "569-594", "pdf": "586-611", "focus": "Dynamic range, tone curves, image formation, frequency, gradient, spatial, sigmoid, and night tone mapping operators.", "visual_spine": "HDR/LDR, tone curves, local operators, color preservation"},
    {"chapter": 21, "title": "Implicit Modeling", "folder": "chapter-21-implicit-modeling", "notebook": "21-implicit-modeling.ipynb", "printed": "595-622", "pdf": "612-639", "focus": "Implicit fields, skeletal primitives, blending, rendering, partitioning, CSG, warping, and BlobTrees.", "visual_spine": "scalar fields, blends, CSG, warps, marching cubes"},
    {"chapter": 22, "title": "Computer Graphics in Games", "folder": "chapter-22-computer-graphics-in-games", "notebook": "22-computer-graphics-in-games.ipynb", "printed": "623-644", "pdf": "640-661", "focus": "Platform constraints, limited resources, optimization, game types, and production workflows.", "visual_spine": "frame budgets, LOD, asset pipeline, normal maps, optimization"},
    {"chapter": 23, "title": "Visualization", "folder": "chapter-23-visualization", "notebook": "23-visualization.ipynb", "printed": "645-680", "pdf": "662-697", "focus": "Data and task abstraction, visual encoding, interaction, composition, reduction, and visualization examples.", "visual_spine": "data/task abstraction, encodings, interaction, reduction, validation"},
]


def chapter_topic(chapter: int) -> str:
    return f"chapter-{chapter:02d}"


def canonical_path(entry: dict[str, object]) -> Path:
    return BOOK_ROOT / str(entry["folder"]) / str(entry["notebook"])
