"""Course inventory for Undergraduate Algebraic Geometry."""

from __future__ import annotations

from pathlib import Path

PDF_SOURCE = 'Undergraduate Algebraic Geometry.pdf'
BODY_PAGE_RULE = 'For main-text printed pages, physical PDF page = printed page - 2.'

PARTS = [{'description': 'Motivation and orientation before the main course.',
  'folder': 'prologue',
  'label': 'Prologue',
  'title': 'Prologue'},
 {'description': 'Conics and cubics as visual laboratories for projective geometry.',
  'folder': 'part-i-playing-with-plane-curves',
  'label': 'Part I',
  'title': 'Playing with plane curves'},
 {'description': 'The algebra-geometry dictionary for affine varieties and their maps.',
  'folder': 'part-ii-the-category-of-affine-varieties',
  'label': 'Part II',
  'title': 'The category of affine varieties'},
 {'description': 'Projective geometry, singularities, cubic surfaces, and modern context.',
  'folder': 'part-iii-applications',
  'label': 'Part III',
  'title': 'Applications'}]

ENTRIES = [{'artifact': 'chapter-00',
  'checks': ['singular point equations',
             'discriminant for repeated roots',
             'component-change samples',
             'denominator exclusion'],
  'concepts': ['polynomial loci',
               'specific examples versus theory',
               'function categories',
               'rigidity',
               'rational maps',
               'fields as geometry settings'],
  'focus': 'Why polynomial zero sets deserve their own geometry, why functions matter, and how '
           'algebra replaces local calculus.',
  'folder': 'prologue/chapter-00-woffle',
  'kind': 'chapter',
  'notebook': '00-woffle.ipynb',
  'number': 0,
  'part': 'Prologue',
  'part_folder': 'prologue',
  'pdf_span': '9-16',
  'printed_span': '11-18',
  'sections': '0.1-0.6 and exercises',
  'title': 'Woffle',
  'visuals': ['cubic-family-topology',
              'function-category-rigidity',
              'repeated-root-discriminant',
              'rational-map-domain-mask']},
 {'artifact': 'chapter-01',
  'checks': ['parametrization residuals',
             'homogenize dehomogenize round trip',
             'conic matrix determinant',
             'five point rank count'],
  'concepts': ['parametrized conics',
               'projective plane charts',
               'homogeneous equations',
               'line at infinity',
               'Bezout in easy cases',
               'pencils of conics'],
  'focus': 'Conics as the first laboratory for projective coordinates, parametrization, '
           'intersection counting, and linear systems.',
  'folder': 'part-i-playing-with-plane-curves/chapter-01-plane-conics',
  'kind': 'chapter',
  'notebook': '01-plane-conics.ipynb',
  'number': 1,
  'part': 'Part I: Playing with plane curves',
  'part_folder': 'part-i-playing-with-plane-curves',
  'pdf_span': '17-32',
  'printed_span': '19-34',
  'sections': '1.1-1.14 and exercises',
  'title': 'Plane conics',
  'visuals': ['projection-parametrizes-conic',
              'projective-plane-charts',
              'affine-projective-conic-gallery',
              'pencil-degenerate-conics']},
 {'artifact': 'chapter-02',
  'checks': ['cubic parametrization substitution',
             'linear system rank',
             'addition closure',
             'associativity samples'],
  'concepts': ['singular cubic parametrization',
               'smooth cubic obstruction',
               'linear systems',
               'ninth point theorem',
               'elliptic group law',
               'genus and topology'],
  'focus': 'Singular and smooth cubics, linear systems, the ninth point, chord-tangent addition, '
           'and the first appearance of genus.',
  'folder': 'part-i-playing-with-plane-curves/chapter-02-cubics-and-the-group-law',
  'kind': 'chapter',
  'notebook': '02-cubics-and-the-group-law.ipynb',
  'number': 2,
  'part': 'Part I: Playing with plane curves',
  'part_folder': 'part-i-playing-with-plane-curves',
  'pdf_span': '33-52',
  'printed_span': '35-54',
  'sections': '2.1-2.16 and exercises',
  'title': 'Cubics and the group law',
  'visuals': ['singular-cubic-param-gallery',
              'smooth-cubic-branch-cover',
              'cubic-pencil-ninth-point',
              'group-law-chord-tangent']},
 {'artifact': 'chapter-03',
  'checks': ['Groebner membership',
             'component factorization',
             'radical toy example',
             'finite projection fibers'],
  'concepts': ['Noetherian rings',
               'Hilbert basis theorem',
               'V and I correspondence',
               'Zariski topology',
               'radical ideals',
               'Noether normalization'],
  'focus': 'The affine algebra-geometry dictionary: ideals define loci, loci define radical '
           'ideals, and finite generation makes the dictionary computable.',
  'folder': 'part-ii-the-category-of-affine-varieties/chapter-03-affine-varieties-and-the-nullstellensatz',
  'kind': 'chapter',
  'notebook': '03-affine-varieties-and-the-nullstellensatz.ipynb',
  'number': 3,
  'part': 'Part II: The category of affine varieties',
  'part_folder': 'part-ii-the-category-of-affine-varieties',
  'pdf_span': '55-70',
  'printed_span': '57-72',
  'sections': '3.1-3.17 and exercises',
  'title': 'Affine varieties and the Nullstellensatz',
  'visuals': ['vi-correspondence-lattice',
              'zariski-topology-contrast',
              'radical-versus-multiplicity',
              'noether-normalization-projection']},
 {'artifact': 'chapter-04',
  'checks': ['pullback substitution',
             'semigroup missing generator',
             'domain denominator test',
             'composition after simplification'],
  'concepts': ['coordinate rings',
               'pullback contravariance',
               'isomorphism criterion',
               'function fields',
               'rational map domains',
               'standard opens'],
  'focus': 'Coordinate rings, polynomial maps, pullbacks, function fields, rational maps, standard '
           'opens, and when maps are actually isomorphisms.',
  'folder': 'part-ii-the-category-of-affine-varieties/chapter-04-functions-on-varieties',
  'kind': 'chapter',
  'notebook': '04-functions-on-varieties.ipynb',
  'number': 4,
  'part': 'Part II: The category of affine varieties',
  'part_folder': 'part-ii-the-category-of-affine-varieties',
  'pdf_span': '71-82',
  'printed_span': '73-84',
  'sections': '4.1-4.14 and exercises',
  'title': 'Functions on varieties',
  'visuals': ['coordinate-ring-quotient',
              'pullback-contravariance',
              'cusp-not-isomorphism',
              'standard-open-graph']},
 {'artifact': 'chapter-05',
  'checks': ['homogeneous round trip',
             'rank one minors',
             'projection inverse on open sets',
             'quadric ruling equation'],
  'concepts': ['homogeneous ideals',
               'projective Nullstellensatz',
               'affine chart cover',
               'rational maps',
               'birational equivalence',
               'Segre and Veronese embeddings'],
  'focus': 'Projective varieties, homogeneous coordinate rings, affine charts, rational maps, '
           'birational equivalence, and rational examples.',
  'folder': 'part-iii-applications/chapter-05-projective-and-birational-geometry',
  'kind': 'chapter',
  'notebook': '05-projective-and-birational-geometry.ipynb',
  'number': 5,
  'part': 'Part III: Applications',
  'part_folder': 'part-iii-applications',
  'pdf_span': '85-98',
  'printed_span': '87-100',
  'sections': '5.0-5.11 and exercises',
  'title': 'Projective and birational geometry',
  'visuals': ['projective-line-gluing',
              'projective-cubic-affine-charts',
              'quadric-projection-and-rulings',
              'segre-veronese-rank-one']},
 {'artifact': 'chapter-06',
  'checks': ['solve f and partials',
             'Jacobian nullity',
             'Euler identity',
             'strict transform nonsingularity'],
  'concepts': ['gradient tangent hyperplanes',
               'singular locus',
               'Jacobian rank',
               'tangent dimension',
               'projective tangent space',
               'blowup charts'],
  'focus': 'Algebraic tangent spaces, singular loci, dimension, intrinsic tangent definitions, and '
           'blowups as local resolution experiments.',
  'folder': 'part-iii-applications/chapter-06-tangent-space-nonsingularity-dimension',
  'kind': 'chapter',
  'notebook': '06-tangent-space-nonsingularity-dimension.ipynb',
  'number': 6,
  'part': 'Part III: Applications',
  'part_folder': 'part-iii-applications',
  'pdf_span': '99-106',
  'printed_span': '101-108',
  'sections': '6.1-6.12 and exercises',
  'title': 'Tangent space and nonsingularity, dimension',
  'visuals': ['tangent-hyperplane-sweep',
              'singular-curve-gallery',
              'jacobian-rank-strata',
              'blowup-strict-transform']},
 {'artifact': 'chapter-07',
  'checks': ['line substitution', 'resultant degree', 'Plucker incidence', 'Fermat line count'],
  'concepts': ['cubic surface sections',
               'polar form',
               'lines meeting a line',
               'skew lines',
               'rationality map',
               '27 line incidence'],
  'focus': 'A classical configuration theorem made visible through lines on a cubic surface, polar '
           'forms, rationality, and incidence.',
  'folder': 'part-iii-applications/chapter-07-the-27-lines-on-a-cubic-surface',
  'kind': 'chapter',
  'notebook': '07-the-27-lines-on-a-cubic-surface.ipynb',
  'number': 7,
  'part': 'Part III: Applications',
  'part_folder': 'part-iii-applications',
  'pdf_span': '107-118',
  'printed_span': '109-120',
  'sections': '7.1-7.7 and exercises',
  'title': 'The 27 lines on a cubic surface',
  'visuals': ['cubic-surface-plane-sections',
              'polar-line-condition-flow',
              'fermat-cubic-lines',
              'twenty-seven-line-incidence-graph']},
 {'artifact': 'chapter-08',
  'checks': ['dual number nilpotence', 'monomial count', 'mod p reduction', 'incidence dimension'],
  'concepts': ['modern algebraic geometry timeline',
               'regular functions and sheaves',
               'Spec and generic points',
               'nilpotent thickening',
               'arithmetic fibers',
               'Grassmannian incidence'],
  'focus': 'A bridge from classical varieties to sheaves, schemes, nilpotents, arithmetic fibers, '
           'and the incidence count behind cubic-surface lines.',
  'folder': 'part-iii-applications/chapter-08-final-comments',
  'kind': 'chapter',
  'notebook': '08-final-comments.ipynb',
  'number': 8,
  'part': 'Part III: Applications',
  'part_folder': 'part-iii-applications',
  'pdf_span': '119-130',
  'printed_span': '121-132',
  'sections': '8.1-8.16',
  'title': 'Final comments',
  'visuals': ['modern-ag-timeline',
              'spec-poset-and-generic-points',
              'dual-number-nilpotent-thickening',
              'grassmannian-incidence-count']}]

def chapter_by_number(number: int) -> dict[str, object]:
    for entry in ENTRIES:
        if int(entry['number']) == number:
            return entry
    raise KeyError(number)

def entries_for_part(folder: str) -> list[dict[str, object]]:
    return [entry for entry in ENTRIES if entry['part_folder'] == folder]

def canonical_notebooks(book_root: Path) -> list[Path]:
    return [book_root / str(entry['folder']) / str(entry['notebook']) for entry in ENTRIES]
