"""Section metadata and source map for Rockafellar's Convex Analysis course."""

from __future__ import annotations

from collections import defaultdict
from typing import Any

PDF_OFFSET = 18

PARTS: list[dict[str, Any]] = [
    {"number": 1, "title": "Basic Concepts", "slug": "part-01-basic-concepts"},
    {"number": 2, "title": "Topological Properties", "slug": "part-02-topological-properties"},
    {"number": 3, "title": "Duality Correspondences", "slug": "part-03-duality-correspondences"},
    {
        "number": 4,
        "title": "Representation and Inequalities",
        "slug": "part-04-representation-and-inequalities",
    },
    {"number": 5, "title": "Differential Theory", "slug": "part-05-differential-theory"},
    {
        "number": 6,
        "title": "Constrained Extremum Problems",
        "slug": "part-06-constrained-extremum-problems",
    },
    {
        "number": 7,
        "title": "Saddle-Functions and Minimax Theory",
        "slug": "part-07-saddle-functions-and-minimax-theory",
    },
    {"number": 8, "title": "Convex Algebra", "slug": "part-08-convex-algebra"},
]

_PART_BY_NUMBER = {part["number"]: part for part in PARTS}


def _section(
    number: int,
    title: str,
    part: int,
    printed_start: int,
    printed_end: int,
    slug_tail: str,
    focus: str,
    concepts: list[str],
    visual_story: str,
    check: str,
    proof_nodes: list[str],
) -> dict[str, Any]:
    part_info = _PART_BY_NUMBER[part]
    slug = f"section-{number:02d}-{slug_tail}"
    return {
        "number": number,
        "title": title,
        "part": part,
        "part_title": part_info["title"],
        "part_slug": part_info["slug"],
        "printed_start": printed_start,
        "printed_end": printed_end,
        "pdf_start": printed_start + PDF_OFFSET,
        "pdf_end": printed_end + PDF_OFFSET,
        "slug": slug,
        "folder": f"{part_info['slug']}/{slug}",
        "notebook": f"{number:02d}-{slug_tail}.ipynb",
        "artifact_key": f"{part_info['slug']}/{slug}",
        "focus": focus,
        "concepts": concepts,
        "visual_story": visual_story,
        "check": check,
        "proof_nodes": proof_nodes,
        "libraries": ["numpy", "matplotlib", "networkx", "sympy"],
    }


SECTIONS: list[dict[str, Any]] = [
    _section(
        1,
        "Affine Sets",
        1,
        3,
        9,
        "affine-sets",
        "affine hulls, translations, hyperplanes, barycentric coordinates",
        ["affine hull", "subspace translate", "hyperplane normal", "barycentric coordinates"],
        "A point cloud is extended to its affine hull while a normal vector exposes the hyperplane equation.",
        "Affine coefficients add to one and the recovered point lies on the displayed affine hull.",
        ["linear combinations", "affine combinations", "affine hull", "hyperplane equations"],
    ),
    _section(
        2,
        "Convex Sets and Cones",
        1,
        10,
        15,
        "convex-sets-and-cones",
        "convex combinations, half-spaces, cones, convex hull generation",
        ["convex combination", "half-space", "convex cone", "polytope"],
        "Segments inside a convex polygon are compared with cone rays and a half-space cut.",
        "Midpoints stay in the convex set, cone sums stay in the cone, and the half-space sign is correct.",
        ["segments", "convexity", "cone closure", "hull generation"],
    ),
    _section(
        3,
        "The Algebra of Convex Sets",
        1,
        16,
        22,
        "algebra-of-convex-sets",
        "Minkowski sums, scalar multiplication, convex hulls, linear images",
        ["Minkowski sum", "linear image", "convex hull", "set addition"],
        "Two small convex bodies are added pointwise, then their support values confirm the algebra.",
        "A support value of the sum equals the sum of support values in the same direction.",
        ["set operations", "Minkowski sum", "linear image", "support check"],
    ),
    _section(
        4,
        "Convex Functions",
        1,
        23,
        31,
        "convex-functions",
        "Jensen inequality, epigraphs, indicators, perspective from sets to functions",
        ["epigraph", "Jensen inequality", "indicator function", "proper convex function"],
        "A convex curve is taught through its epigraph rather than only through its graph.",
        "A sampled Jensen inequality is nonnegative and the epigraph points sit above the curve.",
        ["convex set", "epigraph", "Jensen check", "function-set bridge"],
    ),
    _section(
        5,
        "Functional Operations",
        1,
        32,
        42,
        "functional-operations",
        "addition, supremum, infimal projection, perspective, generated examples",
        ["pointwise supremum", "sum", "infimal convolution", "perspective"],
        "Pointwise maximum and sum operations are plotted as generators of new convex functions.",
        "Midpoint convexity survives the displayed functional operations on the sampled grid.",
        ["basic functions", "operations", "new convex functions", "sampled convexity"],
    ),
    _section(
        6,
        "Relative Interiors of Convex Sets",
        2,
        43,
        50,
        "relative-interiors-of-convex-sets",
        "relative interior, affine hull, boundary behavior under convex operations",
        ["relative interior", "affine hull", "relative boundary", "dimension"],
        "A full-dimensional square, an edge, and a singleton separate ambient from relative interior.",
        "Relative interior sample points have the expected affine-hull dimension and boundary status.",
        ["affine hull", "relative topology", "relative interior", "operation rules"],
    ),
    _section(
        7,
        "Closures of Convex Functions",
        2,
        51,
        59,
        "closures-of-convex-functions",
        "lower semicontinuity, closed epigraphs, closure of a proper convex function",
        ["lower semicontinuity", "closed epigraph", "closure operation", "boundary value"],
        "An endpoint gap is closed by moving from an open epigraph boundary to a closed one.",
        "The closed function has the same interior samples and adds the missing boundary value.",
        ["epigraph", "boundary gap", "lower closure", "closed function"],
    ),
    _section(
        8,
        "Recession Cones and Unboundedness",
        2,
        60,
        71,
        "recession-cones-and-unboundedness",
        "directions at infinity, recession cones of sets and functions, growth behavior",
        ["recession cone", "unbounded set", "recession function", "level set growth"],
        "An unbounded convex region is annotated by every direction in which it can recede.",
        "Adding a recession direction keeps sampled points inside the set.",
        ["bounded slice", "recession direction", "ray test", "growth condition"],
    ),
    _section(
        9,
        "Some Closedness Criteria",
        2,
        72,
        81,
        "some-closedness-criteria",
        "closed convex images, projections, recession obstructions, existence criteria",
        ["linear image", "projection", "closedness", "recession obstruction"],
        "A closed epigraph is projected to a nonclosed interval, making the missing limit visible.",
        "The projection has infimum zero but no point with projected coordinate zero.",
        ["closed set", "projection", "lost boundary", "recession condition"],
    ),
    _section(
        10,
        "Continuity of Convex Functions",
        2,
        82,
        94,
        "continuity-of-convex-functions",
        "continuity on relative interiors, secant estimates, convergence of convex functions",
        ["continuity", "relative interior", "secant slope", "convex convergence"],
        "Secant slopes bracket a convex graph and show why interior continuity is forced.",
        "Displayed secant slopes are monotone in the sample order.",
        ["convex graph", "secants", "local bounds", "continuity"],
    ),
    _section(
        11,
        "Separation Theorems",
        3,
        95,
        101,
        "separation-theorems",
        "proper and strong separation, supporting hyperplanes, half-space certificates",
        ["separating hyperplane", "supporting half-space", "proper separation", "strong separation"],
        "Two disjoint convex bodies are certified by a signed-distance separating line.",
        "All points of the two bodies have opposite signed margins with a positive gap.",
        ["disjoint convex sets", "normal vector", "separating line", "certificate"],
    ),
    _section(
        12,
        "Conjugates of Convex Functions",
        3,
        102,
        111,
        "conjugates-of-convex-functions",
        "Fenchel conjugacy, affine minorants, biconjugacy, dual slopes",
        ["Fenchel conjugate", "affine minorant", "biconjugate", "duality pairing"],
        "A quadratic is reconstructed from its supporting affine minorants indexed by slope.",
        "Fenchel equality holds at the slope paired with the sampled primal point.",
        ["affine minorants", "slope parameter", "conjugate", "Fenchel equality"],
    ),
    _section(
        13,
        "Support Functions",
        3,
        112,
        120,
        "support-functions",
        "support functions, exposed faces, domain and level-set support calculations",
        ["support function", "exposed face", "normal direction", "level set"],
        "A polygon is scanned by rotating normals and recording the farthest support line.",
        "The support value equals the maximum dot product over the sampled vertices.",
        ["normal scan", "support line", "exposed face", "support value"],
    ),
    _section(
        14,
        "Polars of Convex Sets",
        3,
        121,
        127,
        "polars-of-convex-sets",
        "polar sets, cone polarity, closed convex sets containing the origin",
        ["polar set", "dual cone", "origin condition", "bipolar"],
        "A centrally placed convex body is drawn beside its polar body in dual coordinates.",
        "Sampled primal-dual dot products stay below the polar threshold.",
        ["origin-centered body", "polar body", "dot-product bound", "bipolar intuition"],
    ),
    _section(
        15,
        "Polars of Convex Functions",
        3,
        128,
        139,
        "polars-of-convex-functions",
        "polar gauges, dual norms, functional polarity, approximation examples",
        ["gauge", "dual norm", "polar function", "unit ball"],
        "The l1 and l-infinity unit balls show how a norm's polar is read geometrically.",
        "The dual norm inequality bounds sampled pairings by the product of primal and dual norms.",
        ["primal norm", "polar unit ball", "dual norm", "duality inequality"],
    ),
    _section(
        16,
        "Dual Operations",
        3,
        140,
        152,
        "dual-operations",
        "duality of addition and infimal convolution, closure terms, operation pairs",
        ["dual operation", "infimal convolution", "conjugate of a sum", "closure"],
        "Two convex functions combine in primal space while the dual view tracks infimal convolution.",
        "A grid infimum is no larger than either unshifted summand and keeps convex midpoint behavior.",
        ["operation pair", "infimal convolution", "sample minimization", "dual table"],
    ),
    _section(
        17,
        "Caratheodory's Theorem",
        4,
        153,
        161,
        "caratheodorys-theorem",
        "small convex representations, dimension count, convex hull reduction",
        ["Caratheodory representation", "dimension", "simplex", "convex coefficients"],
        "A point in a planar hull is represented by three vertices rather than by all points.",
        "The reduced barycentric coefficients are nonnegative and add to one.",
        ["many points", "dimension reduction", "simplex support", "convex representation"],
    ),
    _section(
        18,
        "Extreme Points and Faces of Convex Sets",
        4,
        162,
        169,
        "extreme-points-and-faces-of-convex-sets",
        "faces, exposed points, extreme directions, tangent hyperplanes",
        ["extreme point", "face", "exposed face", "supporting hyperplane"],
        "A support line exposes a face of a polygon and distinguishes vertices from edge interiors.",
        "All points on the exposed face share the same support value.",
        ["support direction", "exposed face", "extreme points", "face lattice"],
    ),
    _section(
        19,
        "Polyhedral Convex Sets and Functions",
        4,
        170,
        178,
        "polyhedral-convex-sets-and-functions",
        "finite half-space descriptions, piecewise-linear functions, polyhedral epigraphs",
        ["polyhedron", "piecewise-linear function", "finite inequalities", "polyhedral epigraph"],
        "A max of affine functions is plotted as a polyhedral convex function with active regions.",
        "Each sampled function value equals the maximum of its affine pieces.",
        ["affine pieces", "maximum", "active region", "polyhedral graph"],
    ),
    _section(
        20,
        "Some Applications of Polyhedral Convexity",
        4,
        179,
        184,
        "applications-of-polyhedral-convexity",
        "polyhedral refinements, active constraints, stronger closedness and existence statements",
        ["active constraint", "linear program", "polyhedral refinement", "finite certificate"],
        "A small linear program highlights active inequalities and a vertex certificate.",
        "The selected optimum satisfies all inequalities and ties the active constraints.",
        ["feasible polygon", "objective direction", "active set", "vertex certificate"],
    ),
    _section(
        21,
        "Helly's Theorem and Systems of Inequalities",
        4,
        185,
        197,
        "hellys-theorem-and-systems-of-inequalities",
        "finite intersection tests, nonlinear inequalities, Helly dimension logic",
        ["Helly theorem", "intersection certificate", "systems of inequalities", "dimension"],
        "Several convex half-planes are inspected through a small witness point and subfamilies.",
        "The witness point satisfies every displayed inequality.",
        ["finite family", "subfamily tests", "common point", "inequality system"],
    ),
    _section(
        22,
        "Linear Inequalities",
        4,
        198,
        212,
        "linear-inequalities",
        "Farkas alternatives, strict and weak inequalities, linear certificates",
        ["Farkas certificate", "linear system", "cone membership", "alternative theorem"],
        "A target vector outside a cone is separated by a certificate normal.",
        "The certificate is nonnegative on cone generators and negative on the rejected target.",
        ["cone generators", "target vector", "separating certificate", "alternative"],
    ),
    _section(
        23,
        "Directional Derivatives and Subgradients",
        5,
        213,
        226,
        "directional-derivatives-and-subgradients",
        "directional derivatives, subgradient inequality, subdifferential calculus",
        ["directional derivative", "subgradient", "subdifferential", "supporting line"],
        "The absolute-value cusp displays a full interval of supporting slopes at one point.",
        "Every sampled supporting line remains below the convex graph.",
        ["directional slopes", "subgradient interval", "support line", "subgradient inequality"],
    ),
    _section(
        24,
        "Differential Continuity and Monotonicity",
        5,
        227,
        240,
        "differential-continuity-and-monotonicity",
        "monotonicity of subdifferentials, one-dimensional slope curves, graph closure",
        ["monotone graph", "subdifferential mapping", "one-sided derivative", "complete curve"],
        "A piecewise-linear convex function produces a monotone vertical-jump subgradient graph.",
        "All sampled pairs satisfy the monotonicity inequality.",
        ["left slope", "right slope", "subgradient graph", "monotonicity"],
    ),
    _section(
        25,
        "Differentiability of Convex Functions",
        5,
        241,
        250,
        "differentiability-of-convex-functions",
        "almost-everywhere gradients, continuity of gradients, smooth versus nonsmooth points",
        ["gradient", "differentiability", "smooth convex function", "nonsmooth point"],
        "A smooth quadratic and a kinked absolute-value term separate gradient from subgradient behavior.",
        "Central finite differences match the analytic gradient away from the kink.",
        ["smooth sample", "kink sample", "finite difference", "gradient map"],
    ),
    _section(
        26,
        "The Legendre Transformation",
        5,
        251,
        262,
        "legendre-transformation",
        "gradient inversion, conjugate smoothness, strict convexity, dual coordinates",
        ["Legendre transform", "gradient map", "strict convexity", "dual coordinate"],
        "A strictly convex quadratic sends primal positions to slopes and back through the conjugate.",
        "The primal gradient and conjugate gradient invert one another on the sample grid.",
        ["primal coordinate", "slope coordinate", "conjugate coordinate", "inverse gradient"],
    ),
    _section(
        27,
        "The Minimum of a Convex Function",
        6,
        263,
        272,
        "minimum-of-a-convex-function",
        "existence of minimizers, recession, level sets, optimality by zero subgradient",
        ["minimizer", "level set", "recession", "zero subgradient"],
        "Level sets contract toward the minimizer while the subgradient condition marks optimality.",
        "The sampled minimizer has zero gradient and the smallest displayed objective value.",
        ["level sets", "minimizer", "zero subgradient", "existence check"],
    ),
    _section(
        28,
        "Ordinary Convex Programs and Lagrange Multipliers",
        6,
        273,
        290,
        "ordinary-convex-programs-and-lagrange-multipliers",
        "convex constraints, KKT multipliers, complementary slackness, active normals",
        ["convex program", "Lagrange multiplier", "KKT condition", "complementary slackness"],
        "A constrained quadratic minimization shows objective contours balanced by active constraint normals.",
        "Stationarity and complementary slackness residuals are near zero for the displayed solution.",
        ["feasible set", "objective contour", "active normal", "KKT residual"],
    ),
    _section(
        29,
        "Bifunctions and Generalized Convex Programs",
        6,
        291,
        306,
        "bifunctions-and-generalized-convex-programs",
        "convex bifunctions, perturbation functions, generalized multipliers",
        ["bifunction", "perturbation", "value function", "generalized multiplier"],
        "A perturbation parameter moves the right-hand side and traces a convex value function.",
        "The sampled value curve satisfies midpoint convexity.",
        ["perturbed program", "value function", "multiplier slope", "convexity check"],
    ),
    _section(
        30,
        "Adjoint Bifunctions and Dual Programs",
        6,
        307,
        326,
        "adjoint-bifunctions-and-dual-programs",
        "adjoints, dual programs, weak duality, saddle certificates",
        ["adjoint bifunction", "dual program", "weak duality", "duality gap"],
        "Primal and dual objective curves are paired to make weak duality a visible inequality.",
        "Every displayed primal value is no smaller than the paired dual lower bound.",
        ["primal program", "dual program", "adjoint pairing", "gap check"],
    ),
    _section(
        31,
        "Fenchel's Duality Theorem",
        6,
        327,
        341,
        "fenchels-duality-theorem",
        "Fenchel duality, conjugate sums, exact primal-dual equality, qualification",
        ["Fenchel duality", "conjugate", "primal-dual equality", "qualification"],
        "A quadratic-plus-indicator problem is paired with its dual support calculation.",
        "The selected primal and dual values agree within numerical tolerance.",
        ["primal function", "dual function", "Fenchel equality", "qualification check"],
    ),
    _section(
        32,
        "The Maximum of a Convex Function",
        6,
        342,
        348,
        "maximum-of-a-convex-function",
        "maximizing convex functions, extreme points, compact convex domains",
        ["convex maximization", "extreme point", "compact set", "polytope vertex"],
        "A convex function over a polygon puts its maximum on a vertex rather than in the middle.",
        "The maximum over a sampled grid is bounded by the maximum over vertices.",
        ["convex objective", "polygon domain", "vertex scan", "maximum certificate"],
    ),
    _section(
        33,
        "Saddle-Functions",
        7,
        349,
        358,
        "saddle-functions",
        "convex-concave functions, saddle points, bifunction correspondence",
        ["saddle-function", "convex-concave", "saddle point", "Lagrangian"],
        "Contours of a convex-concave quadratic display descent in one variable and ascent in another.",
        "The saddle point has zero partial derivatives and the expected saddle inequalities nearby.",
        ["convex direction", "concave direction", "saddle point", "partial gradients"],
    ),
    _section(
        34,
        "Closures and Equivalence Classes",
        7,
        359,
        369,
        "closures-and-equivalence-classes",
        "closed saddle-functions, equivalence classes, boundary regularization",
        ["closed saddle-function", "equivalence class", "boundary closure", "regularization"],
        "A saddle surface over an open rectangle is compared with its closed boundary extension.",
        "Boundary samples match the closure values prescribed by the extension.",
        ["open domain", "boundary closure", "equivalence class", "regularized saddle"],
    ),
    _section(
        35,
        "Continuity and Differentiability of Saddle-functions",
        7,
        370,
        378,
        "continuity-and-differentiability-of-saddle-functions",
        "partial gradients, convex-concave monotonicity, continuity of saddle mappings",
        ["partial subgradient", "monotonicity", "differentiability", "saddle mapping"],
        "A vector field of partial gradients shows monotone behavior in x and antimonotone behavior in y.",
        "The sampled partial-gradient pairing has the expected signs.",
        ["partial gradients", "convex variable", "concave variable", "sign check"],
    ),
    _section(
        36,
        "Minimax Problems",
        7,
        379,
        387,
        "minimax-problems",
        "minimax values, saddle-points, convex-concave programs, order of optimization",
        ["minimax", "maximin", "saddle value", "order of optimization"],
        "A convex-concave payoff on a box shows when min max and max min agree.",
        "The computed minmax and maximin values agree for the displayed saddle example.",
        ["row value", "column value", "saddle value", "order check"],
    ),
    _section(
        37,
        "Conjugate Saddle-functions and Minimax Theorems",
        7,
        388,
        400,
        "conjugate-saddle-functions-and-minimax-theorems",
        "saddle conjugacy, inverse bifunctions, minimax theorems, existence",
        ["saddle conjugate", "minimax theorem", "inverse bifunction", "existence condition"],
        "A quadratic saddle is transformed through a conjugate pairing and compared with the original.",
        "The sampled biconjugate reconstruction matches the original quadratic saddle values.",
        ["saddle pairing", "conjugate", "biconjugate", "minimax equality"],
    ),
    _section(
        38,
        "The Algebra of Bifunctions",
        8,
        401,
        412,
        "algebra-of-bifunctions",
        "addition and composition of bifunctions, adjoints, convex algebra identities",
        ["bifunction algebra", "composition", "adjoint", "inner product"],
        "A small matrix model visualizes the algebraic shape of adding and composing convex bifunction analogues.",
        "The displayed matrices satisfy the adjoint-of-composition identity.",
        ["bifunction A", "bifunction B", "composition", "adjoint identity"],
    ),
    _section(
        39,
        "Convex Processes",
        8,
        413,
        424,
        "convex-processes",
        "set-valued convex processes, graph cones, process images, inverse processes",
        ["convex process", "set-valued map", "graph cone", "inverse process"],
        "A cone-valued process maps one input ray to a wedge of outputs through a convex graph.",
        "The graph samples are closed under positive scaling and convex addition.",
        ["input cone", "output wedge", "graph cone", "process closure"],
    ),
]


def sections() -> list[dict[str, Any]]:
    """Return a copy of the section catalog."""
    return [dict(section) for section in SECTIONS]


def parts() -> list[dict[str, Any]]:
    """Return the part catalog."""
    return [dict(part) for part in PARTS]


def get_section(number: int) -> dict[str, Any]:
    for section in SECTIONS:
        if section["number"] == number:
            return dict(section)
    raise KeyError(f"unknown section number: {number}")


def sections_by_part() -> dict[int, list[dict[str, Any]]]:
    grouped: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for section in SECTIONS:
        grouped[section["part"]].append(dict(section))
    return dict(grouped)


def source_map_records() -> list[dict[str, Any]]:
    keys = [
        "number",
        "title",
        "part",
        "part_title",
        "printed_start",
        "printed_end",
        "pdf_start",
        "pdf_end",
        "folder",
        "notebook",
        "artifact_key",
        "focus",
    ]
    return [{key: section[key] for key in keys} for section in SECTIONS]

