"""Source map and teaching inventory for the Bridson-Haefliger notebook course."""

from __future__ import annotations

from pathlib import Path

BOOK_ROOT = Path(__file__).resolve().parents[1]
PDF_NAME = "Metric Spaces of Non-Positive Curvature.pdf"
PDF_PATH = BOOK_ROOT / PDF_NAME
PRINTED_TO_PDF_OFFSET = 19
UNITS = [{'artifact_stem': 'i-01-metric-geodesic-angle-dashboard',
  'concepts': ['pseudometric versus metric',
               'geodesic segment and ray',
               'metric graph',
               'Alexandrov upper angle',
               'rectifiable curve'],
  'focus': 'Build the dictionary from distance to geodesic behavior, then turn angle and length into '
           'measurable notebook objects.',
  'folder': 'part-01-geodesic-metric-spaces/chapter-i-01-basic-concepts',
  'id': 'chapter-i-01',
  'lab': 'Compare l1, l_infinity, and Euclidean paths with the same endpoints and inspect where uniqueness '
         'fails.',
  'libraries': ['matplotlib', 'networkx', 'sympy'],
  'notebook': 'i-01-basic-concepts.ipynb',
  'number': 'I.1',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [21, 33],
  'printed_pages': [2, 14],
  'proof_strategy': 'Use a dependency graph to show how the triangle inequality supports length, midpoint, '
                    'geodesic, and angle comparisons.',
  'source_sections': ['metric spaces', 'geodesics', 'Alexandrov angles', 'curve length'],
  'title': 'Basic Concepts',
  'visual_family': 'triangle'},
 {'artifact_stem': 'i-02-model-space-comparison-triangle',
  'concepts': ['constant curvature models',
               'spherical distance',
               'hyperbolic distance',
               'comparison triangle',
               'isometry group'],
  'focus': 'Treat E^n, S^n, and H^n as measuring instruments for later CAT(k) comparisons.',
  'folder': 'part-01-geodesic-metric-spaces/chapter-i-02-the-model-spaces',
  'id': 'chapter-i-02',
  'lab': 'Vary the curvature parameter and watch a fixed side-length triple bend from spherical to Euclidean '
         'to hyperbolic behavior.',
  'libraries': ['matplotlib', 'plotly', 'sympy'],
  'notebook': 'i-02-the-model-spaces.ipynb',
  'number': 'I.2',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [34, 50],
  'printed_pages': [15, 31],
  'proof_strategy': 'Place one side-length triple into all admissible models and compare angle and midpoint '
                    'data.',
  'source_sections': ['Euclidean space', 'sphere', 'hyperbolic space', 'Alexandrov lemma', 'isometry groups'],
  'title': 'The Model Spaces',
  'visual_family': 'model'},
 {'artifact_stem': 'i-03-length-space-intrinsic-distance',
  'concepts': ['length metric',
               'intrinsic distance',
               'properness',
               'Hopf-Rinow principle',
               'covering length metric'],
  'focus': 'Turn curves into distances and separate induced metrics from intrinsic length metrics.',
  'folder': 'part-01-geodesic-metric-spaces/chapter-i-03-length-spaces',
  'id': 'chapter-i-03',
  'lab': 'Measure chord distance and arc distance on a circle and explain why the same point set carries two '
         'different geometries.',
  'libraries': ['matplotlib', 'networkx', 'numpy'],
  'notebook': 'i-03-length-spaces.ipynb',
  'number': 'I.3',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [51, 65],
  'printed_pages': [32, 46],
  'proof_strategy': 'Track how a distance defined by infimum over curves changes under completion, covering, '
                    'and compactness hypotheses.',
  'source_sections': ['length metrics',
                      'Hopf-Rinow',
                      'Riemannian metric spaces',
                      'covering spaces',
                      'constant curvature manifolds'],
  'title': 'Length Spaces',
  'visual_family': 'construction'},
 {'artifact_stem': 'i-04-norm-ball-geodesic-uniqueness',
  'concepts': ['Hilbert norm',
               'strict convexity',
               'Mazur-Ulam behavior',
               'l^p geometry',
               'parallel geodesics'],
  'focus': 'Use norm balls to see exactly when straight segments are unique geodesics.',
  'folder': 'part-01-geodesic-metric-spaces/chapter-i-04-normed-spaces',
  'id': 'chapter-i-04',
  'lab': 'Plot l1, l2, and l_infinity unit balls and enumerate geodesics between the same two points.',
  'libraries': ['matplotlib', 'numpy', 'sympy'],
  'notebook': 'i-04-normed-spaces.ipynb',
  'number': 'I.4',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [66, 74],
  'printed_pages': [47, 55],
  'proof_strategy': 'Represent equality in the triangle inequality as flat spots on the unit ball.',
  'source_sections': ['Hilbert spaces', 'isometries', 'l^p spaces'],
  'title': 'Normed Spaces',
  'visual_family': 'norm'},
 {'artifact_stem': 'i-05-construction-survival-map',
  'concepts': ['product metric', 'metric cone', 'spherical join', 'quotient metric', 'ultralimit'],
  'focus': 'Assemble new geodesic spaces and record which metric features survive the operation.',
  'folder': 'part-01-geodesic-metric-spaces/chapter-i-05-some-basic-constructions',
  'id': 'chapter-i-05',
  'lab': 'Build a cone over a circle with different circumferences and test which apex neighborhoods behave '
         'like CAT(0) neighborhoods.',
  'libraries': ['matplotlib', 'networkx', 'plotly'],
  'notebook': 'i-05-some-basic-constructions.ipynb',
  'number': 'I.5',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [75, 99],
  'printed_pages': [56, 80],
  'proof_strategy': 'Use a construction flow chart with invariant ledgers for geodesic existence, '
                    'completeness, and curvature input.',
  'source_sections': ['products',
                      'k-cones',
                      'spherical joins',
                      'quotient metrics and gluing',
                      'limits',
                      'ultralimits'],
  'title': 'Some Basic Constructions',
  'visual_family': 'construction'},
 {'artifact_stem': 'i-06-hyperbolic-model-coordinate-dictionary',
  'concepts': ['Klein model', 'Poincare ball', 'half-space model', 'Mobius action', 'hyperbolic isometry'],
  'focus': 'Compare hyperbolic models so geodesics, boundary points, and isometries can be moved between '
           'coordinates.',
  'folder': 'part-01-geodesic-metric-spaces/chapter-i-06-more-on-hyperbolic-geometry',
  'id': 'chapter-i-06',
  'lab': 'Move a sample geodesic between the Poincare and Klein disks and compare visual straightness with '
         'metric straightness.',
  'libraries': ['matplotlib', 'plotly', 'numpy'],
  'notebook': 'i-06-more-on-hyperbolic-geometry.ipynb',
  'number': 'I.6',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [100, 115],
  'printed_pages': [81, 96],
  'proof_strategy': 'Show the same ideal chord and geodesic in two models and track which straight lines '
                    'become circular arcs.',
  'source_sections': ['Klein model',
                      'Mobius group',
                      'Poincare ball',
                      'half-space',
                      'isometries',
                      'Riemannian manifold view'],
  'title': 'More on the Geometry of H^n',
  'visual_family': 'hyperbolic'},
 {'artifact_stem': 'i-07-polyhedral-link-neighborhood',
  'concepts': ['metric simplex',
               'geometric link',
               'cone neighborhood',
               'cubical complex',
               'barycentric subdivision'],
  'focus': 'Make piecewise constant curvature complexes inspectable through cells, links, and local geodesic '
           'tests.',
  'folder': 'part-01-geodesic-metric-spaces/chapter-i-07-mk-polyhedral-complexes',
  'id': 'chapter-i-07',
  'lab': 'Construct a square complex vertex link and test whether every short loop has length at least 2*pi.',
  'libraries': ['matplotlib', 'networkx', 'trimesh'],
  'notebook': 'i-07-mk-polyhedral-complexes.ipynb',
  'number': 'I.7',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [116, 141],
  'printed_pages': [97, 122],
  'proof_strategy': 'Pair a cell complex view with a link view so local metric statements become finite '
                    'combinatorial checks.',
  'source_sections': ['metric simplicial complexes',
                      'geometric links',
                      'geodesic existence',
                      'cubical complexes',
                      'barycentric subdivision'],
  'title': 'M_k-Polyhedral Complexes',
  'visual_family': 'complex'},
 {'artifact_stem': 'app-i-07-abstract-simplex-metric-realization',
  'concepts': ['abstract simplex',
               'geometric realization',
               'edge-length assignment',
               'face compatibility',
               'metric realization'],
  'focus': 'Turn combinatorial incidence data into a metric realization without smuggling in a picture.',
  'folder': 'part-01-geodesic-metric-spaces/appendix-i-07-metrizing-abstract-simplicial-complexes',
  'id': 'appendix-i-07-abstract-simplicial-complexes',
  'lab': 'Start from a finite abstract complex, assign edge lengths, and reject an impossible triangle by '
         'the triangle inequality.',
  'libraries': ['matplotlib', 'networkx', 'numpy'],
  'notebook': 'appendix-i-07-metrizing-abstract-simplicial-complexes.ipynb',
  'number': 'I.7 Appendix',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [142, 149],
  'printed_pages': [123, 130],
  'proof_strategy': 'Use an incidence-to-coordinate pipeline and verify that shared faces receive the same '
                    'metric data.',
  'source_sections': ['abstract simplices', 'metric realization', 'compatibility'],
  'title': 'Metrizing Abstract Simplicial Complexes',
  'visual_family': 'complex'},
 {'artifact_stem': 'i-08-cayley-action-quasi-isometry-lab',
  'concepts': ['isometric group action',
               'fundamental domain',
               'quasi-isometry',
               'ends of a space',
               'growth type'],
  'focus': 'Translate coarse group data into metric actions and quasi-isometry invariants.',
  'folder': 'part-01-geodesic-metric-spaces/chapter-i-08-group-actions-and-quasi-isometries',
  'id': 'chapter-i-08',
  'lab': 'Compare a square grid Cayley graph with the Euclidean plane sampled at integer points and estimate '
         'distortion constants.',
  'libraries': ['networkx', 'matplotlib', 'numpy'],
  'notebook': 'i-08-group-actions-and-quasi-isometries.ipynb',
  'number': 'I.8',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [150, 171],
  'printed_pages': [131, 152],
  'proof_strategy': 'Use Cayley graphs and orbit maps to show how algebra becomes a large-scale metric '
                    'object.',
  'source_sections': ['group actions',
                      'presentations',
                      'quasi-isometries',
                      'ends',
                      'growth',
                      'metric graph approximation'],
  'title': 'Group Actions and Quasi-Isometries',
  'visual_family': 'group'},
 {'artifact_stem': 'app-i-08-presentation-complex-relation-loops',
  'concepts': ['combinatorial 2-complex',
               'attaching word',
               'presentation complex',
               'cellular path',
               'relation loop'],
  'focus': 'Represent a group presentation as a two-dimensional space whose loops remember relations.',
  'folder': 'part-01-geodesic-metric-spaces/appendix-i-08-combinatorial-2-complexes',
  'id': 'appendix-i-08-combinatorial-2-complexes',
  'lab': 'Build the presentation complex of a one-relator group and test the boundary word as a closed path.',
  'libraries': ['networkx', 'matplotlib', 'numpy'],
  'notebook': 'appendix-i-08-combinatorial-2-complexes.ipynb',
  'number': 'I.8 Appendix',
  'part': 'Part I',
  'part_title': 'Geodesic Metric Spaces',
  'pdf_pages': [172, 175],
  'printed_pages': [153, 156],
  'proof_strategy': 'Draw a presentation complex and label how each relator becomes a 2-cell boundary.',
  'source_sections': ['2-cells', 'attaching maps', 'presentations'],
  'title': 'Combinatorial 2-Complexes',
  'visual_family': 'group'},
 {'artifact_stem': 'ii-01-cat-k-comparison-inequality',
  'concepts': ['comparison triangle',
               'CAT(k) inequality',
               'CN inequality',
               'monotonicity of upper bounds',
               'model diameter restriction'],
  'focus': 'Make the CAT(k) inequality operational by comparing every chord in a geodesic triangle with its '
           'model counterpart.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-01-definitions-and-characterizations',
  'id': 'chapter-ii-01',
  'lab': 'Sample points on a geodesic triangle and verify the Euclidean comparison inequality numerically '
         'for a tree-like triangle.',
  'libraries': ['matplotlib', 'plotly', 'sympy'],
  'notebook': 'ii-01-definitions-and-characterizations.ipynb',
  'number': 'II.1',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [177, 187],
  'printed_pages': [158, 168],
  'proof_strategy': 'Use a triangle dashboard where moving two comparison points updates the tested chord '
                    'inequality.',
  'source_sections': ['CAT(k) inequality', 'characterizations', 'monotonicity in k', 'examples'],
  'title': 'Definitions and Characterizations of CAT(k) Spaces',
  'visual_family': 'cat'},
 {'artifact_stem': 'app-ii-01-sectional-curvature-to-cat-k',
  'concepts': ['sectional curvature',
               'Jacobi field intuition',
               'metric comparison',
               'local upper bound',
               'Riemannian example'],
  'focus': 'Connect the metric CAT language back to sectional curvature without requiring tensor fluency.',
  'folder': 'part-02-cat-k-spaces/appendix-ii-01-riemannian-curvature',
  'id': 'appendix-ii-01-riemannian-curvature',
  'lab': 'Compute curvature for simple graph surfaces and label which metric comparison direction the sign '
         'suggests.',
  'libraries': ['matplotlib', 'sympy', 'numpy'],
  'notebook': 'appendix-ii-01-riemannian-curvature.ipynb',
  'number': 'II.1 Appendix',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [188, 193],
  'printed_pages': [169, 174],
  'proof_strategy': 'Use a surface patch with two geodesic spreads and compare second-order triangle '
                    'behavior.',
  'source_sections': ['sectional curvature', 'Riemannian comparison', 'local CAT(k) intuition'],
  'title': 'The Curvature of Riemannian Manifolds',
  'visual_family': 'curvature'},
 {'artifact_stem': 'ii-02-cat0-convex-projection-center',
  'concepts': ['convex distance function',
               'closed convex projection',
               'circumcenter',
               'flat subspace',
               'metric midpoint inequality'],
  'focus': 'Use CAT(0) convexity to make projection, center, and flatness statements computationally '
           'checkable.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-02-convexity-and-consequences',
  'id': 'chapter-ii-02',
  'lab': 'Project a cloud of points to a convex segment and compare maximum radius before and after taking '
         'the center.',
  'libraries': ['matplotlib', 'numpy', 'scipy'],
  'notebook': 'ii-02-convexity-and-consequences.ipynb',
  'number': 'II.2',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [194, 202],
  'printed_pages': [175, 183],
  'proof_strategy': 'Track squared-distance convexity along a geodesic and show why nearest-point projection '
                    'is forced.',
  'source_sections': ['metric convexity', 'projections', 'centers', 'flat subspaces'],
  'title': 'Convexity and Its Consequences',
  'visual_family': 'projection'},
 {'artifact_stem': 'ii-03-space-of-directions-cone-join',
  'concepts': ['Alexandrov angle',
               '4-point condition',
               'Euclidean cone',
               'spherical join',
               'space of directions'],
  'focus': 'Build tangent-like information from directions, cones, joins, and stable comparison angles.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-03-angles-limits-cones-and-joins',
  'id': 'chapter-ii-03',
  'lab': 'Assemble a cone over a finite graph and test which direction graph edges produce short loops.',
  'libraries': ['matplotlib', 'plotly', 'networkx'],
  'notebook': 'ii-03-angles-limits-cones-and-joins.ipynb',
  'number': 'II.3',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [203, 211],
  'printed_pages': [184, 192],
  'proof_strategy': 'Show rays leaving a point, identify their angle metric, and compare the cone built from '
                    'those directions.',
  'source_sections': ['angles in CAT(k)',
                      '4-point limits',
                      'cones',
                      'spherical joins',
                      'space of directions'],
  'title': 'Angles, Limits, Cones and Joins',
  'visual_family': 'cone'},
 {'artifact_stem': 'ii-04-cartan-hadamard-patchwork-lift',
  'concepts': ['local CAT(k)', 'universal cover', 'metric patchwork', 'local isometry', 'injectivity radius'],
  'focus': 'Expose the mechanism that turns local upper curvature bounds into global CAT(k) control on the '
           'universal cover.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-04-cartan-hadamard-theorem',
  'id': 'chapter-ii-04',
  'lab': 'Patch local charts around a loop and compare a simply connected lift with a quotient where the '
         'loop obstructs global uniqueness.',
  'libraries': ['matplotlib', 'networkx', 'numpy'],
  'notebook': 'ii-04-cartan-hadamard-theorem.ipynb',
  'number': 'II.4',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [212, 223],
  'printed_pages': [193, 204],
  'proof_strategy': 'Use overlapping CAT neighborhoods and lifted triangles to visualize why simply '
                    'connected patching removes monodromy.',
  'source_sections': ['local-to-global',
                      'exponential map',
                      'patchwork',
                      'local isometries',
                      'injectivity radius'],
  'title': 'The Cartan-Hadamard Theorem',
  'visual_family': 'patchwork'},
 {'artifact_stem': 'ii-05-link-condition-flag-complex-test',
  'concepts': ['link condition',
               'flag complex',
               'cubical CAT(0) test',
               'two-dimensional subcomplex',
               'presentation complex'],
  'focus': 'Turn upper curvature in a polyhedral complex into the link condition and then into examples.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-05-polyhedral-complexes-bounded-curvature',
  'id': 'chapter-ii-05',
  'lab': 'Check a square complex vertex link for the flag condition and compute the shortest cycle length in '
         'angular units.',
  'libraries': ['matplotlib', 'networkx', 'numpy'],
  'notebook': 'ii-05-polyhedral-complexes-bounded-curvature.ipynb',
  'number': 'II.5',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [224, 246],
  'printed_pages': [205, 227],
  'proof_strategy': 'Draw a vertex star and its link side by side, then mark loops whose length certifies or '
                    'violates CAT(0).',
  'source_sections': ['curvature characterizations',
                      'extending geodesics',
                      'flag complexes',
                      'cubical constructions',
                      '2-complexes',
                      'knot and link groups'],
  'title': 'M_k-Polyhedral Complexes of Bounded Curvature',
  'visual_family': 'complex'},
 {'artifact_stem': 'ii-06-displacement-functions-isometry-types',
  'concepts': ['displacement function',
               'elliptic isometry',
               'hyperbolic isometry',
               'parabolic isometry',
               'Clifford translation'],
  'focus': 'Classify isometries by displacement and connect translation behavior to product splitting.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-06-isometries-of-cat0-spaces',
  'id': 'chapter-ii-06',
  'lab': 'Compute displacement on a line, a tree-like graph, and a Euclidean product to decide which model '
         'behavior is visible.',
  'libraries': ['matplotlib', 'numpy', 'networkx'],
  'notebook': 'ii-06-isometries-of-cat0-spaces.ipynb',
  'number': 'II.6',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [247, 262],
  'printed_pages': [228, 243],
  'proof_strategy': 'Plot displacement profiles for sample actions and identify minima, axes, and '
                    'constant-translation behavior.',
  'source_sections': ['individual isometries',
                      'groups of isometries',
                      'Clifford translations',
                      'compact NPC spaces',
                      'splitting'],
  'title': 'Isometries of CAT(0) Spaces',
  'visual_family': 'group'},
 {'artifact_stem': 'ii-07-flat-torus-minset-grid',
  'concepts': ['free abelian action', 'minset', 'flat', 'cocompact action', 'solvable subgroup theorem'],
  'focus': 'Show how commuting semisimple isometries carve Euclidean flats out of a CAT(0) action.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-07-flat-torus-theorem',
  'id': 'chapter-ii-07',
  'lab': 'Generate two commuting translations on a grid and measure the parallelogram fundamental domain.',
  'libraries': ['matplotlib', 'networkx', 'numpy'],
  'notebook': 'ii-07-flat-torus-theorem.ipynb',
  'number': 'II.7',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [263, 278],
  'printed_pages': [244, 259],
  'proof_strategy': 'Use a lattice of commuting translations and a product minset diagram to see why a flat '
                    'appears.',
  'source_sections': ['flat torus theorem',
                      'cocompact actions',
                      'solvable subgroup theorem',
                      'nonproper actions',
                      'topology applications'],
  'title': 'The Flat Torus Theorem',
  'visual_family': 'flat'},
 {'artifact_stem': 'ii-08-cat0-boundary-rays-horoballs',
  'concepts': ['geodesic ray', 'asymptotic class', 'cone topology', 'Busemann function', 'horoball'],
  'focus': 'Construct the boundary from geodesic rays and compare cone-topology and horofunction viewpoints.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-08-boundary-at-infinity',
  'id': 'chapter-ii-08',
  'lab': 'Compute Busemann functions for parallel Euclidean rays and contrast them with rays pointing to '
         'different boundary points.',
  'libraries': ['matplotlib', 'plotly', 'numpy'],
  'notebook': 'ii-08-boundary-at-infinity.ipynb',
  'number': 'II.8',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [279, 295],
  'printed_pages': [260, 276],
  'proof_strategy': 'Draw rays based at different points and show how bounded-distance classes become the '
                    'same ideal point.',
  'source_sections': ['asymptotic rays',
                      'cone topology',
                      'horofunctions',
                      'Busemann functions',
                      'parabolic isometries'],
  'title': 'The Boundary at Infinity of a CAT(0) Space',
  'visual_family': 'boundary'},
 {'artifact_stem': 'ii-09-tits-boundary-visibility-flats',
  'concepts': ['angular metric', 'Tits metric', 'CAT(1) boundary', 'flat sector', 'visibility space'],
  'focus': 'Put a metric on ideal directions and use it to detect flats, splittings, and visibility '
           'behavior.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-09-tits-metric-and-visibility',
  'id': 'chapter-ii-09',
  'lab': 'Sample ray directions in Euclidean plane and in a tree model to show how angular separation '
         'changes the boundary metric.',
  'libraries': ['matplotlib', 'networkx', 'numpy'],
  'notebook': 'ii-09-tits-metric-and-visibility.ipynb',
  'number': 'II.9',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [296, 317],
  'printed_pages': [277, 298],
  'proof_strategy': 'Compare ideal angle data in a flat plane with the angle data in a negatively curved '
                    'visibility example.',
  'source_sections': ['angles in compactification',
                      'angular metric',
                      'CAT(1) boundary',
                      'Tits metric',
                      'splittings',
                      'visibility'],
  'title': 'The Tits Metric and Visibility Spaces',
  'visual_family': 'boundary'},
 {'artifact_stem': 'ii-10-symmetric-space-flats-weyl-chambers',
  'concepts': ['rank-one hyperbolic space',
               'positive definite matrix space',
               'flat',
               'Weyl chamber',
               'Iwasawa decomposition'],
  'focus': 'Use symmetric spaces as high-rank CAT(0) laboratories with flats, Weyl chambers, and '
           'building-like boundaries.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-10-symmetric-spaces',
  'id': 'chapter-ii-10',
  'lab': 'Interpolate SPD matrices along a log path and track eigenvalue ratios as coordinates in a flat.',
  'libraries': ['matplotlib', 'plotly', 'numpy'],
  'notebook': 'ii-10-symmetric-spaces.ipynb',
  'number': 'II.10',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [318, 360],
  'printed_pages': [299, 341],
  'proof_strategy': 'Represent diagonal positive-definite matrices as a flat and mark Weyl chamber walls '
                    'created by eigenvalue ordering.',
  'source_sections': ['rank-one hyperbolic spaces',
                      'P(n,R)',
                      'flats',
                      'Weyl chambers',
                      'Iwasawa decomposition',
                      'Tits boundary'],
  'title': 'Symmetric Spaces',
  'visual_family': 'symmetric'},
 {'artifact_stem': 'app-ii-10-building-apartment-chamber-atlas',
  'concepts': ['apartment', 'chamber', 'wall', 'Weyl group', 'building atlas'],
  'focus': 'Treat buildings as apartment systems where local chamber combinatorics controls global CAT '
           'geometry.',
  'folder': 'part-02-cat-k-spaces/appendix-ii-10-spherical-and-euclidean-buildings',
  'id': 'appendix-ii-10-buildings',
  'lab': 'Build a small chamber graph and compute gallery distances between selected chambers.',
  'libraries': ['matplotlib', 'networkx', 'numpy'],
  'notebook': 'appendix-ii-10-spherical-and-euclidean-buildings.ipynb',
  'number': 'II.10 Appendix',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [361, 365],
  'printed_pages': [342, 346],
  'proof_strategy': 'Draw overlapping apartments and record which chamber galleries can be folded by Weyl '
                    'symmetries.',
  'source_sections': ['apartments', 'chambers', 'Weyl group', 'spherical building', 'Euclidean building'],
  'title': 'Spherical and Euclidean Buildings',
  'visual_family': 'symmetric'},
 {'artifact_stem': 'ii-11-convex-gluing-curvature-ledger',
  'concepts': ['convex gluing',
               'local isometry gluing',
               'equivariant gluing',
               'non-locally convex seam',
               'truncated hyperbolic piece'],
  'focus': 'Track when gluing CAT(k) pieces preserves curvature and when a nonconvex seam breaks the '
           'comparison test.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-11-gluing-constructions',
  'id': 'chapter-ii-11',
  'lab': 'Glue two Euclidean half-strips along a convex segment and test whether sample geodesics cross the '
         'seam predictably.',
  'libraries': ['matplotlib', 'networkx', 'shapely'],
  'notebook': 'ii-11-gluing-constructions.ipynb',
  'number': 'II.11',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [366, 385],
  'printed_pages': [347, 366],
  'proof_strategy': 'Show a tree of pieces glued along convex subsets and contrast it with a seam where '
                    'shortest paths kink incorrectly.',
  'source_sections': ['convex gluing',
                      'local isometries',
                      'equivariant gluing',
                      'non-locally convex gluing',
                      'truncated hyperbolic spaces'],
  'title': 'Gluing Constructions',
  'visual_family': 'gluing'},
 {'artifact_stem': 'ii-12-simple-complex-of-groups-development',
  'concepts': ['stratified space',
               'strict fundamental domain',
               'simple complex of groups',
               'basic construction',
               'local development'],
  'focus': 'Encode group stabilizer data over a stratified space and test curvature through the local '
           'development.',
  'folder': 'part-02-cat-k-spaces/chapter-ii-12-simple-complexes-of-groups',
  'id': 'chapter-ii-12',
  'lab': 'Assign stabilizers to a triangle of strata and compute which inclusions must commute around a '
         'face.',
  'libraries': ['networkx', 'matplotlib', 'numpy'],
  'notebook': 'ii-12-simple-complexes-of-groups.ipynb',
  'number': 'II.12',
  'part': 'Part II',
  'part_title': 'CAT(k) Spaces',
  'pdf_pages': [386, 415],
  'printed_pages': [367, 396],
  'proof_strategy': 'Draw the base stratification, attach local groups, and unfold one vertex into its local '
                    'development.',
  'source_sections': ['stratified spaces',
                      'strict fundamental domain',
                      'simple complexes of groups',
                      'basic construction',
                      'local development',
                      'Coxeter constructions'],
  'title': 'Simple Complexes of Groups',
  'visual_family': 'category'},
 {'artifact_stem': 'iii-h-slim-triangle-boundary-isoperimetry',
  'concepts': ['delta-slim triangle',
               'quasi-geodesic stability',
               'linear isoperimetric inequality',
               'Gromov boundary',
               'visual metric'],
  'focus': 'Compare negative-curvature large-scale behavior through slim triangles, isoperimetry, and '
           'boundary metrics.',
  'folder': 'part-03-geometry-of-group-actions/chapter-iii-h-delta-hyperbolic-spaces',
  'id': 'chapter-iii-h',
  'lab': 'Compare a tree triangle and a grid triangle by measuring distance from one side to the union of '
         'the other two sides.',
  'libraries': ['matplotlib', 'networkx', 'numpy'],
  'notebook': 'iii-h-delta-hyperbolic-spaces.ipynb',
  'number': 'III.H',
  'part': 'Part III',
  'part_title': 'Aspects of the Geometry of Group Actions',
  'pdf_pages': [417, 456],
  'printed_pages': [398, 437],
  'proof_strategy': 'Use a slim triangle overlay and a coarse filling ledger to connect hyperbolicity with '
                    'linear area bounds.',
  'source_sections': ['slim triangles',
                      'quasi-geodesics',
                      'local geodesics',
                      'area inequalities',
                      'Gromov boundary'],
  'title': 'delta-Hyperbolic Spaces',
  'visual_family': 'hyperbolic'},
 {'artifact_stem': 'iii-g-group-theory-dehn-distortion-dashboard',
  'concepts': ['word problem',
               'conjugacy problem',
               'hyperbolic group',
               'semihyperbolic group',
               'subgroup distortion'],
  'focus': 'Use non-positive curvature to make group-theoretic algorithms and subgroup phenomena geometric.',
  'folder': 'part-03-geometry-of-group-actions/chapter-iii-g-non-positive-curvature-and-group-theory',
  'id': 'chapter-iii-g',
  'lab': 'Run a small Dehn-reduction toy example and compare path length before and after applying relators.',
  'libraries': ['networkx', 'matplotlib', 'numpy'],
  'notebook': 'iii-g-non-positive-curvature-and-group-theory.ipynb',
  'number': 'III.Gamma',
  'part': 'Part III',
  'part_title': 'Aspects of the Geometry of Group Actions',
  'pdf_pages': [457, 537],
  'printed_pages': [438, 518],
  'proof_strategy': 'Tie normal forms, Dehn reduction, and subgroup distortion to visible paths in '
                    'Cayley-type graphs.',
  'source_sections': ['isometries',
                      'decision problems',
                      'hyperbolic groups',
                      'semihyperbolic groups',
                      'subgroups',
                      'amalgamation',
                      'residual finiteness'],
  'title': 'Non-Positive Curvature and Group Theory',
  'visual_family': 'group'},
 {'artifact_stem': 'iii-c-scwol-complex-of-groups-covering',
  'concepts': ['scwol', 'complex of groups', 'developability', 'universal group', 'local development'],
  'focus': 'Upgrade simple complexes of groups to the full scwol language and follow fundamental groups '
           'through developments and coverings.',
  'folder': 'part-03-geometry-of-group-actions/chapter-iii-c-complexes-of-groups',
  'id': 'chapter-iii-c',
  'lab': 'Model a tiny scwol with two composable arrows and verify which edge maps compose as required.',
  'libraries': ['networkx', 'matplotlib', 'numpy'],
  'notebook': 'iii-c-complexes-of-groups.ipynb',
  'number': 'III.C',
  'part': 'Part III',
  'part_title': 'Aspects of the Geometry of Group Actions',
  'pdf_pages': [538, 591],
  'printed_pages': [519, 572],
  'proof_strategy': 'Draw the scwol, its local groups, twisting data, and the covering fibers that encode '
                    'the universal construction.',
  'source_sections': ['scwols',
                      'complexes of groups',
                      'fundamental group',
                      'universal cover',
                      'local developments',
                      'coverings'],
  'title': 'Complexes of Groups',
  'visual_family': 'category'},
 {'artifact_stem': 'app-iii-c-category-covering-monodromy',
  'concepts': ['small category',
               'category path',
               'fundamental group',
               'covering category',
               'fiber monodromy'],
  'focus': 'Make category paths, loops, and covering fibers visible enough to support the '
           'complexes-of-groups chapter.',
  'folder': 'part-03-geometry-of-group-actions/appendix-iii-c-small-categories-coverings',
  'id': 'appendix-iii-c-small-categories-coverings',
  'lab': 'Lift a loop in a two-object category cover and compute the induced permutation of the fiber.',
  'libraries': ['networkx', 'matplotlib', 'numpy'],
  'notebook': 'appendix-iii-c-small-categories-coverings.ipynb',
  'number': 'III.C Appendix',
  'part': 'Part III',
  'part_title': 'Aspects of the Geometry of Group Actions',
  'pdf_pages': [592, 602],
  'printed_pages': [573, 583],
  'proof_strategy': 'Use a directed covering diagram and lift a closed category path to read monodromy on '
                    'the fiber.',
  'source_sections': ['basic definitions',
                      'fundamental group',
                      'covering of a category',
                      'relationship with complexes of groups'],
  'title': 'Fundamental Groups and Coverings of Small Categories',
  'visual_family': 'category'},
 {'artifact_stem': 'iii-q-local-isometry-groupoid-covering',
  'concepts': ['orbifold chart',
               'etale groupoid',
               'groupoid equivalence',
               'groupoid fundamental group',
               'geodesic lift'],
  'focus': 'Use groupoids to encode local isometries, orbifold charts, and developability through lifted '
           'geodesics.',
  'folder': 'part-03-geometry-of-group-actions/chapter-iii-q-groupoids-of-local-isometries',
  'id': 'chapter-iii-q',
  'lab': 'Create a small atlas of overlapping intervals and record the partial isometries as a groupoid '
         'action graph.',
  'libraries': ['networkx', 'matplotlib', 'numpy'],
  'notebook': 'iii-q-groupoids-of-local-isometries.ipynb',
  'number': 'III.Q',
  'part': 'Part III',
  'part_title': 'Aspects of the Geometry of Group Actions',
  'pdf_pages': [603, 638],
  'printed_pages': [584, 619],
  'proof_strategy': 'Draw local charts as objects, local isometries as arrows, and the lifted geodesic space '
                    'used in the main theorem.',
  'source_sections': ['orbifolds',
                      'etale groupoids',
                      'equivalences',
                      'fundamental group',
                      'coverings',
                      'geodesic proof'],
  'title': 'Groupoids of Local Isometries',
  'visual_family': 'category'}]
UNIT_BY_ID = {unit["id"]: unit for unit in UNITS}

def unit_by_id(unit_id: str) -> dict:
    return UNIT_BY_ID[unit_id]

def canonical_notebook_path(unit: dict) -> Path:
    return BOOK_ROOT / unit["folder"] / unit["notebook"]

def index_notebook_path(unit: dict) -> Path:
    return BOOK_ROOT / unit["folder"] / "00-index.ipynb"

def artifact_root(unit: dict) -> Path:
    return BOOK_ROOT / "artifacts" / unit["id"]

def part_units(part: str) -> list[dict]:
    return [unit for unit in UNITS if unit["part"] == part]
