"""Source inventory for the contact topology standalone notebook course."""

from __future__ import annotations

from typing import Any

PDF_SOURCE = "An Introduction to Contact Topology.pdf"
SOURCE_SPAN_NOTES = [
    "The PDF is text-extractable; printed page 1 starts at physical PDF page 19.",
    "For main-matter printed pages, add 18 to get the physical PDF page.",
    "The PDF is used for source orientation only; notebooks use original prose, examples, code, and generated artifacts.",
]

ENTRIES: list[dict[str, Any]] = [
    {
        "id": "chapter-01",
        "kind": "chapter",
        "label": "Chapter 1",
        "number": 1,
        "title": "Facets of Contact Geometry",
        "folder": "chapter-01-facets-of-contact-geometry",
        "notebook": "01-facets-of-contact-geometry.ipynb",
        "artifact": "chapter-01",
        "printed_span": "1-50",
        "pdf_span": "19-68",
        "sections": "contact structures, Reeb fields, contact elements, symplectic linear algebra, mechanics, geodesic flow, order of contact, topology applications",
        "focus": "Turns the opening survey into a laboratory for contact planes, Reeb directions, contact elements, and Legendre-style transformations.",
        "topics": [
            "Contact condition alpha wedge (d alpha)^n as a volume test",
            "Reeb vector fields as the direction left by d alpha",
            "Spaces of contact elements and first-order differential equations",
            "Classical mechanics, geodesic flow, and order of contact as contact-geometric examples",
        ],
        "lab": "Modify the coefficient in dz + lambda x dy and watch integrability, contact volume, and Reeb direction respond.",
    },
    {
        "id": "chapter-02",
        "kind": "chapter",
        "label": "Chapter 2",
        "number": 2,
        "title": "Contact Manifolds",
        "folder": "chapter-02-contact-manifolds",
        "notebook": "02-contact-manifolds.ipynb",
        "artifact": "chapter-02",
        "printed_span": "51-92",
        "pdf_span": "69-110",
        "sections": "examples, Gray stability, Moser trick, contact Hamiltonians, symplectic bundles, Darboux, neighbourhood and isotopy extension theorems",
        "focus": "Builds the local and deformation toolkit: examples, flows that preserve contact data, Darboux normal form, and neighborhood models.",
        "topics": [
            "Families of contact forms and Gray stability",
            "Moser vector fields and contact Hamiltonians",
            "Darboux charts as local normal coordinates",
            "Isotropic, contact, and hypersurface neighborhood behavior",
        ],
        "lab": "Choose a small Hamiltonian in standard R3 and verify the contact Hamiltonian equations by symbolic and sampled flow checks.",
    },
    {
        "id": "chapter-03",
        "kind": "chapter",
        "label": "Chapter 3",
        "number": 3,
        "title": "Knots in Contact 3-Manifolds",
        "folder": "chapter-03-knots-in-contact-3-manifolds",
        "notebook": "03-knots-in-contact-3-manifolds.ipynb",
        "artifact": "chapter-03",
        "printed_span": "93-129",
        "pdf_span": "111-147",
        "sections": "Legendrian and transverse knots, front and Lagrangian projection, approximation theorems, submanifold topology, linking numbers, classical invariants",
        "focus": "Makes Legendrian and transverse knot data visible through fronts, projections, linking, and the classical tb/rotation/self-linking invariants.",
        "topics": [
            "Legendrian versus transverse tangency conditions",
            "Front projection rules: slopes, cusps, and crossings",
            "Linking numbers and push-offs",
            "Thurston-Bennequin, rotation, and self-linking invariants",
        ],
        "lab": "Change the crossing and cusp counts of a front diagram and recompute the classical invariants.",
    },
    {
        "id": "chapter-04",
        "kind": "chapter",
        "label": "Chapter 4",
        "number": 4,
        "title": "Contact Structures on 3-Manifolds",
        "folder": "chapter-04-contact-structures-on-3-manifolds",
        "notebook": "04-contact-structures-on-3-manifolds.ipynb",
        "artifact": "chapter-04",
        "printed_span": "130-267",
        "pdf_span": "148-285",
        "sections": "Martinet construction, plane fields, Lutz twist, open books, tight/overtwisted, characteristic foliations, convex surfaces, elimination, genus bounds, Bennequin inequality, overtwisted classification, tomography, tight classification, Cerf theorem, prime decomposition",
        "focus": "Organizes the large 3-dimensional chapter around visible plane-field moves, surface foliations, dividing sets, overtwisted disks, and classification logic.",
        "topics": [
            "Plane-field homotopy data and contact realization",
            "Lutz twists and overtwisted disks",
            "Characteristic foliations and convex-surface dividing sets",
            "Bennequin inequality, tomography, and classification dependencies",
        ],
        "lab": "Sample a characteristic foliation on a surface, locate singularities, and compare the dividing-set sketch with an inequality check.",
    },
    {
        "id": "chapter-05",
        "kind": "chapter",
        "label": "Chapter 5",
        "number": 5,
        "title": "Symplectic Fillings and Convexity",
        "folder": "chapter-05-symplectic-fillings-and-convexity",
        "notebook": "05-symplectic-fillings-and-convexity.ipynb",
        "artifact": "chapter-05",
        "printed_span": "268-285",
        "pdf_span": "286-303",
        "sections": "weak versus strong fillings, symplectic cobordisms, convexity and Levi pseudoconvexity, Levi pseudoconvexity and omega-convexity",
        "focus": "Connects contact boundaries to symplectic interiors, Liouville collars, cobordism arrows, and Levi positivity.",
        "topics": [
            "Strong and weak filling conditions",
            "Symplectic cobordisms as directed boundary data",
            "Liouville vector fields and convex boundary orientation",
            "Levi pseudoconvexity compared with omega-convexity",
        ],
        "lab": "Test candidate boundary forms by checking Liouville transversality and a model Levi-form positivity computation.",
    },
    {
        "id": "chapter-06",
        "kind": "chapter",
        "label": "Chapter 6",
        "number": 6,
        "title": "Contact Surgery",
        "folder": "chapter-06-contact-surgery",
        "notebook": "06-contact-surgery.ipynb",
        "artifact": "chapter-06",
        "printed_span": "286-331",
        "pdf_span": "304-349",
        "sections": "topological surgery, contact surgery and symplectic cobordisms, framings, h-principle for isotropic immersions, Whitney-Graustein theorem, contact Dehn surgery, symplectic fillings",
        "focus": "Treats surgery as controlled replacement data: framings, handles, Legendrian coefficients, Dehn slopes, and filling consequences.",
        "topics": [
            "Topological surgery as remove-and-reglue bookkeeping",
            "Contact framing versus topological framing",
            "Whitney-Graustein rotation number as an immersion invariant",
            "Contact Dehn surgery and symplectic filling applications",
        ],
        "lab": "Convert between contact and topological surgery coefficients and verify a sampled rotation number for immersed curves.",
    },
    {
        "id": "chapter-07",
        "kind": "chapter",
        "label": "Chapter 7",
        "number": 7,
        "title": "Further Constructions of Contact Manifolds",
        "folder": "chapter-07-further-constructions-of-contact-manifolds",
        "notebook": "07-further-constructions-of-contact-manifolds.ipynb",
        "artifact": "chapter-07",
        "printed_span": "332-365",
        "pdf_span": "350-383",
        "sections": "Brieskorn manifolds, Boothby-Wang construction, open books, fibre connected sum, branched covers, plumbing, contact reduction",
        "focus": "Compares construction recipes that manufacture contact manifolds from algebraic links, circle bundles, open books, sums, covers, plumbing, and reduction.",
        "topics": [
            "Brieskorn links as level-set contact examples",
            "Boothby-Wang circle bundles over symplectic bases",
            "Open books as page-monodromy contact carriers",
            "Plumbing and reduction as graph or quotient constructions",
        ],
        "lab": "Build a small plumbing graph and inspect its intersection matrix while comparing it with an open-book page sketch.",
    },
    {
        "id": "chapter-08",
        "kind": "chapter",
        "label": "Chapter 8",
        "number": 8,
        "title": "Contact Structures on 5-Manifolds",
        "folder": "chapter-08-contact-structures-on-5-manifolds",
        "notebook": "08-contact-structures-on-5-manifolds.ipynb",
        "artifact": "chapter-08",
        "printed_span": "366-400",
        "pdf_span": "384-418",
        "sections": "almost contact structures, structure of 5-manifolds, existence of contact structures",
        "focus": "Turns the surgery and obstruction-theory application into computable bookkeeping for almost contact data and simply connected 5-manifold decompositions.",
        "topics": [
            "Almost contact structures as reductions of tangent-bundle structure",
            "Second Stiefel-Whitney and W3 obstructions",
            "Barden-style 5-manifold decomposition data",
            "Existence of contact structures via surgery machinery",
        ],
        "lab": "Feed in H2 rank, torsion labels, and w2 status to predict the visible connected-sum part of the 5-manifold.",
    },
    {
        "id": "appendix-a",
        "kind": "appendix",
        "label": "Appendix A",
        "number": 9,
        "title": "The Generalised Poincare Lemma",
        "folder": "appendix-a-generalised-poincare-lemma",
        "notebook": "appendix-a-generalised-poincare-lemma.ipynb",
        "artifact": "appendix-a",
        "printed_span": "401-403",
        "pdf_span": "419-421",
        "sections": "relative homotopy operator for differential forms near a submanifold",
        "focus": "Makes the homotopy-operator proof visible as radial contraction plus an exactness check for closed forms.",
        "topics": [
            "Retraction onto a base submanifold",
            "Homotopy operator for differential forms",
            "Closed forms that vanish along the base",
            "Relative primitive construction",
        ],
        "lab": "Choose a simple closed polynomial 1-form on a collar and recover a primitive by integrating along the contraction parameter.",
    },
    {
        "id": "appendix-b",
        "kind": "appendix",
        "label": "Appendix B",
        "number": 10,
        "title": "Time-Dependent Vector Fields",
        "folder": "appendix-b-time-dependent-vector-fields",
        "notebook": "appendix-b-time-dependent-vector-fields.ipynb",
        "artifact": "appendix-b",
        "printed_span": "404-407",
        "pdf_span": "422-425",
        "sections": "flows of time-dependent vector fields and formulas for pullbacks and Lie derivatives",
        "focus": "Supplies the calculus used by Moser and Gray arguments: evolving flows, pullbacks, and Lie derivative identities.",
        "topics": [
            "Time-dependent vector fields and non-autonomous flows",
            "Pullback differentiation along a flow",
            "Lie derivative identities for functions and forms",
            "Numerical flow sanity checks",
        ],
        "lab": "Integrate a rotating linear vector field and compare finite-difference pullback change with the Lie-derivative prediction.",
    },
]

BACK_MATTER: list[dict[str, str]] = [
    {"title": "Contents", "printed_span": "vii-ix", "pdf_span": "9-11"},
    {"title": "Preface", "printed_span": "x-xvi", "pdf_span": "12-18"},
    {"title": "References", "printed_span": "408-418", "pdf_span": "426-436"},
    {"title": "Notation index", "printed_span": "419-425", "pdf_span": "437-443"},
    {"title": "Author index", "printed_span": "426-428", "pdf_span": "444-446"},
    {"title": "Subject index", "printed_span": "429-440", "pdf_span": "447-458"},
]


def source_map() -> dict[str, Any]:
    return {
        "pdf_source": PDF_SOURCE,
        "source_span_notes": SOURCE_SPAN_NOTES,
        "entries": ENTRIES,
        "back_matter": BACK_MATTER,
    }
