"""Chapter 8 helpers for geometric differentiation notebooks.

The functions here intentionally stay small and explicit. They wrap the
dictionary-backed geometric algebra in ``utils.ga`` with the differential
experiments used by the Chapter 8 notebook.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable

import numpy as np

from utils.ga import Algebra, Multivector, unit_rotor

EPS = 1e-10
E2 = Algebra([1, 1], names=["e1", "e2"])
E3 = Algebra([1, 1, 1], names=["e1", "e2", "e3"])


def coords_to_vector(coordinates: Iterable[float], algebra: Algebra = E3) -> Multivector:
    """Create a grade-1 multivector from coordinates."""
    return algebra.vector(coordinates)


def vector_to_coords(vector: Multivector) -> np.ndarray:
    """Return coordinates of a pure vector."""
    return vector.grade(1).coordinates()


def vector_inverse(vector: Multivector) -> Multivector:
    """Return the geometric inverse of a non-null vector."""
    denominator = vector.gp(vector).scalar_value()
    if abs(denominator) < EPS:
        raise ZeroDivisionError(f"vector is not invertible: {vector!r}")
    return vector / denominator


def commutator(left: Multivector, right: Multivector) -> Multivector:
    """Return the commutator product ``0.5 * (left right - right left)``."""
    return 0.5 * (left.gp(right) - right.gp(left))


def jacobi_residual(a: Multivector, b: Multivector, c: Multivector) -> Multivector:
    """Return the Jacobi sum for the commutator product."""
    return commutator(commutator(a, b), c) + commutator(commutator(c, a), b) + commutator(
        commutator(b, c), a
    )


def rotor_transform(multivector: Multivector, plane_bivector: Multivector, angle: float) -> Multivector:
    """Apply the rotor generated by ``plane_bivector`` through ``angle`` radians."""
    rotor = unit_rotor(plane_bivector, angle)
    return multivector.sandwich(rotor)


def first_order_rotor_change(
    multivector: Multivector,
    plane_bivector: Multivector,
    small_angle: float,
) -> Multivector:
    """Return the first-order commutator approximation to a small rotor action."""
    return multivector + small_angle * commutator(multivector, plane_bivector)


def scalar_central_difference(
    function: Callable[[float], Multivector],
    t: float,
    *,
    h: float = 1e-6,
) -> Multivector:
    """Central difference for a scalar-parameter multivector function."""
    return (function(t + h) - function(t - h)) / (2.0 * h)


def directional_derivative(
    function: Callable[[Multivector], Multivector],
    point: Multivector,
    direction: Multivector,
    *,
    h: float = 1e-6,
) -> Multivector:
    """Central finite-difference directional derivative along a multivector line."""
    return (function(point + h * direction) - function(point - h * direction)) / (2.0 * h)


def vector_derivative(
    function: Callable[[Multivector], Multivector],
    point: Multivector,
    *,
    h: float = 1e-6,
) -> Multivector:
    """Return ``sum_i e_i (e_i * partial_x) F`` in an orthonormal Euclidean algebra."""
    algebra = point.algebra
    total = algebra.scalar(0)
    for basis_vector in algebra.basis():
        total = total + basis_vector.gp(
            directional_derivative(function, point, basis_vector, h=h)
        )
    return total


def vector_inverse_derivative(point: Multivector, direction: Multivector) -> Multivector:
    """Analytic directional derivative of ``x^{-1}`` in the full vector space."""
    inverse = vector_inverse(point)
    return -inverse.gp(direction).gp(inverse)


def reflect_vector_in_plane(vector: Multivector, normal: Multivector) -> Multivector:
    """Reflect a vector in the mirror plane with the supplied normal vector."""
    return (-normal.gp(vector).gp(vector_inverse(normal))).grade(1)


def mirror_tilt_derivative(
    vector: Multivector,
    normal: Multivector,
    normal_change: Multivector,
) -> Multivector:
    """Directional derivative of a mirror reflection as its normal changes."""
    reflected = reflect_vector_in_plane(vector, normal)
    bivector_change = 2.0 * vector_inverse(normal).wedge(normal_change)
    return commutator(reflected, bivector_change).grade(1)


def spherical_projection(vector: Multivector) -> Multivector:
    """Project a nonzero vector to the unit sphere."""
    radius = vector.norm()
    if radius < EPS:
        raise ZeroDivisionError("cannot project the zero vector onto the unit sphere")
    return vector / radius


def spherical_projection_derivative(
    point: Multivector,
    direction: Multivector,
) -> Multivector:
    """Directional derivative of ``x -> x / ||x||``."""
    tangent_component = direction.wedge(point).gp(vector_inverse(point)).grade(1)
    return tangent_component / point.norm()


def basis_blade_table(algebra: Algebra = E3) -> list[dict[str, int | str]]:
    """Return basis blades with mask, grade, and display name."""
    rows: list[dict[str, int | str]] = []
    for mask in range(1 << algebra.dimension):
        rows.append({"mask": mask, "grade": algebra.grade(mask), "blade": algebra.basis_name(mask)})
    return rows


def multivector_from_coefficients(
    coefficients: Iterable[float],
    algebra: Algebra = E3,
) -> Multivector:
    """Create a multivector from coefficients ordered by basis-blade mask."""
    terms = {
        mask: float(value)
        for mask, value in enumerate(coefficients)
        if abs(float(value)) > EPS
    }
    return Multivector(algebra, terms)


def coefficient_vector(multivector: Multivector) -> np.ndarray:
    """Return coefficients ordered by basis-blade mask."""
    return np.array(
        [multivector.terms.get(mask, 0.0) for mask in range(1 << multivector.algebra.dimension)]
    )


def scalar_norm_squared(vector: Multivector) -> Multivector:
    """Return ``x^2`` as a scalar multivector for Euclidean vectors."""
    return vector.gp(vector).grade(0)
