"""Canonical inventory for the robotics manipulation notebook course."""

PARTS = [
    {
        "folder": "part-01-foundations-and-single-robot-manipulation",
        "title": "Part I: Foundations and Single-Robot Manipulation",
        "description": "Rigid motion, serial manipulator kinematics, dynamics, and feedback control.",
    },
    {
        "folder": "part-02-multifingered-manipulation",
        "title": "Part II: Multifingered Manipulation",
        "description": "Contact, grasp maps, force closure, rolling contact, hand dynamics, and tendon actuation.",
    },
    {
        "folder": "part-03-nonholonomic-systems",
        "title": "Part III: Nonholonomic Systems",
        "description": "Distributions, Lie brackets, controllability, steering, chained forms, and geometric phase.",
    },
    {
        "folder": "part-04-outlook-and-appendices",
        "title": "Part IV: Outlook and Appendices",
        "description": "Applications outlook, Lie-group foundations, and a Python screw-calculus reference.",
    },
]


ENTRIES = [
    {
        "kind": "chapter",
        "number": 1,
        "label": "Chapter 01",
        "title": "Introduction",
        "part": "part-01-foundations-and-single-robot-manipulation",
        "folder": "chapter-01-introduction",
        "notebook": "01-introduction.ipynb",
        "printed": "1-18",
        "pdf": "19-36",
        "artifact": "chapter-01",
        "focus": "robotics history, manipulation taxonomy, course dependency map, degrees of freedom",
        "question": "What geometry must a manipulation course make operational?",
        "visuals": [
            ("timeline", "manipulation-timeline.png", "abstract robotics timeline"),
            ("taxonomy", "manipulator-taxonomy.png", "machine families as geometry"),
            ("dependency", "course-dependency-map.png", "how later chapters depend on rigid motion"),
        ],
        "lab": "Build a small dependency graph for a new robotics project and check that every claimed skill has a mathematical predecessor.",
        "compute": "intro",
    },
    {
        "kind": "chapter",
        "number": 2,
        "label": "Chapter 02",
        "title": "Rigid Body Motion",
        "part": "part-01-foundations-and-single-robot-manipulation",
        "folder": "chapter-02-rigid-body-motion",
        "notebook": "02-rigid-body-motion.ipynb",
        "printed": "19-80",
        "pdf": "37-98",
        "artifact": "chapter-02",
        "focus": "SO(3), SE(3), homogeneous transforms, twists, screws, wrenches, reciprocal screws",
        "question": "How can rigid motion be represented so coordinates change but geometry does not?",
        "visuals": [
            ("frames", "rigid-transform-frame-lab.png", "distance-preserving moving frames"),
            ("screw", "screw-motion-explorer.png", "axis, pitch, and helical point path"),
            ("wrench", "wrench-twist-duality.png", "instantaneous power pairing"),
        ],
        "lab": "Move the same twist through three frames and confirm that the wrench pairing is invariant.",
        "compute": "lie",
    },
    {
        "kind": "chapter",
        "number": 3,
        "label": "Chapter 03",
        "title": "Manipulator Kinematics",
        "part": "part-01-foundations-and-single-robot-manipulation",
        "folder": "chapter-03-manipulator-kinematics",
        "notebook": "03-manipulator-kinematics.ipynb",
        "printed": "81-154",
        "pdf": "99-172",
        "artifact": "chapter-03",
        "focus": "product of exponentials, inverse kinematics, Jacobians, singularities, manipulability",
        "question": "How do joint screws assemble into end-effector motion and force transmission?",
        "visuals": [
            ("manipulator", "product-of-exponentials-builder.png", "joint screws accumulate into a tool pose"),
            ("workspace", "workspace-and-manipulability.png", "reachable set and velocity ellipsoid"),
            ("singularity", "jacobian-singularity-gallery.png", "rank loss as geometry collapses"),
        ],
        "lab": "Sample a planar arm workspace and compare its best-conditioned and worst-conditioned poses.",
        "compute": "robot",
    },
    {
        "kind": "chapter",
        "number": 4,
        "label": "Chapter 04",
        "title": "Robot Dynamics and Control",
        "part": "part-01-foundations-and-single-robot-manipulation",
        "folder": "chapter-04-robot-dynamics-and-control",
        "notebook": "04-robot-dynamics-and-control.ipynb",
        "printed": "155-210",
        "pdf": "173-228",
        "artifact": "chapter-04",
        "focus": "Lagrangian dynamics, open-chain structure, Lyapunov stability, tracking, constrained control",
        "question": "How do energy, inertia, and feedback turn kinematics into controlled motion?",
        "visuals": [
            ("dynamics", "two-link-inertia-coupling.png", "configuration-dependent inertia"),
            ("phase", "lyapunov-phase-portraits.png", "energy level sets and convergence"),
            ("control", "tracking-controller-comparison.png", "computed torque versus PD response"),
        ],
        "lab": "Simulate a two-link tracking task and check both energy structure and error decay.",
        "compute": "dynamics",
    },
    {
        "kind": "chapter",
        "number": 5,
        "label": "Chapter 05",
        "title": "Multifingered Hand Kinematics",
        "part": "part-02-multifingered-manipulation",
        "folder": "chapter-05-multifingered-hand-kinematics",
        "notebook": "05-multifingered-hand-kinematics.ipynb",
        "printed": "211-264",
        "pdf": "229-282",
        "artifact": "chapter-05",
        "focus": "contacts, grasp maps, force closure, grasp planning, rolling contact",
        "question": "How do local contact forces become object-level motion and wrench capability?",
        "visuals": [
            ("cone", "contact-model-gallery.png", "friction cones and contact wrench directions"),
            ("grasp", "grasp-map-wrench-space.png", "contact columns summing to object wrench"),
            ("closure", "force-closure-convex-test.png", "origin containment in wrench space"),
        ],
        "lab": "Move frictional contacts around a polygon and watch the closure margin change.",
        "compute": "grasp",
    },
    {
        "kind": "chapter",
        "number": 6,
        "label": "Chapter 06",
        "title": "Hand Dynamics and Control",
        "part": "part-02-multifingered-manipulation",
        "folder": "chapter-06-hand-dynamics-and-control",
        "notebook": "06-hand-dynamics-and-control.ipynb",
        "printed": "265-316",
        "pdf": "283-334",
        "artifact": "chapter-06",
        "focus": "Pfaffian constraints, d'Alembert projection, internal forces, tendon actuation, hierarchy",
        "question": "How do constrained fingers control an object without fighting their own contacts?",
        "visuals": [
            ("constraint", "pfaffian-constraint-types.png", "velocity planes and forbidden directions"),
            ("internal", "internal-force-nullspace.png", "squeeze forces invisible to object motion"),
            ("tendon", "tendon-actuation-feasibility.png", "pull-only tendons and torque cones"),
        ],
        "lab": "Separate object wrench from internal squeeze and check tendon tension feasibility.",
        "compute": "hand",
    },
    {
        "kind": "chapter",
        "number": 7,
        "label": "Chapter 07",
        "title": "Nonholonomic Behavior in Robotic Systems",
        "part": "part-03-nonholonomic-systems",
        "folder": "chapter-07-nonholonomic-behavior-in-robotic-systems",
        "notebook": "07-nonholonomic-behavior-in-robotic-systems.ipynb",
        "printed": "317-354",
        "pdf": "335-372",
        "artifact": "chapter-07",
        "focus": "Pfaffian distributions, Lie brackets, Frobenius theorem, controllability, Hall bases",
        "question": "When do forbidden instantaneous motions become possible through motion sequences?",
        "visuals": [
            ("distribution", "pfaffian-distribution-view.png", "nullspaces of one-forms"),
            ("bracket", "lie-bracket-flow-square.png", "second-order drift from commutators"),
            ("growth", "growth-vector-dashboard.png", "rank expansion through brackets"),
        ],
        "lab": "Run a bracket square and fit the drift order as the loop size shrinks.",
        "compute": "nonholonomic",
    },
    {
        "kind": "chapter",
        "number": 8,
        "label": "Chapter 08",
        "title": "Nonholonomic Motion Planning",
        "part": "part-03-nonholonomic-systems",
        "folder": "chapter-08-nonholonomic-motion-planning",
        "notebook": "08-nonholonomic-motion-planning.ipynb",
        "printed": "355-394",
        "pdf": "373-412",
        "artifact": "chapter-08",
        "focus": "sinusoidal steering, chained forms, optimal steering, BCH words, dynamic finger repositioning",
        "question": "How can Lie-bracket controllability be converted into actual steering commands?",
        "visuals": [
            ("steering", "brockett-sinusoidal-steering.png", "area in controls creates bracket motion"),
            ("chained", "chained-form-harmonics.png", "harmonics rectify higher coordinates"),
            ("geometric_phase", "geometric-phase-fingertip.png", "rolling loop accumulates orientation"),
        ],
        "lab": "Steer Brockett's system with a sinusoidal loop and compare the endpoint with signed area.",
        "compute": "steering",
    },
    {
        "kind": "chapter",
        "number": 9,
        "label": "Chapter 09",
        "title": "Future Prospects",
        "part": "part-04-outlook-and-appendices",
        "folder": "chapter-09-future-prospects",
        "notebook": "09-future-prospects.ipynb",
        "printed": "395-402",
        "pdf": "413-420",
        "artifact": "chapter-09",
        "focus": "hazardous environments, surgery, microrobotics, scale laws, teleoperation latency",
        "question": "How do the book's mathematical tools survive changes in scale, risk, and application?",
        "visuals": [
            ("scale", "robotics-scale-law-panel.png", "surface, volume, and actuation trends"),
            ("latency", "teleoperation-latency-loop.png", "delay and closed-loop response"),
            ("surgery", "remote-center-surgery-kinematics.png", "port fulcrum and lost degrees of freedom"),
        ],
        "lab": "Compare a macro arm and a micro mechanism with dimensionless scale-law ratios.",
        "compute": "outlook",
    },
    {
        "kind": "appendix",
        "number": "A",
        "label": "Appendix A",
        "title": "Lie Groups and Robot Kinematics",
        "part": "part-04-outlook-and-appendices",
        "folder": "appendix-a-lie-groups-and-robot-kinematics",
        "notebook": "appendix-a-lie-groups-and-robot-kinematics.ipynb",
        "printed": "403-434",
        "pdf": "421-452",
        "artifact": "appendix-a",
        "focus": "manifolds, Lie groups, Lie algebras, SE(3), adjoints, invariant volume",
        "question": "What Lie-group facts explain the coordinate rules used throughout the course?",
        "visuals": [
            ("lie", "manifold-chart-tangent-view.png", "charts, tangent vectors, and covectors"),
            ("screw", "se3-exponential-screw-reference.png", "twist exponential and helical path"),
            ("adjoint", "adjoint-coadjoint-power-invariance.png", "twist and wrench transformations"),
        ],
        "lab": "Translate a twist and wrench through a displaced frame and verify invariant power.",
        "compute": "appendix_a",
    },
    {
        "kind": "appendix",
        "number": "B",
        "label": "Appendix B",
        "title": "A Mathematica Package for Screw Calculus",
        "part": "part-04-outlook-and-appendices",
        "folder": "appendix-b-a-mathematica-package-for-screw-calculus",
        "notebook": "appendix-b-a-mathematica-package-for-screw-calculus.ipynb",
        "printed": "435-440",
        "pdf": "453-458",
        "artifact": "appendix-b",
        "focus": "Python screw-calculus equivalents for the historical Mathematica API",
        "question": "How can the historical screw-calculus package become an executable Python reference?",
        "visuals": [
            ("api", "screw-calculus-api-map.png", "Mathematica-style ideas mapped to Python helpers"),
            ("frames", "homogeneous-point-vector-demo.png", "points translate while vectors do not"),
            ("manipulator", "scara-poe-reference.png", "twists to forward kinematics and Jacobian"),
        ],
        "lab": "Rebuild a SCARA forward kinematics calculation with the Python helpers in this course.",
        "compute": "appendix_b",
    },
]
