"""Course inventory for the MFGDL notebooks."""
from __future__ import annotations
from pathlib import Path

BOOK_ROOT = Path(__file__).resolve().parents[1]
ENTRIES = [{'chapter': 1, 'title': 'Algebraic Structures and Mathematics before Numbers', 'short': 'Algebraic Structures', 'folder': 'chapter-01-algebraic-structures', 'notebook': '01-algebraic-structures.ipynb', 'printed': '4-19', 'pdf': '4-19', 'artifact': 'chapter-01', 'visual_spine': 'sets, maps, power sets, Cartesian products, finite groups, Cayley graphs, actions, invariance/equivariance, tensor notation, einsum checks'}, {'chapter': 2, 'title': 'Geometric and Analytical Structures', 'short': 'Geometric and Analytical Structures', 'folder': 'chapter-02-geometric-analytical-structures', 'notebook': '02-geometric-analytical-structures.ipynb', 'printed': '20-25', 'pdf': '20-25', 'artifact': 'chapter-02', 'visual_spine': 'norm balls, induced metrics, pseudometric/quasi-metric examples, Hausdorff distance, proximity graphs, projections, Gram-Schmidt, attention scaling'}, {'chapter': 3, 'title': 'Vector Calculus', 'short': 'Vector Calculus', 'folder': 'chapter-03-vector-calculus', 'notebook': '03-vector-calculus.ipynb', 'printed': '26-36', 'pdf': '26-36', 'artifact': 'chapter-03', 'visual_spine': 'Lipschitz/smoothness gallery, scalar/vector fields, gradients, Jacobians, integrals, divergence/flux, Laplacian, loss landscapes, backprop graph'}, {'chapter': 4, 'title': 'Topological Foundations and Differential Geometry', 'short': 'Topology and Differential Geometry', 'folder': 'chapter-04-topology-differential-geometry', 'notebook': '04-topology-differential-geometry.ipynb', 'printed': '37-50', 'pdf': '37-50', 'artifact': 'chapter-04', 'visual_spine': 'open sets, continuity via preimages, homeomorphism/homotopy, Euler characteristic, geodesics, charts, tangent spaces, exp/log maps, gauges, manifold hypothesis'}, {'chapter': 5, 'title': 'Functional Analysis', 'short': 'Functional Analysis', 'folder': 'chapter-05-functional-analysis', 'notebook': '05-functional-analysis.ipynb', 'printed': '51-54', 'pdf': '51-54', 'artifact': 'chapter-05', 'visual_spine': 'Cauchy sequences, completeness gaps, Banach/Hilbert geometry, function bases, orthonormal reconstruction, operators, adjoints, functionals'}, {'chapter': 6, 'title': 'Spectral Theory', 'short': 'Spectral Theory', 'folder': 'chapter-06-spectral-theory', 'notebook': '06-spectral-theory.ipynb', 'printed': '55-64', 'pdf': '55-64', 'artifact': 'chapter-06', 'visual_spine': 'eigen-directions, self-adjoint spectra, Laplacian eigenfunctions, Fourier Gram matrices, SVD, Parseval, heat flow, graph Laplacian bridge'}, {'chapter': 7, 'title': 'Graph Theory', 'short': 'Graph Theory', 'folder': 'chapter-07-graph-theory', 'notebook': '07-graph-theory.ipynb', 'printed': '65-77', 'pdf': '65-77', 'artifact': 'chapter-07', 'visual_spine': 'graph anatomy, adjacency/degree matrices, graph distances, graph families, geometric graphs, homophily, permutations, homomorphisms, Laplacians, graph Fourier modes, message passing'}]

def chapter_topic(chapter: int) -> str:
    return f"chapter-{chapter:02d}"

def canonical_path(entry: dict[str, object]) -> Path:
    return BOOK_ROOT / str(entry["folder"]) / str(entry["notebook"])
