"""Inventory for the Information Geometry and Its Applications notebook course."""

from __future__ import annotations

PARTS = [
    {
        "folder": "part-01-geometry-of-divergence-functions",
        "title": "Part I: Geometry of Divergence Functions: Dually Flat Riemannian Structure",
        "description": "Divergence functions, Bregman geometry, probability families, invariant metrics, alpha geometry, entropy, and matrix-valued extensions.",
    },
    {
        "folder": "part-02-dual-differential-geometry",
        "title": "Part II: Introduction to Dual Differential Geometry",
        "description": "Differential-geometric foundations and their dual-connection specialization for information manifolds.",
    },
    {
        "folder": "part-03-statistical-inference",
        "title": "Part III: Information Geometry of Statistical Inference",
        "description": "Asymptotic inference, hidden-variable estimation, semiparametric models, and time-series manifolds.",
    },
    {
        "folder": "part-04-applications-of-information-geometry",
        "title": "Part IV: Applications of Information Geometry",
        "description": "Machine learning, natural gradient dynamics, signal processing, optimization, and game-score geometry.",
    },
]

ENTRIES = [
    {
        "kind": "chapter",
        "number": 1,
        "label": "Chapter 01",
        "title": "Manifold, Divergence and Dually Flat Structure",
        "folder": "chapter-01-manifold-divergence-dually-flat-structure",
        "notebook": "01-manifold-divergence-dually-flat-structure.ipynb",
        "part": "part-01-geometry-of-divergence-functions",
        "topic": "chapter-01",
        "family": "dually-flat",
        "printed": "3-30",
        "pdf": "20-47",
        "focus": "Manifolds, asymmetric divergence, Bregman geometry, Legendre duality, affine coordinates, and generalized Pythagorean projection.",
        "concepts": [
            "a coordinate chart is a computational handle, not the manifold itself",
            "a divergence compares two points without requiring symmetry",
            "a convex potential creates dual coordinates through the Legendre transform",
            "orthogonal e- and m-projections turn the Pythagorean theorem into an algorithm",
        ],
        "visuals": [
            "probability-simplex chart comparing e-geodesics and m-geodesics",
            "Bregman tangent-plane gap animation",
            "dual-coordinate grid over a convex potential",
            "alternating projection path with divergence values annotated",
        ],
        "checks": [
            "Bregman divergence is non-negative and zero at identical points",
            "Legendre gradients invert on the plotted convex potential",
            "m-geodesic probabilities stay normalized",
            "Pythagorean residual is small for the constructed orthogonal projection",
        ],
    },
    {
        "kind": "chapter",
        "number": 2,
        "label": "Chapter 02",
        "title": "Exponential Families and Mixture Families of Probability Distributions",
        "folder": "chapter-02-exponential-and-mixture-families",
        "notebook": "02-exponential-and-mixture-families.ipynb",
        "part": "part-01-geometry-of-divergence-functions",
        "topic": "chapter-02",
        "family": "dually-flat",
        "printed": "31-50",
        "pdf": "48-67",
        "focus": "Exponential and mixture families, e-flat and m-flat structures, maximum entropy, mutual information, and maximum likelihood.",
        "concepts": [
            "natural parameters draw straight e-flat coordinates",
            "expectation parameters draw straight m-flat coordinates",
            "maximum entropy is a projection onto moment constraints",
            "likelihood fitting is a divergence minimization problem",
        ],
        "visuals": [
            "Gaussian family in natural and expectation coordinates",
            "discrete simplex with exponential-family and mixture-family slices",
            "maximum-entropy projection onto a moment hyperplane",
            "mutual-information surface over a small joint table",
        ],
        "checks": [
            "log-partition gradient matches numerical expectation parameters",
            "probabilities from natural coordinates sum to one",
            "maximum-entropy solution satisfies the requested moments",
            "MLE projection decreases empirical KL divergence",
        ],
    },
    {
        "kind": "chapter",
        "number": 3,
        "label": "Chapter 03",
        "title": "Invariant Geometry of Manifold of Probability Distributions",
        "folder": "chapter-03-invariant-geometry-of-probability-distributions",
        "notebook": "03-invariant-geometry-of-probability-distributions.ipynb",
        "part": "part-01-geometry-of-divergence-functions",
        "topic": "chapter-03",
        "family": "divergence",
        "printed": "51-70",
        "pdf": "68-87",
        "focus": "Invariance, coarse graining, sufficient statistics, f-divergences, KL properties, Fisher information, and positive measures.",
        "concepts": [
            "coarse graining cannot increase distinguishability for invariant divergences",
            "f-divergences share a common convex-generator form",
            "Fisher information is the local metric selected by invariance",
            "positive measures widen the geometry beyond normalized distributions",
        ],
        "visuals": [
            "coarse-graining map from a fine simplex to a smaller simplex",
            "gallery of KL, chi-square, Hellinger, and alpha divergences",
            "local Fisher metric ellipses on the simplex",
            "data-processing inequality experiment with repeated random channels",
        ],
        "checks": [
            "coarse-grained KL does not exceed fine KL",
            "f-divergence is zero for identical distributions",
            "categorical Fisher metric is symmetric positive semidefinite",
            "random stochastic matrices preserve total probability",
        ],
    },
    {
        "kind": "chapter",
        "number": 4,
        "label": "Chapter 04",
        "title": "Alpha-Geometry, Tsallis q-Entropy and Positive-Definite Matrices",
        "folder": "chapter-04-alpha-geometry-tsallis-entropy-positive-definite-matrices",
        "notebook": "04-alpha-geometry-tsallis-entropy-positive-definite-matrices.ipynb",
        "part": "part-01-geometry-of-divergence-functions",
        "topic": "chapter-04",
        "family": "divergence",
        "printed": "71-106",
        "pdf": "88-123",
        "focus": "Alpha geometry, alpha geodesics and projections, Tsallis q-entropy, escort geometry, positive measures, positive-definite matrices, and miscellaneous divergences.",
        "concepts": [
            "alpha changes which coordinates look affine",
            "q-logarithms and q-exponentials deform ordinary exponential-family calculations",
            "escort distributions reweight outcomes before measuring geometry",
            "matrix divergences expose invariance under structured transformations",
        ],
        "visuals": [
            "alpha-geodesic family sweeping across the simplex",
            "q-logarithm and q-exponential deformation dashboard",
            "escort-distribution flow as q varies",
            "positive-definite matrix cone with divergence contours",
        ],
        "checks": [
            "alpha divergence approaches KL at the limiting alpha values",
            "escort probabilities remain normalized",
            "positive-definite matrix examples have positive eigenvalues",
            "Jensen-Shannon divergence is symmetric in the examples",
        ],
    },
    {
        "kind": "chapter",
        "number": 5,
        "label": "Chapter 05",
        "title": "Elements of Differential Geometry",
        "folder": "chapter-05-elements-of-differential-geometry",
        "notebook": "05-elements-of-differential-geometry.ipynb",
        "part": "part-02-dual-differential-geometry",
        "topic": "chapter-05",
        "family": "differential-geometry",
        "printed": "109-130",
        "pdf": "126-147",
        "focus": "Manifolds, tangent spaces, metrics, affine connections, tensors, covariant derivatives, geodesics, curvature, Levi-Civita connection, and submanifolds.",
        "concepts": [
            "tangent vectors are directional derivatives expressed in a chart",
            "a metric turns local displacement into measurable length",
            "an affine connection tells vectors how to move between tangent spaces",
            "curvature records path dependence of transport",
        ],
        "visuals": [
            "coordinate chart and tangent basis on a curved surface",
            "metric ellipse field for a non-Cartesian coordinate system",
            "geodesic shooting compared with straight chart lines",
            "round-trip parallel transport revealing curvature",
        ],
        "checks": [
            "metric matrices are symmetric positive definite on sampled points",
            "geodesic integration preserves expected first-order speed",
            "Levi-Civita symbols are torsion-free in the example",
            "parallel transport around a flat loop returns the vector",
        ],
    },
    {
        "kind": "chapter",
        "number": 6,
        "label": "Chapter 06",
        "title": "Dual Affine Connections and Dually Flat Manifold",
        "folder": "chapter-06-dual-affine-connections-dually-flat-manifold",
        "notebook": "06-dual-affine-connections-dually-flat-manifold.ipynb",
        "part": "part-02-dual-differential-geometry",
        "topic": "chapter-06",
        "family": "differential-geometry",
        "printed": "131-161",
        "pdf": "141-171",
        "focus": "Dual connections, metric and cubic tensors from divergence, alpha geometry, canonical divergence, mixed coordinates, neural firing, integrated information, and input-output economics.",
        "concepts": [
            "dual connections are paired through the metric",
            "a divergence contains metric and cubic-tensor information in its derivatives",
            "dually flat coordinates make canonical divergence computable",
            "mixed coordinates decompose interaction structure in finite systems",
        ],
        "visuals": [
            "dual coordinate nets and canonical divergence surface",
            "finite-difference metric and cubic tensor from a divergence",
            "mixed-coordinate k-cut decomposition in a binary distribution",
            "neural firing interaction lattice with divergence contributions",
        ],
        "checks": [
            "dual-coordinate inner products satisfy the expected Kronecker pairing",
            "finite-difference metric is symmetric",
            "canonical divergence is zero on the diagonal",
            "mixed-coordinate decomposition sums to total divergence in the toy model",
        ],
    },
    {
        "kind": "chapter",
        "number": 7,
        "label": "Chapter 07",
        "title": "Asymptotic Theory of Statistical Inference",
        "folder": "chapter-07-asymptotic-theory-of-statistical-inference",
        "notebook": "07-asymptotic-theory-of-statistical-inference.ipynb",
        "part": "part-03-statistical-inference",
        "topic": "chapter-07",
        "family": "statistical-inference",
        "printed": "165-177",
        "pdf": "173-185",
        "focus": "Estimation, exponential and curved exponential families, first- and higher-order asymptotics, and hypothesis testing.",
        "concepts": [
            "estimators become local random points on a statistical manifold",
            "Fisher information controls first-order covariance",
            "curvature explains higher-order correction terms",
            "hypothesis tests compare nearby submanifolds by information distance",
        ],
        "visuals": [
            "sampling cloud contracting toward a true parameter",
            "curved exponential family embedded in a flat family",
            "Fisher ellipses for first-order approximation",
            "likelihood-ratio, Wald, and score geometry comparison",
        ],
        "checks": [
            "simulated estimator variance approaches inverse Fisher scaling",
            "curved-family residual is orthogonal to the tangent projection",
            "test statistics agree locally in the small-deviation experiment",
            "confidence ellipse coverage improves with sample size",
        ],
    },
    {
        "kind": "chapter",
        "number": 8,
        "label": "Chapter 08",
        "title": "Estimation in the Presence of Hidden Variables",
        "folder": "chapter-08-hidden-variables-and-em",
        "notebook": "08-hidden-variables-and-em.ipynb",
        "part": "part-03-statistical-inference",
        "topic": "chapter-08",
        "family": "statistical-inference",
        "printed": "179-189",
        "pdf": "186-196",
        "focus": "EM as alternating divergence minimization, hidden-variable models, Gaussian mixtures, information loss under data reduction, and misspecification.",
        "concepts": [
            "hidden variables enlarge the complete-data manifold",
            "EM alternates between compatible observed-data and model constraints",
            "data reduction loses information when the statistic is insufficient",
            "misspecification replaces truth with the closest model point",
        ],
        "visuals": [
            "two-manifold EM projection diagram",
            "Gaussian-mixture responsibility heatmap",
            "monotone log-likelihood trace through EM iterations",
            "coarse-graining information-loss bar chart",
        ],
        "checks": [
            "responsibilities sum to one for each observation",
            "EM log-likelihood is non-decreasing in the demonstration",
            "coarse-grained divergence is no larger than original divergence",
            "misspecified projection minimizes the sampled KL curve",
        ],
    },
    {
        "kind": "chapter",
        "number": 9,
        "label": "Chapter 09",
        "title": "Neyman-Scott Problem: Estimating Function and Semiparametric Statistical Model",
        "folder": "chapter-09-neyman-scott-estimating-functions-semiparametrics",
        "notebook": "09-neyman-scott-estimating-functions-semiparametrics.ipynb",
        "part": "part-03-statistical-inference",
        "topic": "chapter-09",
        "family": "statistical-inference",
        "printed": "191-213",
        "pdf": "197-219",
        "focus": "Nuisance parameters, Neyman-Scott behavior, semiparametric models, estimating functions, exponential-case solutions, scale problems, and neural firing examples.",
        "concepts": [
            "many nuisance parameters can distort ordinary likelihood intuition",
            "estimating functions define directions rather than full parametric models",
            "semiparametric efficiency is a projection away from nuisance directions",
            "scale and neural firing examples make the geometry visible",
        ],
        "visuals": [
            "Neyman-Scott simulation showing persistent variance bias",
            "estimating-function vector field and zero set",
            "nuisance tangent projection diagram",
            "scale-problem information decomposition",
        ],
        "checks": [
            "bias in the Neyman-Scott variance simulation does not vanish in the fixed-group-size setup",
            "estimating-function root has small residual",
            "efficient score is orthogonal to nuisance directions",
            "scale example preserves positivity of variance estimates",
        ],
    },
    {
        "kind": "chapter",
        "number": 10,
        "label": "Chapter 10",
        "title": "Linear Systems and Time Series",
        "folder": "chapter-10-linear-systems-and-time-series",
        "notebook": "10-linear-systems-and-time-series.ipynb",
        "part": "part-03-statistical-inference",
        "topic": "chapter-10",
        "family": "statistical-inference",
        "printed": "215-227",
        "pdf": "220-232",
        "focus": "Stationary time series, linear systems, finite-dimensional system manifolds, dual system geometry, and AR, MA, and ARMA models.",
        "concepts": [
            "a stationary process can be represented by spectral geometry",
            "linear systems form finite-dimensional submanifolds inside broader process spaces",
            "AR and MA coordinates provide dual views of the same signal family",
            "prediction error and divergence are linked through system geometry",
        ],
        "visuals": [
            "AR and MA parameter regions with stability boundaries",
            "spectral-density family over frequency",
            "dual-coordinate grid for ARMA toy models",
            "prediction-error divergence surface",
        ],
        "checks": [
            "sample AR coefficients lie inside the stability region",
            "spectral densities are positive on the plotted grid",
            "autocovariance matrix is positive semidefinite",
            "dual coordinate conversion round-trips in the toy model",
        ],
    },
    {
        "kind": "chapter",
        "number": 11,
        "label": "Chapter 11",
        "title": "Machine Learning",
        "folder": "chapter-11-machine-learning",
        "notebook": "11-machine-learning.ipynb",
        "part": "part-04-applications-of-information-geometry",
        "topic": "chapter-11",
        "family": "applications",
        "printed": "231-278",
        "pdf": "248-295",
        "focus": "Clustering, Voronoi diagrams, robust centers, SVM geometry, kernels, graphical models, mean-field approximation, belief propagation, CCCP, boosting, Bayesian duality, RBMs, and contrastive divergence.",
        "concepts": [
            "Bregman centers explain several clustering updates",
            "kernel methods induce geometry in feature space",
            "belief propagation and mean-field methods are projection algorithms",
            "boosting and contrastive divergence can be read as geometric updates",
        ],
        "visuals": [
            "Bregman k-means centers and Voronoi regions",
            "kernel-induced metric field around training points",
            "graphical-model marginal polytope sketch",
            "RBM contrastive-divergence flow on a binary state space",
        ],
        "checks": [
            "cluster assignments match nearest Bregman center",
            "kernel matrix is positive semidefinite in examples",
            "belief-propagation messages remain normalized",
            "contrastive-divergence update has expected data-minus-model sign",
        ],
    },
    {
        "kind": "chapter",
        "number": 12,
        "label": "Chapter 12",
        "title": "Natural Gradient Learning and Its Dynamics in Singular Regions",
        "folder": "chapter-12-natural-gradient-and-singular-learning",
        "notebook": "12-natural-gradient-and-singular-learning.ipynb",
        "part": "part-04-applications-of-information-geometry",
        "topic": "chapter-12",
        "family": "applications",
        "printed": "279-314",
        "pdf": "282-317",
        "focus": "Natural gradient descent, stochastic learning, Hessian geometry, reinforcement learning, mirror descent, multilayer perceptron singularities, plateau dynamics, and singular statistical models.",
        "concepts": [
            "natural gradient rescales steepest descent by the information metric",
            "mirror descent is a dual-coordinate cousin of natural gradient learning",
            "singular regions create slow ordinary-gradient dynamics",
            "information geometry explains how natural gradient escapes plateau behavior",
        ],
        "visuals": [
            "ordinary-gradient versus natural-gradient vector fields",
            "mirror-descent path in primal and dual coordinates",
            "singular valley with plateau slowdown",
            "small multilayer perceptron symmetry and bifurcation diagram",
        ],
        "checks": [
            "natural-gradient direction solves the Fisher linear system",
            "mirror-descent iterates stay inside the simplex",
            "singular Hessian example has a small eigenvalue",
            "natural-gradient toy dynamics reduce loss faster than Euclidean scaling",
        ],
    },
    {
        "kind": "chapter",
        "number": 13,
        "label": "Chapter 13",
        "title": "Signal Processing and Optimization",
        "folder": "chapter-13-signal-processing-and-optimization",
        "notebook": "13-signal-processing-and-optimization.ipynb",
        "part": "part-04-applications-of-information-geometry",
        "topic": "chapter-13",
        "family": "applications",
        "printed": "315-358",
        "pdf": "318-361",
        "focus": "PCA, ICA, non-negative matrix factorization, sparse signal processing, convex programming, barrier-induced dual geometry, game-score geometry, and Hyvarinen score.",
        "concepts": [
            "PCA and whitening choose coordinates from covariance geometry",
            "ICA uses estimating functions to separate independent signals",
            "NMF and sparse regression become constrained divergence minimizations",
            "barrier functions and game scores generate dual geometric structures",
        ],
        "visuals": [
            "PCA whitening ellipse and component learning flow",
            "ICA source-mixing and separation geometry",
            "NMF simplex of non-negative parts",
            "barrier-function geodesics inside a convex feasible region",
        ],
        "checks": [
            "PCA eigenvectors are orthonormal",
            "whitened covariance is close to identity",
            "NMF factors remain non-negative",
            "barrier Hessian is positive definite inside the feasible region",
        ],
    },
]


def canonical_entries() -> list[dict]:
    return list(ENTRIES)


def parts() -> list[dict]:
    return list(PARTS)
