"""Rebuild the GDL course book and chapter index notebooks."""

from __future__ import annotations

from pathlib import Path

import nbformat
from nbformat.v4 import new_markdown_cell, new_notebook

import gdl_inventory as inventory

BOOK_ROOT = inventory.BOOK_ROOT


def write_markdown_notebook(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    nb = new_notebook(cells=[new_markdown_cell(text.strip() + "\n")])
    nbformat.write(nb, path)


def build_book_index() -> str:
    lines = [
        "# Geometric Deep Learning - Standalone Notebook Course",
        "",
        "This course is an original executable companion to *Geometric Deep Learning: Grids, Groups, Graphs, Geodesics, and Gauges*. It is designed to stand on its own: each chapter explains the concepts in fresh prose, generates its own visual artifacts, and checks the core invariants numerically.",
        "",
        "The PDF is used only as source orientation for structure, concepts, page spans, and notation. The course does not copy textbook prose, exercises, screenshots, page crops, or figures.",
        "",
        "## Front Matter Route",
        "",
        "- Preface idea: geometric deep learning treats architecture design as the search for invariants and equivariants of structured domains.",
        "- Notation idea: a domain `Omega`, signals `x: Omega -> C`, a symmetry group `G`, a representation `rho(g)`, and a learned map `f` are the recurring objects.",
        "- Body map: Chapter 2 explains why generic high-dimensional learning is hard; Chapters 3-5 build the geometric recipe; Chapters 6-7 show applications and historical roots.",
        "",
        "## Chapters",
        "",
    ]
    for entry in inventory.ENTRIES:
        chapter_index = f"{entry['folder']}/00-index.ipynb"
        canonical = f"{entry['folder']}/{entry['notebook']}"
        lines.append(
            f"- [Chapter {entry['chapter']:02d}: {entry['title']}]({chapter_index}) - "
            f"[canonical notebook]({canonical}); printed pp. {entry['printed_pages']}; "
            f"PDF pp. {entry['pdf_pages']}; {entry['focus']}"
        )
    lines.extend(
        [
            "",
            "## Validation Commands",
            "",
            "```powershell",
            "uv run python Geometric-Deep-Learning/scripts/smoke_gdl_stack.py",
            "uv run python -m compileall -q Geometric-Deep-Learning/utils Geometric-Deep-Learning/scripts",
            "uv run python Geometric-Deep-Learning/scripts/audit_gdl_notebooks.py --min-words 1200 --min-code-cells 5",
            "uv run python Geometric-Deep-Learning/scripts/audit_gdl_visuals.py",
            "uv run python Geometric-Deep-Learning/scripts/validate_gdl_course.py --all --timeout 300",
            "```",
        ]
    )
    return "\n".join(lines)


def build_chapter_index(entry: dict[str, object]) -> str:
    return "\n".join(
        [
            f"# Chapter {entry['chapter']:02d}: {entry['title']}",
            "",
            "[Back to Book Index](../00-book-index.ipynb)",
            "",
            f"- Canonical notebook: [{entry['notebook']}]({entry['notebook']})",
            f"- Printed pages: {entry['printed_pages']}",
            f"- Physical PDF pages: {entry['pdf_pages']}",
            f"- Sections: {entry['sections']}",
            f"- Focus: {entry['focus']}",
            f"- Visual spine: {entry['visual_spine']}",
            "",
            "Artifacts generated by this chapter live under "
            f"`artifacts/{inventory.chapter_topic(int(entry['chapter']))}/`.",
        ]
    )


def main() -> None:
    for entry in inventory.ENTRIES:
        canonical = inventory.canonical_path(entry)
        if not canonical.exists():
            raise FileNotFoundError(f"Missing canonical notebook: {canonical}")
    write_markdown_notebook(BOOK_ROOT / "00-book-index.ipynb", build_book_index())
    for entry in inventory.ENTRIES:
        write_markdown_notebook(inventory.index_path(entry), build_chapter_index(entry))
    print(f"Updated book index and {len(inventory.ENTRIES)} chapter indexes.")


if __name__ == "__main__":
    main()

