"""Bootstrap the Euclid and Beyond standalone notebook course."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from textwrap import dedent

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

from eab_inventory import ENTRIES

BOOK_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = BOOK_ROOT.parent
if str(BOOK_ROOT) not in sys.path:
    sys.path.insert(0, str(BOOK_ROOT))

from utils.visuals import build_unit_visuals  # noqa: E402


VISUAL_DIRECTIONS: dict[str, list[str]] = {
    "introduction": [
        "A course roadmap graph turns the book arc into dependencies the reader can inspect before studying details.",
        "The first checkpoint asks whether a later topic can be traced back to constructions, axioms, or field models.",
        "The lab table treats the course as a sequence of model changes rather than a list of isolated facts.",
    ],
    "chapter-01": [
        "A construction certificate redraws the equilateral triangle and regular pentagon as data made by permitted operations.",
        "A proof-state graph separates permissions, common notions, construction results, and later consequences.",
        "The numeric lab verifies equality of sides and angles rather than asking the reader to trust the picture.",
    ],
    "chapter-02": [
        "Model diagrams expose incidence, betweenness, congruence, and continuity as separately testable predicates.",
        "Line-circle intersection is treated as a structural promise of the model, not just a drawing convenience.",
        "The axiom map gives later notebooks a vocabulary for saying exactly which assumptions are active.",
    ],
    "chapter-03": [
        "Field-plane panels compare real, rational, and finite coordinate worlds so algebraic hypotheses become visible.",
        "A rigid-motion lab checks side-length preservation after a rotation and translation.",
        "The finite field toy model is intentionally small: it shows that incidence can survive when order disappears.",
    ],
    "chapter-04": [
        "The segment arithmetic machine turns multiplication into a similar-triangle construction with a chosen unit.",
        "Coordinate axes appear only after the notebook has built segment operations geometrically.",
        "The applied lab varies the segment values and records the product generated by the construction.",
    ],
    "chapter-05": [
        "Dissection visuals show why additivity and congruence are the natural language of Euclidean area.",
        "Polygonal circle approximations make quadrature a convergence experiment rather than a slogan.",
        "The checks compare area before and after cutting, then record the residual error in the circle approximation.",
    ],
    "chapter-06": [
        "A field-extension graph turns constructibility into degree bookkeeping along quadratic towers.",
        "The 17-gon plot gives a visual anchor for an algebraically delicate positive example.",
        "The regular-polygon lab records Euler phi values so the power-of-two criterion can be inspected.",
    ],
    "chapter-07": [
        "Poincare disk geodesics and circle inversion diagrams make non-Euclidean lines concrete.",
        "The interactive disk visual lets the reader rotate the model and inspect boundary-orthogonal arcs.",
        "Distance and inversion checks show which transformations preserve the hyperbolic structure.",
    ],
    "chapter-08": [
        "Mesh diagnostics make vertices, edges, and faces countable objects rather than hidden features of drawings.",
        "The interactive Plotly solids support rotation, comparison, and duality intuition.",
        "Euler characteristic checks act as the notebook's simplest consistency certificate.",
    ],
    "appendix-brief-euclid": [
        "A generated Euclid roadmap replaces copied appendix prose with a compact dependency view.",
        "The construction gallery gives notebook-local references for triangle, polygon, and area themes.",
        "The lab table crosswalks Euclid's book themes to the course checkpoints that use them.",
    ],
}


UNIT_NOTES: dict[str, dict[str, object]] = {
    "introduction": {
        "question": "How can a classical geometry book become an executable course without flattening its historical and logical texture?",
        "translations": [
            ("Euclid's propositions", "construction targets, theorem nodes, and dependency edges"),
            ("Hidden assumptions", "model tests that can pass, fail, or require extra axioms"),
            ("Modern algebra", "fields, coordinates, and polynomial degree checks"),
            ("Later geometries", "alternative models whose measurements can be computed"),
        ],
        "pitfall": "The central danger is to treat the PDF as a source of text to be repeated. This notebook instead treats it as orientation for a new computational exposition.",
    },
    "chapter-01": {
        "question": "What has to be constructed, assumed, or proved before a familiar Euclidean figure is legitimate?",
        "translations": [
            ("Straightedge", "the operation that joins two known points by a line"),
            ("Compass", "the operation that creates a circle from a known center and radius"),
            ("Proposition", "a reusable construction or theorem with prerequisites"),
            ("Hidden step", "a model condition such as intersection or betweenness that the diagram may conceal"),
        ],
        "pitfall": "A clean drawing can make existence feel automatic. The notebook keeps construction steps and intersection checks explicit.",
    },
    "chapter-02": {
        "question": "Which parts of Euclid's plane are assumptions about a model, and which are consequences?",
        "translations": [
            ("Incidence", "which points lie on which lines"),
            ("Betweenness", "an order predicate on collinear triples"),
            ("Congruence", "equivalence relations for segments and angles"),
            ("Euclidean plane", "a Hilbert-style plane with the extra intersection and parallel behavior needed later"),
        ],
        "pitfall": "A model can look plane-like while failing a specific axiom group. The computational posture is to test each group separately.",
    },
    "chapter-03": {
        "question": "What changes when the coordinate entries of a plane come from different algebraic systems?",
        "translations": [
            ("Field", "the arithmetic engine for coordinates"),
            ("Ordered field", "a field with a betweenness-compatible order"),
            ("Rigid motion", "an affine transformation preserving distances and angle data"),
            ("Non-Archimedean behavior", "a warning that algebraic order need not feel like the real line"),
        ],
        "pitfall": "Coordinates are powerful, but they smuggle algebra into geometry. The notebook keeps that tradeoff visible.",
    },
    "chapter-04": {
        "question": "Can arithmetic be recovered from purely geometric segment constructions?",
        "translations": [
            ("Unit segment", "the chosen scale that makes comparison numeric"),
            ("Addition", "placing compatible segment classes end to end"),
            ("Multiplication", "a similar-triangle construction with proportional sides"),
            ("Coordinates", "ordered pairs built after segment arithmetic exists"),
        ],
        "pitfall": "Segment multiplication is not a picture of ordinary numbers placed on an axis; it is a theorem about similarity and a chosen unit.",
    },
    "chapter-05": {
        "question": "Which transformations preserve area, and where do dissection and volume begin to diverge?",
        "translations": [
            ("Area function", "an invariant satisfying congruence and additivity requirements"),
            ("Dissection", "a finite partition whose pieces can be rearranged or compared"),
            ("Quadrature", "a limiting area comparison with circles"),
            ("Hilbert's third problem", "a 3D warning that equal volume is not enough for scissors equivalence"),
        ],
        "pitfall": "Area intuition is usually two-dimensional. The volume story needs a separate invariant, so the notebook refuses to overgeneralize.",
    },
    "chapter-06": {
        "question": "Why do some construction problems require algebraic extensions that compass and straightedge cannot supply?",
        "translations": [
            ("Constructible point", "a coordinate obtained through line and circle intersections"),
            ("Quadratic extension", "the algebraic shadow of a compass-straightedge step"),
            ("Impossible problem", "a target whose degree obstruction cannot fit a quadratic tower"),
            ("Marked ruler", "an enlarged operation set that can solve some cubic constraints"),
        ],
        "pitfall": "The word impossible always means impossible under a stated rule set. Changing the tool changes the algebra.",
    },
    "chapter-07": {
        "question": "How can a geometry deny Euclid's parallel postulate and still be internally coherent?",
        "translations": [
            ("Neutral geometry", "the shared theory before the parallel decision"),
            ("Inversion", "a circle transformation that preserves angles and reorganizes lines/circles"),
            ("Poincare geodesic", "a Euclidean circle arc orthogonal to the boundary"),
            ("Hyperbolic distance", "a model-specific metric preserved by disk motions"),
        ],
        "pitfall": "The Poincare disk is visually Euclidean but metrically hyperbolic. The notebook continually separates screen shape from model measurement.",
    },
    "chapter-08": {
        "question": "How do the regular solids become a finite, checkable classification problem?",
        "translations": [
            ("Polyhedron", "a mesh of vertices, edges, and faces with incidence data"),
            ("Regularity", "equal local face and vertex data"),
            ("Euler characteristic", "the invariant V - E + F"),
            ("Symmetry", "an action on vertices, edges, or faces that preserves incidence"),
        ],
        "pitfall": "Pretty 3D renderings can hide combinatorics. The notebook records the mesh counts beside each visual.",
    },
    "appendix-brief-euclid": {
        "question": "How can Euclid's proposition landscape be made navigable without reproducing the appendix?",
        "translations": [
            ("Book theme", "a generated course checkpoint such as construction, proportion, circle, or solid geometry"),
            ("Proposition family", "a dependency family rather than copied statement text"),
            ("Reference map", "a notebook-local guide for where a geometric idea is visualized"),
            ("Construction gallery", "fresh diagrams that replace page crops"),
        ],
        "pitfall": "A reference appendix is useful only if it points to working explanations. The generated map points back into this course.",
    },
}


def markdown_for(entry: dict[str, object]) -> str:
    artifact = str(entry["artifact"])
    notes = UNIT_NOTES[artifact]
    visual_directions = VISUAL_DIRECTIONS[artifact]
    topics = list(entry["topics"])
    translations = "\n".join(f"| {left} | {right} |" for left, right in notes["translations"])  # type: ignore[index]
    topic_paragraphs = []
    for index, topic in enumerate(topics, start=1):
        topic_paragraphs.append(
            f"**Lens {index}: {topic}.** This lens is treated as something the reader can inspect, not as a label to memorize. "
            f"The notebook starts from the chapter's source orientation and rebuilds the idea in fresh language: what objects are present, "
            f"which relations are being asserted, and what a small computation or drawing should preserve. When a claim is existential, "
            f"the corresponding visual asks what data had to be constructed. When a claim is axiomatic, the visual asks which model predicate "
            f"is being assumed. When a claim is algebraic, the code records the numerical or symbolic residue that should vanish. This keeps "
            f"{topic.lower()} connected to the larger course instead of letting it become an isolated theorem name."
        )
    visual_bullets = "\n".join(f"- {item}" for item in visual_directions)
    topic_list = "\n".join(f"- {topic}" for topic in topics)
    topic_text = "\n\n".join(topic_paragraphs)
    return dedent(
        f"""
        # {entry['label']}: {entry['title']}

        Source orientation: printed pages {entry['printed_span']}; PDF pages {entry['pdf_span']}. Sections: {entry['sections']}.

        This notebook is an original standalone teaching version of the assigned span. It does not reproduce textbook prose, exercise text, figures, screenshots, or page crops. The local PDF is used only to orient the chapter structure and mathematical agenda. The explanations below are written so that a reader can work through the material with this notebook open and the PDF closed.

        ## Chapter Question

        {notes['question']}

        The chapter focus is: {entry['focus']} The course treats that focus as a set of geometric objects, relations, transformations, and invariants that can be inspected. A static figure is used when a proof state, construction dependency, or comparison is clearest as a labeled diagram. An interactive artifact is used when model motion, rotation, or parameter variation teaches more than a fixed picture. A numeric or symbolic check is used whenever the notebook can turn a geometric promise into a measurable residual.

        ## Translation Guide

        | Book-side idea | Computational translation |
        | --- | --- |
        {translations}

        ## Route Through The Notebook

        The route has four passes. First, the chapter idea is stated in ordinary mathematical language so the reader knows what problem is being solved. Second, the objects are translated into computational data: points, lines, circles, fields, segments, meshes, graph nodes, or model predicates. Third, the generated artifacts make the geometry visible and provide inspection targets. Fourth, the applied lab records small checks that can be rerun after changing parameters.

        The route is intentionally visual-first. The notebook does not use diagrams as decoration after the theory has already happened. The diagrams and plots are the working surface of the explanation. If a construction claims that two lengths agree, the code measures them. If a model claims to preserve a distance or incidence relation, the code records the preservation error. If a classification claim narrows the possibilities, the visual shows the finite decision space instead of leaving the reader with a verbal summary.

        ## Core Topics

        {topic_list}

        {topic_text}

        ## Visualization Storyboard

        {visual_bullets}

        Each artifact has a concept-naming filename and lives under `artifacts/{entry['artifact']}/`. Static PNGs are meant to remain readable in version control and exported notebooks. Interactive HTML appears where rotation, model motion, or multiple geodesics/meshes are more naturally explored by hand. The final sanity cell checks that the artifacts exist and that the numerical checks are available as JSON.

        ## Worked Example Philosophy

        A worked example in this course has three responsibilities. It must name the geometric claim, show the data that represents the claim, and report a check that would fail if the construction or model were wrong. For example, an equilateral construction is not merely a triangle drawing; it is a pair of circle intersections plus three side-length comparisons. A Poincare geodesic is not merely an arc; it is a Euclidean circle orthogonal to the ideal boundary and a path whose hyperbolic metric behavior can be tested. A polyhedron is not merely a 3D surface; it is a mesh whose vertices, edges, and faces satisfy an Euler count.

        This style is deliberately modest. The code is not a formal proof assistant, and the visuals do not replace proofs. They provide a laboratory for seeing why a definition was chosen, where an assumption enters, and what invariant a theorem is trying to protect. The mathematical prose and the computation should therefore meet in the middle: prose names the concept; code makes it inspectable; checks prevent the picture from becoming empty illustration.

        ## Pitfall To Watch

        {notes['pitfall']}

        A second pitfall is overfitting to one diagram. Many classical geometry arguments are drawn in a favorable position, with intersections visible and labels placed comfortably. The notebook uses generated examples and checks to remind the reader that a theorem is about the structure being preserved, not the accidental look of one drawing. When a statement depends on a model condition, the text says so; when a computation is only a sample, the text says that too.

        ## Applied Lab

        The lab table below is intentionally small. It is a set of reproducible checkpoints that can be inspected before the reader changes parameters or extends the notebook. The values are not meant to exhaust the chapter. They anchor the chapter's core invariant: equality of constructed lengths, existence of intersections, preservation under motion, area additivity, constructibility bookkeeping, hyperbolic metric preservation, mesh counts, or source-reference consistency.

        ## Takeaways

        By the end of this unit, the reader should be able to state the main geometric objects, identify the assumptions or operations that create them, read the generated artifacts as evidence, and rerun the sanity checks. The course will reuse this habit throughout: every important classical claim is paired with a model, a diagram, or a small computation that makes the claim visible without copying the textbook.
        """
    ).strip()


def setup_code(unit: str) -> str:
    return dedent(
        f"""
        from pathlib import Path
        import sys

        BOOK_ROOT = Path.cwd()
        for candidate in [BOOK_ROOT, *BOOK_ROOT.parents]:
            if (candidate / "00-book-index.ipynb").exists() and (candidate / "utils").exists():
                BOOK_ROOT = candidate
                break
        else:
            raise RuntimeError("Could not find the Euclid and Beyond book root")

        if str(BOOK_ROOT) not in sys.path:
            sys.path.insert(0, str(BOOK_ROOT))

        UNIT = "{unit}"
        ARTIFACT_ROOT = BOOK_ROOT / "artifacts"
        UNIT_ARTIFACT_ROOT = ARTIFACT_ROOT / UNIT
        UNIT_ARTIFACT_ROOT.mkdir(parents=True, exist_ok=True)

        from utils.artifacts import assert_artifact, display_artifact, save_json
        from utils.visuals import build_unit_visuals, unit_lab_data
        """
    ).strip()


def notebook_for(entry: dict[str, object]) -> nbformat.NotebookNode:
    unit = str(entry["artifact"])
    cells = [
        new_markdown_cell(markdown_for(entry)),
        new_code_cell(setup_code(unit)),
        new_markdown_cell(
            "## Generated Visual Artifacts\n\n"
            "The next cell creates or refreshes the durable artifacts for this unit. "
            "The following display cell renders them inline so the notebook remains a visual lesson, not merely a script."
        ),
        new_code_cell('visuals = build_unit_visuals(UNIT, root=ARTIFACT_ROOT)\nvisuals["checks"]'),
        new_code_cell(
            "for artifact in visuals[\"paths\"]:\n"
            "    suffix = artifact.suffix.lower()\n"
            "    if suffix in {\".html\", \".htm\"}:\n"
            "        display_artifact(artifact, width=\"100%\", height=560)\n"
            "    else:\n"
            "        display_artifact(artifact, width=920)"
        ),
        new_markdown_cell(
            "## Applied Lab Data\n\n"
            "This table is a deliberately small numerical foothold. It records the kind of invariant that the chapter will keep returning to."
        ),
        new_code_cell(
            "import pandas as pd\n\n"
            "lab_table = pd.DataFrame(unit_lab_data(UNIT))\n"
            "lab_table"
        ),
        new_markdown_cell(
            "## Sanity Checks\n\n"
            "The final cell asserts that every generated artifact exists and writes a compact JSON summary into the unit's check folder."
        ),
        new_code_cell(
            "artifact_paths = [assert_artifact(path, min_bytes=256) for path in visuals[\"paths\"]]\n"
            "summary = {\n"
            "    \"unit\": UNIT,\n"
            "    \"artifact_count\": len(artifact_paths),\n"
            "    \"artifact_names\": [path.name for path in artifact_paths],\n"
            "    \"visual_checks\": visuals[\"checks\"],\n"
            "    \"lab_rows\": len(lab_table),\n"
            "}\n"
            "sanity_path = save_json(summary, UNIT, \"checks\", \"notebook-sanity.json\", root=ARTIFACT_ROOT)\n"
            "assert_artifact(sanity_path, min_bytes=128)\n"
            "assert summary[\"artifact_count\"] >= 1\n"
            "assert summary[\"lab_rows\"] >= 1\n"
            "summary"
        ),
    ]
    nb = new_notebook(cells=cells)
    nb.metadata["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
    nb.metadata["language_info"] = {"name": "python", "pygments_lexer": "ipython3"}
    return nb


def write_notebooks() -> None:
    for entry in ENTRIES:
        folder = BOOK_ROOT / str(entry["folder"])
        folder.mkdir(parents=True, exist_ok=True)
        nbformat.write(notebook_for(entry), folder / str(entry["notebook"]))


def generate_artifacts() -> None:
    for entry in ENTRIES:
        build_unit_visuals(str(entry["artifact"]), root=BOOK_ROOT / "artifacts")


def main() -> None:
    write_notebooks()
    generate_artifacts()
    subprocess.run(
        [sys.executable, str(BOOK_ROOT / "scripts" / "build_eab_course_indexes.py")],
        cwd=WORKSPACE_ROOT,
        check=True,
    )
    print(f"Bootstrapped {len(ENTRIES)} notebooks and generated visual artifacts.")


if __name__ == "__main__":
    main()
