"""Inventory for the Euclid and Beyond standalone notebook course."""

from __future__ import annotations

from typing import Any

PDF_SOURCE = "Euclid and Beyond.pdf"

SOURCE_SPAN_NOTES = [
    "The PDF is image-based; source orientation uses rendered pages rather than text extraction.",
    "Arabic printed pages map to physical PDF pages by adding 12.",
    "Back matter is inventoried but is not a canonical teaching notebook.",
]

ENTRIES: list[dict[str, Any]] = [
    {
        "id": "introduction",
        "kind": "introduction",
        "label": "Introduction",
        "number": 0,
        "title": "Introduction",
        "folder": "introduction",
        "notebook": "introduction.ipynb",
        "artifact": "introduction",
        "printed_span": "1-6",
        "pdf_span": "13-18",
        "sections": "course orientation",
        "focus": "Frames Euclid as the starting point for modern foundations, algebraic models, constructibility, non-Euclidean geometry, and polyhedra.",
        "topics": [
            "Euclid's Elements as a source of constructions and proof questions",
            "Axiomatic rigor and the role of hidden assumptions",
            "Geometry without numbers versus coordinate and field methods",
            "Constructibility, area, hyperbolic geometry, and polyhedra as the course arc",
        ],
    },
    {
        "id": 1,
        "kind": "chapter",
        "label": "Chapter 1",
        "number": 1,
        "title": "Euclid's Geometry",
        "folder": "chapter-01-euclids-geometry",
        "notebook": "01-euclids-geometry.ipynb",
        "artifact": "chapter-01",
        "printed_span": "7-64",
        "pdf_span": "19-76",
        "sections": "1-5: Elements, ruler/compass, axioms, pentagon, newer results",
        "focus": "Turns Euclid's constructions and proof style into inspectable construction steps, dependencies, and existence checks.",
        "topics": [
            "Ruler and compass constructions",
            "Implicit assumptions in classical proofs",
            "Equilateral triangle and regular pentagon construction logic",
            "Proof dependency graphs and construction certificates",
        ],
    },
    {
        "id": 2,
        "kind": "chapter",
        "label": "Chapter 2",
        "number": 2,
        "title": "Hilbert's Axioms",
        "folder": "chapter-02-hilberts-axioms",
        "notebook": "02-hilberts-axioms.ipynb",
        "artifact": "chapter-02",
        "printed_span": "65-116",
        "pdf_span": "77-128",
        "sections": "6-12: incidence, betweenness, congruence, Hilbert/Euclidean planes",
        "focus": "Shows how incidence, order, congruence, continuity, and line-circle interaction become testable model properties.",
        "topics": [
            "Incidence and betweenness",
            "Segment and angle congruence",
            "Hilbert planes and Euclidean planes",
            "Line-circle and circle-circle intersection behavior",
        ],
    },
    {
        "id": 3,
        "kind": "chapter",
        "label": "Chapter 3",
        "number": 3,
        "title": "Geometry over Fields",
        "folder": "chapter-03-geometry-over-fields",
        "notebook": "03-geometry-over-fields.ipynb",
        "artifact": "chapter-03",
        "printed_span": "117-164",
        "pdf_span": "129-176",
        "sections": "13-18: Cartesian/abstract fields, ordered fields, rigid motions, non-Archimedean geometry",
        "focus": "Compares coordinate planes over different algebraic systems and tracks which geometric behaviors require order or completeness.",
        "topics": [
            "Cartesian and abstract field planes",
            "Ordered fields and betweenness",
            "Rigid motions and SAS",
            "Finite and non-Archimedean toy models",
        ],
    },
    {
        "id": 4,
        "kind": "chapter",
        "label": "Chapter 4",
        "number": 4,
        "title": "Segment Arithmetic",
        "folder": "chapter-04-segment-arithmetic",
        "notebook": "04-segment-arithmetic.ipynb",
        "artifact": "chapter-04",
        "printed_span": "165-194",
        "pdf_span": "177-206",
        "sections": "19-21: segment operations, similar triangles, coordinates",
        "focus": "Builds arithmetic operations out of segment constructions and uses similar triangles to introduce coordinates.",
        "topics": [
            "Addition and multiplication of line segments",
            "Similar triangles as arithmetic machines",
            "Choosing a unit segment",
            "Coordinates recovered from geometry",
        ],
    },
    {
        "id": 5,
        "kind": "chapter",
        "label": "Chapter 5",
        "number": 5,
        "title": "Area",
        "folder": "chapter-05-area",
        "notebook": "05-area.ipynb",
        "artifact": "chapter-05",
        "printed_span": "195-240",
        "pdf_span": "207-252",
        "sections": "22-27: Euclidean area, measure functions, dissection, circle quadrature, volume, Hilbert's third problem",
        "focus": "Treats area and volume as invariants tested by dissection, approximation, and obstruction.",
        "topics": [
            "Euclidean area and measure functions",
            "Dissection and equidecomposability",
            "Circle quadrature approximations",
            "Volume and Hilbert's third problem as an obstruction story",
        ],
    },
    {
        "id": 6,
        "kind": "chapter",
        "label": "Chapter 6",
        "number": 6,
        "title": "Construction Problems and Field Extensions",
        "folder": "chapter-06-construction-problems-and-field-extensions",
        "notebook": "06-construction-problems-and-field-extensions.ipynb",
        "artifact": "chapter-06",
        "printed_span": "241-294",
        "pdf_span": "253-306",
        "sections": "28-32: famous problems, 17-gon, marked ruler, cubic/quartic equations, finite extensions",
        "focus": "Connects constructible geometry to field extensions, polynomial degree, and the boundary between compass-straightedge and marked-ruler power.",
        "topics": [
            "Three classical impossible problems",
            "Regular 17-gon construction signal",
            "Marked ruler versus compass-straightedge",
            "Cubic, quartic, and finite field extensions",
        ],
    },
    {
        "id": 7,
        "kind": "chapter",
        "label": "Chapter 7",
        "number": 7,
        "title": "Non-Euclidean Geometry",
        "folder": "chapter-07-non-euclidean-geometry",
        "notebook": "07-non-euclidean-geometry.ipynb",
        "artifact": "chapter-07",
        "printed_span": "295-434",
        "pdf_span": "307-446",
        "sections": "33-43: parallel postulate, neutral/hyperbolic geometry, inversion, Poincare model, ends, trig",
        "focus": "Uses neutral and hyperbolic models to make the parallel postulate, inversion, Poincare geodesics, ends, and hyperbolic trigonometry inspectable.",
        "topics": [
            "Parallel postulate history and neutral geometry",
            "Circle inversion and geodesic arcs",
            "Poincare disk and half-plane models",
            "Hyperbolic distance, area, and trigonometry",
        ],
    },
    {
        "id": 8,
        "kind": "chapter",
        "label": "Chapter 8",
        "number": 8,
        "title": "Polyhedra",
        "folder": "chapter-08-polyhedra",
        "notebook": "08-polyhedra.ipynb",
        "artifact": "chapter-08",
        "printed_span": "435-480",
        "pdf_span": "447-492",
        "sections": "44-47: regular solids, Euler/Cauchy, semiregular polyhedra, symmetry groups",
        "focus": "Studies polyhedra through meshes, Euler characteristic, rigidity intuition, and symmetry diagnostics.",
        "topics": [
            "The regular solids",
            "Euler characteristic",
            "Cauchy rigidity as edge-face constraint",
            "Semiregular polyhedra and symmetry groups",
        ],
    },
    {
        "id": "appendix",
        "kind": "appendix",
        "label": "Appendix",
        "number": 9,
        "title": "Brief Euclid",
        "folder": "appendix-brief-euclid",
        "notebook": "appendix-brief-euclid.ipynb",
        "artifact": "appendix-brief-euclid",
        "printed_span": "481-486",
        "pdf_span": "493-498",
        "sections": "compact Euclid reference",
        "focus": "Provides a compact generated map of Euclid's book-level structure and proposition themes without reproducing the appendix.",
        "topics": [
            "Books I-XIII as a dependency map",
            "Construction, proportion, number, and solid geometry themes",
            "How the course reuses Euclid's propositions as modern checkpoints",
        ],
    },
]

BACK_MATTER: list[dict[str, str]] = [
    {"title": "Notes", "printed_span": "487-494", "pdf_span": "499-506"},
    {"title": "References", "printed_span": "495-502", "pdf_span": "507-514"},
    {"title": "List of Axioms", "printed_span": "503-504", "pdf_span": "515-516"},
    {"title": "Index of Euclid's Propositions", "printed_span": "505-506", "pdf_span": "517-518"},
    {"title": "Index", "printed_span": "507-528", "pdf_span": "519-540"},
]


def entry_by_artifact(artifact: str) -> dict[str, Any]:
    for entry in ENTRIES:
        if entry["artifact"] == artifact:
            return entry
    raise KeyError(artifact)
