"""Numerical helpers for Chapter 5 meet and join notebooks.

The functions here deliberately use transparent linear algebra.  They are not a
complete implementation of Grassmann-Cayley algebra; they provide small,
checkable coordinate shadows of the meet and join ideas from Chapter 5.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import sqrt
from typing import Iterable

import numpy as np
import plotly.graph_objects as go

EPS = 1e-10

COLORS = {
    "line": "#1f77b4",
    "line_alt": "#d62728",
    "plane": "#f2c14e",
    "meet": "#2ca02c",
    "join": "#9467bd",
    "faint": "rgba(80, 80, 80, 0.28)",
}


def as_columns(vectors: Iterable[Iterable[float]] | np.ndarray) -> np.ndarray:
    """Return a matrix whose columns are the supplied basis vectors."""
    array = np.asarray(vectors, dtype=float)
    if array.ndim == 1:
        return array.reshape((-1, 1))
    if array.ndim != 2:
        raise ValueError(f"expected a vector or matrix, got shape {array.shape}")
    return array


def normalize(vector: Iterable[float] | np.ndarray, *, tol: float = EPS) -> np.ndarray:
    """Return a unit vector, raising on near-zero input."""
    value = np.asarray(vector, dtype=float)
    length = np.linalg.norm(value)
    if length <= tol:
        raise ValueError("cannot normalize a near-zero vector")
    return value / length


def matrix_rank(matrix: np.ndarray, *, tol: float = EPS) -> int:
    """Numerical rank from singular values."""
    values = np.linalg.svd(np.asarray(matrix, dtype=float), compute_uv=False)
    return int(np.sum(values > tol))


def nullspace(matrix: np.ndarray, *, tol: float = EPS) -> np.ndarray:
    """Return an orthonormal basis for the nullspace of ``matrix``."""
    matrix = np.asarray(matrix, dtype=float)
    _, values, vh = np.linalg.svd(matrix, full_matrices=True)
    rank = int(np.sum(values > tol))
    return vh[rank:].T.copy()


def orthonormal_basis(matrix: np.ndarray, *, tol: float = EPS) -> np.ndarray:
    """Return an orthonormal basis for the column span of ``matrix``."""
    matrix = np.asarray(matrix, dtype=float)
    if matrix.ndim != 2:
        raise ValueError(f"expected a matrix, got shape {matrix.shape}")
    if matrix.size == 0:
        return np.zeros((matrix.shape[0], 0))
    u, values, _ = np.linalg.svd(matrix, full_matrices=False)
    rank = int(np.sum(values > tol))
    return u[:, :rank].copy()


def blade_volume(basis: Iterable[Iterable[float]] | np.ndarray, *, tol: float = EPS) -> float:
    """Return the Euclidean k-volume represented by a basis matrix."""
    basis = as_columns(basis)
    if basis.shape[1] == 0:
        return 1.0
    gram = basis.T @ basis
    det = float(np.linalg.det(gram))
    if det < 0 and abs(det) < tol:
        det = 0.0
    if det < 0:
        raise ValueError("Gram determinant is negative beyond tolerance")
    return sqrt(det)


def join_basis(*bases: np.ndarray, tol: float = EPS) -> np.ndarray:
    """Return an orthonormal basis for the span generated by all arguments."""
    if not bases:
        raise ValueError("join_basis needs at least one basis")
    matrices = [as_columns(basis) for basis in bases]
    rows = {matrix.shape[0] for matrix in matrices}
    if len(rows) != 1:
        raise ValueError("all bases must live in the same ambient dimension")
    return orthonormal_basis(np.column_stack(matrices), tol=tol)


def meet_basis(a: np.ndarray, b: np.ndarray, *, tol: float = EPS) -> np.ndarray:
    """Return an orthonormal basis for the intersection of two column spans."""
    a = as_columns(a)
    b = as_columns(b)
    if a.shape[0] != b.shape[0]:
        raise ValueError("both spaces must live in the same ambient dimension")
    kernel = nullspace(np.column_stack([a, -b]), tol=tol)
    if kernel.shape[1] == 0:
        return np.zeros((a.shape[0], 0))
    a_coefficients = kernel[: a.shape[1], :]
    return orthonormal_basis(a @ a_coefficients, tol=tol)


def projector(basis: np.ndarray, *, tol: float = EPS) -> np.ndarray:
    """Return the orthogonal projector onto the span of ``basis``."""
    q = orthonormal_basis(as_columns(basis), tol=tol)
    return q @ q.T


def subspace_distance(a: np.ndarray, b: np.ndarray, *, tol: float = EPS) -> float:
    """Return a compact distance between two subspaces."""
    return float(np.linalg.norm(projector(a, tol=tol) - projector(b, tol=tol), ord="fro"))


def principal_angles(a: np.ndarray, b: np.ndarray, *, tol: float = EPS) -> np.ndarray:
    """Return principal angles between two subspaces in radians."""
    qa = orthonormal_basis(as_columns(a), tol=tol)
    qb = orthonormal_basis(as_columns(b), tol=tol)
    if qa.shape[1] == 0 or qb.shape[1] == 0:
        return np.array([])
    singular_values = np.linalg.svd(qa.T @ qb, compute_uv=False)
    singular_values = np.clip(singular_values, -1.0, 1.0)
    return np.arccos(singular_values)


def transform_basis(matrix: np.ndarray, basis: np.ndarray, *, tol: float = EPS) -> np.ndarray:
    """Apply a linear map to a subspace basis and clean the resulting span."""
    return orthonormal_basis(np.asarray(matrix, dtype=float) @ as_columns(basis), tol=tol)


def homogeneous_point(x: float, y: float, w: float = 1.0) -> np.ndarray:
    """Return a 2-D homogeneous point."""
    return np.array([float(x), float(y), float(w)])


def homogeneous_line_from_points(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Join two homogeneous points into a line."""
    return np.cross(np.asarray(a, dtype=float), np.asarray(b, dtype=float))


def homogeneous_intersection(line_a: np.ndarray, line_b: np.ndarray) -> np.ndarray:
    """Meet two homogeneous lines into a point."""
    return np.cross(np.asarray(line_a, dtype=float), np.asarray(line_b, dtype=float))


def normalize_homogeneous(point: np.ndarray, *, tol: float = EPS) -> np.ndarray:
    """Normalize a homogeneous point to affine coordinates."""
    point = np.asarray(point, dtype=float)
    if abs(point[-1]) <= tol:
        raise ZeroDivisionError("homogeneous point is at infinity")
    return point / point[-1]


@dataclass(frozen=True)
class Line3D:
    """A 3-D line represented by one point and one unit direction."""

    point: np.ndarray
    direction: np.ndarray

    def __post_init__(self) -> None:
        object.__setattr__(self, "point", np.asarray(self.point, dtype=float))
        object.__setattr__(self, "direction", normalize(self.direction))
        if self.point.shape != (3,):
            raise ValueError("line point must be a 3-vector")
        if self.direction.shape != (3,):
            raise ValueError("line direction must be a 3-vector")

    def sample(self, t_min: float = -2.5, t_max: float = 2.5, n: int = 80) -> np.ndarray:
        t = np.linspace(t_min, t_max, n)
        return self.point + t[:, None] * self.direction


@dataclass(frozen=True)
class Plane3D:
    """A 3-D plane represented by one point and one unit normal."""

    point: np.ndarray
    normal: np.ndarray

    def __post_init__(self) -> None:
        object.__setattr__(self, "point", np.asarray(self.point, dtype=float))
        object.__setattr__(self, "normal", normalize(self.normal))
        if self.point.shape != (3,):
            raise ValueError("plane point must be a 3-vector")
        if self.normal.shape != (3,):
            raise ValueError("plane normal must be a 3-vector")

    def signed_distance(self, point: np.ndarray) -> float:
        return float((np.asarray(point, dtype=float) - self.point) @ self.normal)

    def grid(self, span: float = 2.5, n: int = 18) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        reference = np.array([1.0, 0.0, 0.0])
        if abs(reference @ self.normal) > 0.85:
            reference = np.array([0.0, 1.0, 0.0])
        u = normalize(np.cross(self.normal, reference))
        v = normalize(np.cross(self.normal, u))
        coords = np.linspace(-span, span, n)
        aa, bb = np.meshgrid(coords, coords)
        points = self.point + aa[..., None] * u + bb[..., None] * v
        return points[..., 0], points[..., 1], points[..., 2]


@dataclass(frozen=True)
class LinePlaneIntersection:
    """Classification of a line-plane meet."""

    kind: str
    point: np.ndarray | None
    parameter: float | None
    denominator: float
    signed_distance: float


def line_plane_intersection(
    line: Line3D,
    plane: Plane3D,
    *,
    tol: float = EPS,
) -> LinePlaneIntersection:
    """Classify and compute the meet of a Euclidean line and plane."""
    denominator = float(plane.normal @ line.direction)
    signed_distance = plane.signed_distance(line.point)
    if abs(denominator) <= tol:
        kind = "contained" if abs(signed_distance) <= tol else "parallel"
        return LinePlaneIntersection(kind, None, None, denominator, signed_distance)
    parameter = -signed_distance / denominator
    point = line.point + parameter * line.direction
    return LinePlaneIntersection("point", point, float(parameter), denominator, signed_distance)


def plane_surface_trace(plane: Plane3D, name: str = "plane") -> go.Surface:
    x, y, z = plane.grid()
    return go.Surface(
        x=x,
        y=y,
        z=z,
        name=name,
        opacity=0.28,
        showscale=False,
        colorscale=[[0, COLORS["plane"]], [1, COLORS["plane"]]],
        hoverinfo="skip",
    )


def line_trace(line: Line3D, name: str = "line", color: str = COLORS["line"]) -> go.Scatter3d:
    points = line.sample()
    return go.Scatter3d(
        x=points[:, 0],
        y=points[:, 1],
        z=points[:, 2],
        mode="lines",
        name=name,
        line={"color": color, "width": 7},
    )


def point_trace(point: np.ndarray, name: str = "meet") -> go.Scatter3d:
    return go.Scatter3d(
        x=[point[0]],
        y=[point[1]],
        z=[point[2]],
        mode="markers+text",
        text=[name],
        textposition="top center",
        name=name,
        marker={"color": COLORS["meet"], "size": 7},
    )


def _line_for_angle(angle_degrees: float) -> Line3D:
    angle = np.deg2rad(angle_degrees)
    point = np.array([-1.05, -0.55, -0.70])
    direction = np.array([np.cos(angle), 0.28, np.sin(angle)])
    return Line3D(point, direction)


def line_plane_slider_figure(angles_degrees: Iterable[float] | None = None) -> go.Figure:
    """Build an interactive Plotly figure for line-plane intersection."""
    if angles_degrees is None:
        angles_degrees = np.linspace(14.0, 76.0, 16)
    angles = [float(angle) for angle in angles_degrees]
    plane = Plane3D(point=np.zeros(3), normal=np.array([0.0, 0.0, 1.0]))

    def traces(angle: float) -> list[go.BaseTraceType]:
        line = _line_for_angle(angle)
        hit = line_plane_intersection(line, plane)
        if hit.point is None:
            marker = go.Scatter3d(x=[], y=[], z=[], mode="markers", name="meet")
        else:
            marker = point_trace(hit.point, name=f"meet at {angle:.1f} deg")
        return [plane_surface_trace(plane), line_trace(line), marker]

    initial = traces(angles[0])
    frames = [go.Frame(name=f"{angle:.1f}", data=traces(angle)) for angle in angles]
    steps = [
        {
            "args": [
                [f"{angle:.1f}"],
                {"frame": {"duration": 0, "redraw": True}, "mode": "immediate"},
            ],
            "label": f"{angle:.0f} deg",
            "method": "animate",
        }
        for angle in angles
    ]

    fig = go.Figure(data=initial, frames=frames)
    fig.update_layout(
        title="Line-plane meet: the green point is the intersection",
        width=920,
        height=680,
        margin={"l": 0, "r": 0, "t": 48, "b": 0},
        scene={
            "aspectmode": "cube",
            "xaxis": {"range": [-2.7, 2.7], "title": "x"},
            "yaxis": {"range": [-2.7, 2.7], "title": "y"},
            "zaxis": {"range": [-1.4, 1.6], "title": "z"},
            "camera": {"eye": {"x": 1.45, "y": -1.85, "z": 1.15}},
        },
        sliders=[{"active": 0, "steps": steps, "currentvalue": {"prefix": "line tilt: "}}],
        updatemenus=[
            {
                "type": "buttons",
                "showactive": False,
                "x": 0.02,
                "y": 0.02,
                "buttons": [
                    {
                        "label": "play",
                        "method": "animate",
                        "args": [None, {"frame": {"duration": 260, "redraw": True}}],
                    }
                ],
            }
        ],
        legend={"x": 0.02, "y": 0.98, "bgcolor": "rgba(255,255,255,0.72)"},
    )
    return fig


def affine_line_slider_figure(slopes: Iterable[float] | None = None) -> go.Figure:
    """Build a 2-D Plotly figure showing a homogeneous line-line meet."""
    if slopes is None:
        slopes = np.r_[np.linspace(-0.8, 0.35, 8), np.linspace(0.42, 0.62, 9), np.linspace(0.7, 1.1, 5)]
    slopes = [float(slope) for slope in slopes]
    fixed_slope = 0.5
    fixed_intercept = -0.15
    moving_intercept = 0.65
    xs = np.linspace(-3.0, 3.0, 200)

    p0 = homogeneous_point(-1.0, fixed_slope * -1.0 + fixed_intercept)
    p1 = homogeneous_point(1.0, fixed_slope * 1.0 + fixed_intercept)
    fixed_line = homogeneous_line_from_points(p0, p1)

    def traces(slope: float) -> list[go.BaseTraceType]:
        q0 = homogeneous_point(-1.0, slope * -1.0 + moving_intercept)
        q1 = homogeneous_point(1.0, slope * 1.0 + moving_intercept)
        moving_line = homogeneous_line_from_points(q0, q1)
        meet = homogeneous_intersection(fixed_line, moving_line)
        y_fixed = fixed_slope * xs + fixed_intercept
        y_moving = slope * xs + moving_intercept
        data: list[go.BaseTraceType] = [
            go.Scatter(x=xs, y=y_fixed, mode="lines", name="line A", line={"color": COLORS["line"], "width": 4}),
            go.Scatter(x=xs, y=y_moving, mode="lines", name="line B", line={"color": COLORS["line_alt"], "width": 4}),
        ]
        if abs(meet[-1]) > 1e-8:
            affine = normalize_homogeneous(meet)
            if -3.5 <= affine[0] <= 3.5 and -3.5 <= affine[1] <= 3.5:
                data.append(
                    go.Scatter(
                        x=[affine[0]],
                        y=[affine[1]],
                        mode="markers+text",
                        text=["meet"],
                        textposition="top center",
                        name="meet",
                        marker={"color": COLORS["meet"], "size": 11},
                    )
                )
            else:
                data.append(go.Scatter(x=[], y=[], mode="markers", name="meet outside view"))
        else:
            data.append(go.Scatter(x=[], y=[], mode="markers", name="meet at infinity"))
        return data

    initial = traces(slopes[0])
    frames = [go.Frame(name=f"{slope:.3f}", data=traces(slope)) for slope in slopes]
    steps = [
        {
            "args": [[f"{slope:.3f}"], {"frame": {"duration": 0, "redraw": True}, "mode": "immediate"}],
            "label": f"{slope:.2f}",
            "method": "animate",
        }
        for slope in slopes
    ]
    fig = go.Figure(data=initial, frames=frames)
    fig.update_layout(
        title="Homogeneous meet: finite point becomes a point at infinity near parallelism",
        width=860,
        height=560,
        xaxis={"range": [-3.2, 3.2], "title": "x"},
        yaxis={"range": [-3.2, 3.2], "title": "y", "scaleanchor": "x", "scaleratio": 1},
        sliders=[{"active": 0, "steps": steps, "currentvalue": {"prefix": "slope of line B: "}}],
        margin={"l": 42, "r": 16, "t": 54, "b": 36},
        legend={"x": 0.02, "y": 0.98, "bgcolor": "rgba(255,255,255,0.72)"},
    )
    return fig
