"""Bootstrap the Modern Robotics standalone notebook course."""

from __future__ import annotations

import json
import sys
import textwrap
from pathlib import Path

import nbformat as nbf

SCRIPT_ROOT = Path(__file__).resolve().parent
BOOK_ROOT = SCRIPT_ROOT.parent
sys.path.insert(0, str(BOOK_ROOT))
sys.path.insert(0, str(SCRIPT_ROOT))

from build_modern_robotics_course_indexes import build_book_index, build_chapter_indexes, build_part_indexes
from modern_robotics_inventory import AUTHORS, BOOK_TITLE, CHAPTERS, PARTS, PDF_FILENAME
from utils.visuals import build_chapter_visuals, build_storyboard


def chapter_dir(chapter) -> Path:
    return BOOK_ROOT / chapter.part_slug / chapter.slug


def _bullet(items: tuple[str, ...] | list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def _storyboard_table(chapter) -> str:
    rows = ["| Concept | Representation | Artifact | Inspection target |", "| --- | --- | --- | --- |"]
    for item in build_storyboard(chapter.as_dict()):
        rows.append(f"| {item['concept']} | {item['representation']} | `{item['artifact']}` | {item['inspection']} |")
    return "\n".join(rows)


def chapter_markdown(chapter) -> str:
    terms = ", ".join(chapter.terms)
    translation = _bullet(chapter.translation)
    pitfalls = _bullet(chapter.pitfalls)
    takeaways = _bullet(chapter.takeaways)
    table = _storyboard_table(chapter)
    return f"""
# {chapter.title}

Source orientation: printed pages {chapter.printed_start}-{chapter.printed_end}, PDF pages {chapter.pdf_start}-{chapter.pdf_end}. This notebook is an original visualization-first lesson inspired by the structure of *{BOOK_TITLE}* by {AUTHORS}. It does not quote or reproduce textbook prose, exercises, screenshots, or page crops.

## Chapter Question

{chapter.question}

This question is the thread for the chapter. The goal is not to memorize a list of formulas; it is to make the geometry inspectable. A robot mechanism is a physical machine, but the way we reason about it is through spaces, maps, constraints, tangents, and dual forces. The notebook keeps those objects visible. Every diagram and computation below is designed to answer a local question that a reader can check: what is moving, what is fixed, what map is being applied, what invariant should survive, and where can the model fail?

## Translation Guide

The source chapter or appendix is translated into computational language using these terms: {terms}. The important conversions for this notebook are:

{translation}

The central habit is to name the representation and the invariant at the same time. Coordinates are useful only when we know what geometric object they represent. A column of joint angles may describe a point on a torus, a homogeneous transform may describe a rigid frame, and a matrix rank may reveal an instantaneous loss of motion. The notebook therefore pairs each formula with a small experiment: a plot, a residual, an ellipsoid, a path, a graph, or a constraint surface.

## Route Through the Notebook

1. Establish the objects and conventions needed for {chapter.title.lower()}.
2. Build a concept dependency map so definitions have visible structure.
3. Generate the main visual lab: {chapter.visual_focus}.
4. Run a compact worked example that exposes an invariant.
5. Try an applied lab that changes a parameter and asks what should remain true.
6. Finish with sanity checks that assert artifact existence, image variation, and numerical margins.

This is a standalone course notebook. The PDF can be useful for historical context and exercises, but the lesson here is complete without it. Definitions are restated in fresh language, examples are computed from scratch, and visuals are generated by course-local code. When the notebook mentions a source span, it is a navigation reference rather than a dependency for comprehension.

## Visualization Storyboard

{table}

The first visual is a dependency map. It is intentionally simple: before computing anything, the reader should see which concepts support which later moves. The second visual is the main lab for this chapter. It turns the chapter's core geometry into something that can be inspected rather than imagined. The third visual is a numeric check: a residual, rank, eigenvalue, path length, or comparable margin that can be tested after the figure is built.

## Working Principles

The most reliable way to learn robotics geometry is to move between three views. The first view is symbolic: equations name maps and constraints. The second view is numerical: a small instance exposes scale, rank, conditioning, and residuals. The third view is visual: geometry becomes a shape, path, ellipsoid, cone, graph, or surface. This notebook keeps all three views close together. If a symbolic statement is correct, the numerical experiment should produce the expected small residual or positive margin. If a visual is meaningful, it should make a specific invariant or failure mode easier to see.

For {chapter.title.lower()}, the relevant failure modes are not side details; they are part of the concept. Singularities, chart boundaries, rank loss, time-scaling limits, contact mode changes, and wheel constraints are all examples of geometry asserting itself. A robust robotics model does not pretend those edges are absent. It names them, draws them, and then tests a small case so the reader can recognize the issue in later code.

The visual lab is also meant to be read as an engineering diagnostic. A static equation may hide the fact that a parameter is moving toward a bad region; a plot can show that trend before it becomes a failed solve. A table of metrics may look dry until it is treated as a contract: positive eigenvalues mean the energy model is still physically plausible, rank reveals whether a local map has lost directions, and a nonzero residual says a constraint is not yet satisfied. The notebook keeps those contracts close to the figures so a reader can connect visual judgment with executable checks.

## Applied Lab

{chapter.lab}

In the lab, vary one parameter at a time and predict the direction of change before running the code. For example, ask whether a rank should change, whether a path should lengthen, whether an eigenvalue should stay positive, whether a cone should widen, or whether a coordinate chart should approach a singular value. This prediction step is small, but it is what turns a figure into a mathematical instrument.

## Pitfalls To Watch

{pitfalls}

These pitfalls are deliberately operational. If a computation becomes confusing, check frame labels, units, rank, and the distinction between a physical object and its coordinates. Many robotics errors are not arithmetic mistakes; they are mismatches between a representation and the geometry it claims to encode.

## Takeaways

{takeaways}

By the end of this notebook, the reader should be able to explain the chapter's main object, build a small computed example, interpret the generated visual artifact, and state at least one numerical sanity check that would catch an implementation mistake.
"""


SETUP_CODE = f"""
from pathlib import Path
import json
import math
import sys

import numpy as np

HERE = Path.cwd().resolve()
BOOK_ROOT = next(
    parent for parent in [HERE, *HERE.parents]
    if (parent / "AGENTS.md").exists() and (parent / "{PDF_FILENAME}").exists()
)
if str(BOOK_ROOT) not in sys.path:
    sys.path.insert(0, str(BOOK_ROOT))

from utils.artifacts import display_artifact, save_json
from utils.validation import assert_artifact, image_stats

print(f"BOOK_ROOT={{BOOK_ROOT}}")
"""


WORKED_EXAMPLE_CODE = """
from utils.kinematics import planar_arm_points, planar_jacobian, manipulability_measure
from utils.lie import adjoint, se3_exp, se3_log, so3_exp, so3_log, transform_from, wrench_power

lengths = np.array([1.0, 0.75, 0.45])
theta = np.array([0.45, -0.8, 0.6])
points = planar_arm_points(lengths, theta)
J = planar_jacobian(lengths, theta)
R = so3_exp(np.array([0.2, -0.1, 0.35]))
round_trip = np.linalg.norm(so3_log(R) - np.array([0.2, -0.1, 0.35]))
T = transform_from(R, np.array([0.25, -0.1, 0.4]))
twist = np.array([0.1, -0.2, 0.3, 0.4, 0.2, -0.1])
wrench = np.array([0.3, 0.1, -0.2, 1.0, -0.4, 0.2])
power_before = wrench_power(twist, wrench)
power_after = wrench_power(adjoint(T) @ twist, np.linalg.inv(adjoint(T)).T @ wrench)
worked_example = {
    "endpoint": points[-1].round(4).tolist(),
    "jacobian_rank": int(np.linalg.matrix_rank(J)),
    "manipulability": float(manipulability_measure(J)),
    "rotation_log_round_trip": float(round_trip),
    "power_pairing_error": float(abs(power_before - power_after)),
}
worked_example
"""


LAB_CODE = """
from utils.control import pd_response
from utils.dynamics import two_link_mass_matrix
from utils.grasping import friction_cone, grasp_matrix
from utils.mobile import mecanum_wheel_matrix, unicycle_rollout
from utils.planning import cubic_time_scaling, dijkstra_grid, quintic_time_scaling

theme = CHAPTER["theme"]
if theme in {"configuration", "kinematics"}:
    sweep = np.linspace(-np.pi, np.pi, 90)
    values = [manipulability_measure(planar_jacobian(np.array([1.0, 0.8]), np.array([0.25, q]))) for q in sweep]
    lab_summary = {"theme": theme, "max_manipulability": float(np.max(values)), "min_manipulability": float(np.min(values))}
elif theme in {"rigid", "appendix"}:
    angles = np.linspace(0.0, 0.95 * np.pi, 60)
    residuals = [np.linalg.norm(so3_log(so3_exp(np.array([0.0, 0.0, a]))) - np.array([0.0, 0.0, a])) for a in angles]
    lab_summary = {"theme": theme, "max_rotation_residual": float(np.max(residuals))}
elif theme == "dynamics":
    eigs = np.array([np.linalg.eigvalsh(two_link_mass_matrix(q)) for q in np.linspace(-np.pi, np.pi, 80)])
    lab_summary = {"theme": theme, "minimum_mass_eigenvalue": float(eigs.min())}
elif theme == "planning":
    t = np.linspace(0, 1, 100)
    lab_summary = {"theme": theme, "cubic_midpoint": float(cubic_time_scaling(np.array([0.5]), 1.0)[0]), "quintic_midpoint": float(quintic_time_scaling(np.array([0.5]), 1.0)[0])}
elif theme == "contact":
    cone = friction_cone(np.array([0.0, 1.0]), 0.5)
    G = grasp_matrix(np.array([[1.0, 0.0], [-0.5, 0.86], [-0.5, -0.86]]), np.array([[-1.0, 0.0], [0.5, -0.86], [0.5, 0.86]]))
    lab_summary = {"theme": theme, "cone_samples": int(len(cone)), "grasp_rank": int(np.linalg.matrix_rank(G))}
elif theme == "mobile":
    controls = np.c_[np.ones(80) * 0.5, np.ones(80) * 0.3]
    path = unicycle_rollout(controls)
    lab_summary = {"theme": theme, "wheel_map_rank": int(np.linalg.matrix_rank(mecanum_wheel_matrix())), "final_pose": path[-1].round(4).tolist()}
else:
    lab_summary = {"theme": theme}

lab_summary
"""


def make_chapter_notebook(chapter) -> None:
    chapter_data = chapter.as_dict()
    nb = nbf.v4.new_notebook()
    nb["metadata"]["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
    nb["metadata"]["language_info"] = {"name": "python", "pygments_lexer": "ipython3"}
    nb["cells"] = [
        nbf.v4.new_markdown_cell(textwrap.dedent(chapter_markdown(chapter)).strip()),
        nbf.v4.new_code_cell(textwrap.dedent(SETUP_CODE).strip()),
        nbf.v4.new_code_cell(
            "CHAPTER = "
            + json.dumps(chapter_data, indent=2)
            + "\n\nfrom utils.visuals import build_storyboard\nstoryboard = build_storyboard(CHAPTER)\nstoryboard"
        ),
        nbf.v4.new_code_cell(
            "from utils.visuals import build_chapter_visuals\n\n"
            "outputs = build_chapter_visuals(CHAPTER)\n"
            "for artifact in outputs['figures']:\n"
            "    display_artifact(artifact, width=760)\n"
            "outputs['metrics']"
        ),
        nbf.v4.new_markdown_cell(
            "## Worked Example\n\nThe worked example below is intentionally compact and reusable. It checks a planar arm Jacobian, a rotation exponential/logarithm round trip, and the twist/wrench power pairing under a frame transform. These are small tests, but they exercise the same representation discipline used throughout the course."
        ),
        nbf.v4.new_code_cell(textwrap.dedent(WORKED_EXAMPLE_CODE).strip()),
        nbf.v4.new_markdown_cell(
            "## Applied Lab\n\nThe applied lab changes behavior based on the chapter theme. It produces a small numerical summary that should agree with the visual lab: ranks should be plausible, residuals should be small, paths should have nonzero length, and positive-definite quantities should stay positive."
        ),
        nbf.v4.new_code_cell(textwrap.dedent(LAB_CODE).strip()),
        nbf.v4.new_markdown_cell(
            "## Sanity Checks\n\nThe final cell asserts that the generated artifacts exist, are large enough to be useful, and have nontrivial pixel variation. It also stores a JSON summary under the chapter's artifact subtree so the notebook leaves a machine-checkable trace."
        ),
        nbf.v4.new_code_cell(
            "artifact_stats = {}\n"
            "for artifact in outputs['figures']:\n"
            "    resolved = assert_artifact(artifact)\n"
            "    stats = image_stats(resolved)\n"
            "    assert stats['pixel_std'] > 2.0, f'low variation image: {resolved}'\n"
            "    artifact_stats[resolved.name] = stats\n"
            "assert_artifact(outputs['checks'], min_size=100)\n"
            "sanity = {'chapter': CHAPTER['slug'], 'metrics': outputs['metrics'], 'worked_example': worked_example, 'lab_summary': lab_summary, 'artifact_stats': artifact_stats}\n"
            "sanity_path = save_json(sanity, CHAPTER['slug'], 'checks', 'notebook-sanity.json')\n"
            "display_artifact(sanity_path)\n"
            "sanity"
        ),
    ]
    path = chapter_dir(chapter) / chapter.notebook
    path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, path)


def bootstrap() -> None:
    for part_slug, _ in PARTS:
        (BOOK_ROOT / part_slug).mkdir(parents=True, exist_ok=True)
    (BOOK_ROOT / "artifacts").mkdir(exist_ok=True)
    for chapter in CHAPTERS:
        chapter_dir(chapter).mkdir(parents=True, exist_ok=True)
        make_chapter_notebook(chapter)
        build_chapter_visuals(chapter.as_dict())
    build_book_index()
    build_part_indexes()
    build_chapter_indexes()
    print(f"Bootstrapped {len(CHAPTERS)} canonical notebooks and initial artifacts.")


if __name__ == "__main__":
    bootstrap()
