"""Verified source map for the PAG notebook course.

The PDF scan has 15 front-matter pages before printed page 1, so
``pdf_page = printed_page + 15`` for the main text.
"""

BOOK_TITLE = "Principles of Algebraic Geometry"
BOOK_AUTHOR = "Phillip Griffiths and Joseph Harris"
SOURCE = "Principles of Algebraic Geometry.pdf"
PDF_PAGE_OFFSET = 15


def pdf_span(printed_start: int, printed_end: int) -> str:
    return f"{printed_start + PDF_PAGE_OFFSET}-{printed_end + PDF_PAGE_OFFSET}"


def section(title: str, printed_start: int) -> dict:
    return {"title": title, "printed_start": printed_start, "pdf_start": printed_start + PDF_PAGE_OFFSET}


ENTRIES = [
    {
        "kind": "chapter",
        "number": 0,
        "label": "Chapter 00",
        "title": "Foundational Material",
        "folder": "chapter-00-foundational-material",
        "notebook": "00-foundational-material.ipynb",
        "topic": "chapter-00",
        "printed_span": "1-127",
        "pdf_span": pdf_span(1, 127),
        "focus": "Several complex variables, complex manifolds, sheaves, topology, vector bundles, harmonic theory, and Kahler manifolds as reusable machinery.",
        "sections": [
            section("Rudiments of Several Complex Variables", 2),
            section("Cauchy's Formula and Applications", 2),
            section("Several Variables", 6),
            section("Weierstrass Theorems and Corollaries", 7),
            section("Analytic Varieties", 12),
            section("Complex Manifolds", 14),
            section("Submanifolds and Subvarieties", 18),
            section("De Rham and Dolbeault Cohomology", 23),
            section("Calculus on Complex Manifolds", 27),
            section("Sheaves and Cohomology", 34),
            section("Origins: The Mittag-Leffler Problem", 34),
            section("Sheaves", 35),
            section("Cohomology of Sheaves", 38),
            section("The de Rham Theorem", 43),
            section("The Dolbeault Theorem", 45),
            section("Topology of Manifolds", 49),
            section("Intersection of Cycles", 49),
            section("Poincare Duality", 53),
            section("Intersection of Analytic Cycles", 60),
            section("Vector Bundles, Connections, and Curvature", 66),
            section("Complex and Holomorphic Vector Bundles", 66),
            section("Metrics, Connections, and Curvature", 71),
            section("Harmonic Theory on Compact Complex Manifolds", 80),
            section("The Hodge Theorem", 80),
            section("Proof of the Hodge Theorem I: Local Theory", 84),
            section("Proof of the Hodge Theorem II: Global Theory", 92),
            section("Applications of the Hodge Theorem", 100),
            section("Kahler Manifolds", 106),
            section("The Kahler Condition", 106),
            section("The Hodge Identities and the Hodge Decomposition", 111),
            section("The Lefschetz Decomposition", 118),
        ],
    },
    {
        "kind": "chapter",
        "number": 1,
        "label": "Chapter 01",
        "title": "Complex Algebraic Varieties",
        "folder": "chapter-01-complex-algebraic-varieties",
        "notebook": "01-complex-algebraic-varieties.ipynb",
        "topic": "chapter-01",
        "printed_span": "128-211",
        "pdf_span": pdf_span(128, 211),
        "focus": "Divisors, line bundles, vanishing, projective varieties, Kodaira embedding, blowups, Grassmannians, and Schubert calculus.",
        "sections": [
            section("Divisors and Line Bundles", 129),
            section("Divisors", 129),
            section("Line Bundles", 132),
            section("Chern Classes of Line Bundles", 139),
            section("Some Vanishing Theorems and Corollaries", 148),
            section("The Kodaira Vanishing Theorem", 148),
            section("The Lefschetz Theorem on Hyperplane Sections", 156),
            section("Theorem B", 159),
            section("The Lefschetz Theorem on (1,1)-classes", 161),
            section("Algebraic Varieties", 164),
            section("Analytic and Algebraic Varieties", 164),
            section("Degree of a Variety", 171),
            section("Tangent Spaces to Algebraic Varieties", 175),
            section("The Kodaira Embedding Theorem", 176),
            section("Line Bundles and Maps to Projective Space", 176),
            section("Blowing Up", 182),
            section("Proof of the Kodaira Theorem", 189),
            section("Grassmannians", 193),
            section("Definitions", 193),
            section("The Cell Decomposition", 194),
            section("The Schubert Calculus", 197),
            section("Universal Bundles", 207),
            section("The Plucker Embedding", 209),
        ],
    },
    {
        "kind": "chapter",
        "number": 2,
        "label": "Chapter 02",
        "title": "Riemann Surfaces and Algebraic Curves",
        "folder": "chapter-02-riemann-surfaces-and-algebraic-curves",
        "notebook": "02-riemann-surfaces-and-algebraic-curves.ipynb",
        "topic": "chapter-02",
        "printed_span": "212-363",
        "pdf_span": pdf_span(212, 363),
        "focus": "Curves, Riemann-Hurwitz, Abel theorem, Riemann-Roch, Plucker formulas, correspondences, tori, abelian varieties, and Jacobians.",
        "sections": [
            section("Preliminaries", 213),
            section("Embedding Riemann Surfaces", 213),
            section("The Riemann-Hurwitz Formula", 216),
            section("The Genus Formula", 219),
            section("Cases g = 0,1", 222),
            section("Abel's Theorem", 224),
            section("Abel's Theorem - First Version", 224),
            section("The First Reciprocity Law and Corollaries", 229),
            section("Abel's Theorem - Second Version", 232),
            section("Jacobi Inversion", 235),
            section("Linear Systems on Curves", 240),
            section("Reciprocity Law II", 240),
            section("The Riemann-Roch Formula", 243),
            section("Canonical Curves", 246),
            section("Special Linear Systems I", 249),
            section("Hyperelliptic Curves and Riemann's Count", 253),
            section("Special Linear Systems II", 259),
            section("Plucker Formulas", 263),
            section("Associated Curves", 263),
            section("Ramification", 264),
            section("The General Plucker Formulas I", 268),
            section("The General Plucker Formulas II", 271),
            section("Weierstrass Points", 273),
            section("Plucker Formulas for Plane Curves", 277),
            section("Correspondences", 282),
            section("Definitions and Formulas", 282),
            section("Geometry of Space Curves", 290),
            section("Special Linear Systems III", 298),
            section("Complex Tori and Abelian Varieties", 300),
            section("The Riemann Conditions", 300),
            section("Line Bundles on Complex Tori", 307),
            section("Theta-Functions", 317),
            section("The Group Structure on an Abelian Variety", 324),
            section("Intrinsic Formulations", 326),
            section("Curves and Their Jacobians", 333),
            section("Preliminaries on Jacobians", 333),
            section("Riemann's Theorem", 338),
            section("Riemann's Singularity Theorem", 341),
            section("Special Linear Systems IV", 349),
            section("Torelli's Theorem", 359),
        ],
    },
    {
        "kind": "chapter",
        "number": 3,
        "label": "Chapter 03",
        "title": "Further Techniques",
        "folder": "chapter-03-further-techniques",
        "notebook": "03-further-techniques.ipynb",
        "topic": "chapter-03",
        "printed_span": "364-468",
        "pdf_span": pdf_span(364, 468),
        "focus": "Currents, residues, intersections, Chern classes, fixed-point formulas, spectral sequences, and Leray-style bookkeeping.",
        "sections": [
            section("Distributions and Currents", 366),
            section("Definitions; Residue Formulas", 366),
            section("Smoothing and Regularity", 373),
            section("Cohomology of Currents", 382),
            section("Applications of Currents to Complex Analysis", 385),
            section("Currents Associated to Analytic Varieties", 385),
            section("Intersection Numbers of Analytic Varieties", 392),
            section("The Levi Extension and Proper Mapping Theorems", 395),
            section("Chern Classes", 400),
            section("Definitions", 400),
            section("The Gauss Bonnet Formulas", 409),
            section("Remarks Concerning Chern Classes of Holomorphic Vector Bundles", 416),
            section("Fixed-Point and Residue Formulas", 419),
            section("The Lefschetz Fixed-Point Formula", 419),
            section("The Holomorphic Lefschetz Fixed-Point Formula", 422),
            section("The Bott Residue Formula", 426),
            section("The General Hirzebruch-Riemann-Roch Formula", 435),
            section("Spectral Sequences and Applications", 438),
            section("Spectral Sequences of Filtered and Bigraded Complexes", 438),
            section("Hypercohomology", 445),
            section("Differentials of the Second Kind", 454),
            section("The Leray Spectral Sequence", 462),
        ],
    },
    {
        "kind": "chapter",
        "number": 4,
        "label": "Chapter 04",
        "title": "Surfaces",
        "folder": "chapter-04-surfaces",
        "notebook": "04-surfaces.ipynb",
        "topic": "chapter-04",
        "printed_span": "469-646",
        "pdf_span": pdf_span(469, 646),
        "focus": "Intersection theory on surfaces, blowups, rational and irrational surfaces, ruled and elliptic surfaces, K3 and Enriques surfaces, Noether formula, and singularities.",
        "sections": [
            section("Preliminaries", 470),
            section("Intersection Numbers, the Adjunction Formula, and Riemann-Roch", 470),
            section("Blowing Up and Down", 473),
            section("The Quadric Surface", 478),
            section("The Cubic Surface", 480),
            section("Rational Maps", 489),
            section("Rational and Birational Maps", 489),
            section("Curves on an Algebraic Surface", 498),
            section("The Structure of Birational Maps Between Surfaces", 510),
            section("Rational Surfaces I", 513),
            section("Noether's Lemma", 513),
            section("Rational Ruled Surfaces", 514),
            section("The General Rational Surface", 520),
            section("Surfaces of Minimal Degree", 522),
            section("Curves of Maximal Genus", 527),
            section("Steiner Constructions", 528),
            section("The Enriques-Petri Theorem", 533),
            section("Rational Surfaces II", 536),
            section("The Castelnuovo-Enriques Theorem", 536),
            section("The Enriques Surface", 541),
            section("Cubic Surfaces Revisited", 545),
            section("The Intersection of Two Quadrics in P4", 550),
            section("Some Irrational Surfaces", 552),
            section("The Albanese Map", 552),
            section("Irrational Ruled Surfaces", 553),
            section("A Brief Introduction to Elliptic Surfaces", 564),
            section("Kodaira Number and the Classification Theorem I", 572),
            section("The Classification Theorem II", 582),
            section("K-3 Surfaces", 590),
            section("Enriques Surfaces", 594),
            section("Noether's Formula", 600),
            section("Noether's Formula for Smooth Hypersurfaces", 600),
            section("Blowing Up Submanifolds", 602),
            section("Ordinary Singularities of Surfaces", 611),
            section("Noether's Formula for General Surfaces", 618),
            section("Some Examples", 628),
            section("Isolated Singularities of Surfaces", 636),
        ],
    },
    {
        "kind": "chapter",
        "number": 5,
        "label": "Chapter 05",
        "title": "Residues",
        "folder": "chapter-05-residues",
        "notebook": "05-residues.ipynb",
        "topic": "chapter-05",
        "printed_span": "647-732",
        "pdf_span": pdf_span(647, 732),
        "focus": "Residues, global residue theorem, transformation laws, local duality, projective applications, Koszul complexes, coherent sheaves, global Ext, and vector bundles.",
        "sections": [
            section("Elementary Properties of Residues", 649),
            section("Definition and Cohomological Interpretation", 649),
            section("The Global Residue Theorem", 655),
            section("The Transformation Law and Local Duality", 656),
            section("Applications of Residues", 662),
            section("Intersection Numbers", 662),
            section("Finite Holomorphic Mappings", 667),
            section("Applications to Plane Projective Geometry", 670),
            section("Rudiments of Commutative and Homological Algebra with Applications", 678),
            section("Commutative Algebra", 678),
            section("Homological Algebra", 682),
            section("The Koszul Complex and Applications", 687),
            section("A Brief Tour Through Coherent Sheaves", 695),
            section("Global Duality", 705),
            section("Global Ext", 705),
            section("Explanation of the General Global Duality Theorem", 707),
            section("Global Ext and Vector Fields with Isolated Zeros", 708),
            section("Global Duality and Superabundance of Points on a Surface", 712),
            section("Extensions of Modules", 722),
            section("Points on a Surface and Rank-Two Vector Bundles", 726),
            section("Residues and Vector Bundles", 729),
        ],
    },
    {
        "kind": "chapter",
        "number": 6,
        "label": "Chapter 06",
        "title": "The Quadric Line Complex",
        "folder": "chapter-06-the-quadric-line-complex",
        "notebook": "06-the-quadric-line-complex.ipynb",
        "topic": "chapter-06",
        "printed_span": "733-804",
        "pdf_span": pdf_span(733, 804),
        "focus": "Quadrics, linear systems, Grassmannian G(2,4), line complexes, Kummer surface, configurations, group law, and rationality.",
        "sections": [
            section("Preliminaries: Quadrics", 734),
            section("Rank of a Quadric", 734),
            section("Linear Spaces on Quadrics", 735),
            section("Linear Systems of Quadrics", 741),
            section("Lines on Linear Systems of Quadrics", 746),
            section("The Problem of Five Conies", 749),
            section("The Quadric Line Complex: Introduction", 756),
            section("Geometry of the Grassmannian G(2,4)", 756),
            section("Line Complexes", 759),
            section("The Quadric Line Complex and Associated Kummer Surface I", 762),
            section("Singular Lines of the Quadric Line Complex", 767),
            section("Two Configurations", 773),
            section("Lines on the Quadric Line Complex", 778),
            section("The Variety of Lines on the Quadric Line Complex", 778),
            section("Curves on the Variety of Lines", 780),
            section("Two Configurations Revisited", 784),
            section("The Group Law", 787),
            section("The Quadric Line Complex: Reprise", 791),
            section("The Quadric Line Complex and Associated Kummer Surface II", 791),
            section("Rationality of the Quadric Line Complex", 796),
        ],
    },
]


def canonical_notebooks(root):
    return [root / entry["folder"] / entry["notebook"] for entry in ENTRIES]
